// tag::ess[]
. Log into {ess-console}[Elastic Cloud] and select your deployment.
In {kib}, select **Add data**, then search for and select "Elastic APM".
If the integration is already installed, under the polices tab, select **Actions** > **Edit integration**.
If the integration has not been installed, select **Add Elastic APM**.
Copy the URL. If you're using Agent authorization, copy the Secret token as well.

. Configure the APM Integration as a collector for your Jaeger agents.
+
As of this writing, the Jaeger agent binary offers the following CLI flags,
which can be used to enable TLS, output to {ecloud}, and set the APM Integration secret token:
+
[source,terminal]
----
--reporter.grpc.tls.enabled=true
--reporter.grpc.host-port=<apm-url:443>
--agent.tags="elastic-apm-auth=Bearer <secret-token>"
----

TIP: For the equivalent environment variables,
change all letters to upper-case and replace punctuation with underscores (`_`).
See the https://www.jaegertracing.io/docs/1.27/cli/[Jaeger CLI flags documentation] for more information.

// end::ess[]

// tag::self-managed[]
. Configure the APM Integration as a collector for your Jaeger agents.
In {kib}, select **Add data**, then search for and select "Elastic APM".
If the integration is already installed, under the polices tab, select **Actions** > **Edit integration**.
If the integration has not been installed, select **Add Elastic APM**.
Copy the Host. If you're using Agent authorization, copy the Secret token as well.
+
As of this writing, the Jaeger agent binary offers the `--reporter.grpc.host-port` CLI flag.
Use this to define the host and port that the APM Integration is listening on:
+
[source,terminal]
----
--reporter.grpc.host-port=<apm-endpoint:8200>
----

. (Optional) Enable encryption
+
When TLS is enabled for the APM Integration, Jaeger agents must also enable TLS communication:
+
[source,terminal]
----
--reporter.grpc.tls.enabled=true
----

. (Optional) Enable token-based authorization
+
A secret token or API key can be used to ensure only authorized Jaeger agents can send data to the APM Integration.
When enabled, use an agent level tag to authorize Jaeger agent communication with the APM Server:
+
[source,terminal]
----
--agent.tags="elastic-apm-auth=Bearer <secret-token>"
----

TIP: For the equivalent environment variables,
change all letters to upper-case and replace punctuation with underscores (`_`).
See the https://www.jaegertracing.io/docs/1.27/cli/[Jaeger CLI flags documentation] for more information.

// end::self-managed[]
