// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package include

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("apm-server", "XPackFields", asset.ModuleFieldsPri, AssetXPackFields); err != nil {
		panic(err)
	}
}

// AssetXPackFields returns asset data.
// This is the base64 encoded gzipped contents of x-pack/apm-server.
func AssetXPackFields() string {
	return "eJycks9unTwQxfc8xSjrwAOw+KTvASJFavfR1D5wRwHbnRk3vW9fQeCW29KqLTvmz/Gxf6elV1x74jK3rpyMg0tO7QxXCdZ+LRxeGyIXn9DTw//PT/Tx+xw9vc89NEQRFlTKUu7pv4aIaJk+qNKm+kic4lmjtYIggwQqmgvUBfa4Kik+V1FJI00SkAyRBrBXhZHVcCE28gvoIuZ5VJ5pEEyR/FrQNUR2yeovIadBxp5cKxp6H7F+PaClxDP6o6u1TqtET6PmWrZKvCaeJfQ08GTYirvY9rvrxap8EDuTuzdyXL7d5tbZ9886JwD271nR8jgqRnbEwyvl4Y7D7ta6pjkkwwr/PhIfCv9JFhadnTWxguoKMuvC522hq+xYTC28YW5rUiZ2pHClT/A3IJEkc60z0nIXg36RAPsrypsHeFegkuMd6imn8W46wlzS+jDddty/ZeNHvgorORleXGZ0IdfkP5G+ufn1otW5q3a++S0AAP//+xA6Bg=="
}
