// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package include

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("apm-server", "XPackFields", asset.ModuleFieldsPri, AssetXPackFields); err != nil {
		panic(err)
	}
}

// AssetXPackFields returns asset data.
// This is the base64 encoded gzipped contents of x-pack/apm-server.
func AssetXPackFields() string {
	return "eJxskUGuozAQRPecopR1nAN4MdIcIFIWsx+17Ma0ArZ/t5F+bv8VAvlEgh1V1c9lt8OdHx5UJ9eUslFoUrKbuKkEc9+Vwr0DmrSRPU5/b1f8+83h+sqdOiCyBZX6lD3+dADwTO+oWKlnUI5HhrPKQXoJqFoqaxO280JS/ppFJSeMEjgbR/RMbVY22BwGkKENjEGslaQ0oRceI9qj8qUDbCja/oeSe0keTWfu8IqYXw5wyDSx37dadCwIj6RlrqsSH5kmCR49jcaruMHW340XZ6Ud7Aj3WWQ//L7N29nmj5yDBWzfTdlRSsqJGsfdK5X+Yw9bW7t0PwEAAP//VQmqXQ=="
}
