// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package include

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("apm-server", "XPackFields", asset.ModuleFieldsPri, AssetXPackFields); err != nil {
		panic(err)
	}
}

// AssetXPackFields returns asset data.
// This is the base64 encoded gzipped contents of x-pack/apm-server.
func AssetXPackFields() string {
	return "eJycksFu3DAMRO/+CiLn2B/gQ4Gg5xQB2nugyGMvEVtSSSrp/n0hr73r7RppU99MUcMR39T0imNLLk21iQvqvHEM9QQT9lr/Ss6/VkTGNqKlu4enR/px6aPHU99dRdRBvXAq5Za+VEREpXujSovqPbnQ7R3UmuC5Z09JYoIYQ+9nJcHPzMJhoJE9gqKjHs6yQEmzP5BTsgPowGpxEDdRzxg7smNCUxHpIYo9+xh6Hloyyajo1KLtPKCm4Ca0W1dznWaJlgaJOS2V7hjcxL6l3o2KpbiKLb+rXpfFbcT25K6NbC+fX3M+We/vnewAWL8nQe2GQTA4Q7fZUuyvOKxutamqTTI0uY8j8T25f8lC0VlZkxNQnkFGKXzeC11xhmKq8IaazkkZnSH4I73A3oFAHNQkTwjlLQp5Yw/9FOXFA6xJEI7dFeoxhqHaWenXLIJg1Dlz5OM44rS0k8T8DDuwEt5KFweaeBxZ4WPoZnuX+WUR/xevP9IFNQ4zsmZZxIdB25W+zd9lgEBTDIpn4wmNjznYVbBuNrazt295eoEUqpsIxmxDnIkvpJu/Ttc8NVk/Pf7hMnSNd/FyY+D+hMxLPCP7HQAA//9EqJ5D"
}
