:issue: https://github.com/elastic/apm-server/issues/
:pull: https://github.com/elastic/apm-server/pull/

[[breaking-changes]]
== Breaking Changes
APM Server is built on top of {beats-ref}/index.html[libbeat].
As such, any breaking change in libbeat is also considered to be a breaking change in APM Server.

[float]
=== 7.15

The following breaking changes were introduced in 7.15:

- `network.connection_type` is now `network.connection.type` {pull}5671[5671]
- `transaction.page` and `error.page` no longer recorded {pull}5872[5872]
- experimental:["This breaking change applies to the experimental tail-based sampling feature."] `apm-server.sampling.tail` now requires `apm-server.data_streams.enabled` {pull}5952[5952]
- beta:["This breaking change applies to the beta APM integration."] The `traces-sampled-*` data stream is now `traces-apm.sampled-*` {pull}5952[5952]

[float]
=== 7.14
There are no breaking changes in APM Server.

[float]
=== 7.13
There are no breaking changes in APM Server.

[float]
=== 7.12

There are three breaking changes to be aware of;
these changes only impact users ingesting data with
{apm-server-ref-v}/jaeger.html[Jaeger clients].

* Leading 0s are no longer removed from Jaeger client trace/span ids.
+
--
This change ensures distributed tracing continues to work across platforms by creating
consistent, full trace/span IDs from Jaeger clients, Elastic APM agents,
and OpenTelemetry SDKs.
--

* Jaeger spans will now have a type of "app" where they previously were "custom".
+
--
If the Jaeger span type is not inferred, it will now be "app".
This aligns with the OpenTelemetry Collector exporter
and improves the functionality of the _time spent by span type_ charts in the APM app.
--

* Jaeger spans may now have a more accurate outcome of "unknown".
+
--
Previously, a "success" outcome was assumed when a span didn't fail.
The new default assigns "unknown", and only sets an outcome of "success" or "failure" when
the outcome is explicitly known.
This change aligns with Elastic APM agents and the OpenTelemetry Collector exporter.
--

[float]
=== 7.11
There are no breaking changes in APM Server.

[float]
=== 7.10
There are no breaking changes in APM Server.

[float]
=== 7.9
There are no breaking changes in APM Server.

[float]
=== 7.8
There are no breaking changes in APM Server.

[float]
=== 7.7
There are no breaking changes in APM Server.
However, a previously hardcoded feature is now configurable.
Failing to follow these <<upgrading-to-77,upgrade steps>> will result in increased span metadata ingestion when upgrading to version 7.7.

[float]
=== 7.6
There are no breaking changes in APM Server.

[float]
=== 7.5
The following breaking changes have been introduced in 7.5:

* Introduced dedicated `apm-server.ilm.setup.*` flags.
This means you can now customize ILM behavior from within the APM Server configuration.
As a side effect, `setup.template.*` settings will be ignored for ILM related templates per event type.
See {apm-server-ref}/ilm.html[set up ILM] for more information.

* By default, ILM policies will not longer be versioned.
All event types will switch to the new default policy: rollover after 30 days or when reaching a size 50gb.
See {apm-server-ref}/ilm.html[default policy] for more information.

* To make use of all the new features introduced in 7.5,
you must ensure you are using version 7.5+ of APM Server and version 7.5+ of Kibana.

[float]
=== 7.0
The following breaking changes have been introduced in 7.0:

* Removed deprecated Intake v1 API endpoints.
Upgrade agents to a version that supports APM Server ≥ 6.5.
{apm-guide-ref}/breaking-7.0.0.html#breaking-remove-v1[More information].
* Moved fields in Elasticsearch to be compliant with the Elastic Common Schema (ECS).
{apm-guide-ref}/breaking-7.0.0.html#breaking-ecs[More information and changed fields].
* {beats-ref}/breaking-changes-7.0.html[Breaking changes in libbeat]

[float]
=== 6.5
There are no breaking changes in APM Server.
Advanced users may find the <<upgrading-to-65,upgrading to 6.5 guide>> useful.

[float]
=== 6.4
The following breaking changes have been introduced in 6.4:

* Indexing the `onboarding` document in it's own index by default.

[float]
=== 6.3
The following breaking changes have been introduced in 6.3:

* Indexing events in separate indices by default.
* {beats-ref-63}/breaking-changes-6.3.html[Breaking changes in libbeat]

[float]
=== 6.2

APM Server is now GA (generally available).