[[exploring-es-data]]
= Explore data in {es}

IMPORTANT: {deprecation-notice-data}
If you've already upgraded, see <<apm-data-streams>>.

Elastic APM data is stored in data streams.
include::../data-streams.asciidoc[tag=data-streams]

The namespace default is `default`.
To configure a custom namespace, set `data_streams.namespace`:

[source,yaml]
----
apm-server:
  data_streams.namespace: custom_namespace
----

[discrete]
[[apm-data-streams-list-standalone]]
== APM data streams

By type, the APM data streams are:

Traces::
Traces are comprised of {apm-guide-ref}/data-model.html[spans and transactions].
Traces are stored in the following data streams:
+
include::../data-streams.asciidoc[tag=traces-data-streams]

Metrics::
Metrics include application-based metrics, aggregation metrics, and basic system metrics.
Metrics are stored in the following data streams:
+
include::../data-streams.asciidoc[tag=metrics-data-streams]

Logs::
Logs include application error events and application logs.
Logs are stored in the following data streams:
+
include::../data-streams.asciidoc[tag=logs-data-streams]

[float]
[[sample-apm-document]]
== Sample APM documents

Sample documents for each of the APM event types are available on these pages:

* <<transaction-indices>>
* <<span-indices>>
* <<error-indices>>
* <<metricset-indices>>
* <<sourcemap-indices>>

[float]
[[elasticsearch-query-examples]]
== {es} query examples

The following examples enable you to interact with {es}'s REST API.
One possible way to do this is using {kib}'s
{kibana-ref}/console-kibana.html[{dev-tools-app} console].

Data streams, templates, and index-level operations can also be manged via {kib}'s
{kibana-ref}/managing-indices.html[Index management] panel.

To see an overview of existing data streams, run:
["source","sh"]
----
GET /_data_stream/*apm*
----
// CONSOLE

To query a specific event type, for example, application traces:
["source","sh",subs="attributes"]
----
GET traces-apm*/_search
----
// CONSOLE

If you are interested in the _settings_ and _mappings_ of the Elastic APM indices,
first, run a query to find template names:

["source","sh"]
----
GET _cat/templates/*apm*
----
// CONSOLE

Then, retrieve the specific template you are interested in:
["source","sh"]
----
GET  /_template/your-template-name
----
// CONSOLE


include::./transaction-indices.asciidoc[]
include::./span-indices.asciidoc[]
include::./error-indices.asciidoc[]
include::./metricset-indices.asciidoc[]
include::./sourcemap-indices.asciidoc[]
