[[exploring-es-data]]
= Explore data in {es}

* <<elasticsearch-query-examples>>
* <<sample-apm-document>>
* <<metricset-indices>>

[float]
[[elasticsearch-query-examples]]
== {es} query examples

Elastic APM data is stored in <<apm-data-streams>>.

The following examples enable you to interact with {es}'s REST API.
One possible way to do this is using {kib}'s
{kibana-ref}/console-kibana.html[{dev-tools-app} console].

Data streams, templates, and index-level operations can also be manged via {kib}'s
{kibana-ref}/managing-indices.html[Index management] panel.

To see an overview of existing data streams, run:
["source","sh"]
----
GET /_data_stream/*apm*
----
// CONSOLE

To query a specific event type, for example, application traces:
["source","sh",subs="attributes"]
----
GET traces-apm*/_search
----
// CONSOLE

If you are interested in the _settings_ and _mappings_ of the Elastic APM indices,
first, run a query to find template names:

["source","sh"]
----
GET _cat/templates/*apm*
----
// CONSOLE

Then, retrieve the specific template you are interested in:
["source","sh"]
----
GET  /_template/your-template-name
----
// CONSOLE

[float]
[[sample-apm-document]]
== Sample APM documents

Sample documents for each of the APM event types are available below:

[%collapsible]
.Transaction documents
====
Example transaction documents indexed in {es}:

[source,json]
----
include::../data/elasticsearch/generated/transactions.json[]
----
====

[%collapsible]
.Span documents
====
Example span documents indexed in {es}:

[source,json]
----
include::../data/elasticsearch/generated/spans.json[]
----
====

[%collapsible]
.Error documents
====
Example error documents indexed in {es}:

[source,json]
----
include::../data/elasticsearch/generated/errors.json[]
----
====

[%collapsible]
.Metric document
====
include::./metricset-indices.asciidoc[tag=example]
====

[%collapsible]
.Source map documents
====
Example source map document indexed in {es}:

[source,json]
----
include::../data/intake-api/generated/sourcemap/bundle.js.map[]
----
====

include::./metricset-indices.asciidoc[]