[role="xpack"]
[[feature-roles]]
== Grant users access to secured resources

IMPORTANT: {deprecation-notice-config}

You can use role-based access control to grant users access to secured
resources. The roles that you set up depend on your organization's security
requirements and the minimum privileges required to use specific features.

Typically, you need to create the following separate roles:

* <<privileges-to-publish-events,Writer role>>: To publish events collected by {beatname_uc}.
* <<privileges-to-publish-monitoring,Monitoring role>>: One for sending monitoring
information, and another for viewing it.
* <<privileges-api-key,API key role>>: To create and manage API keys.
* <<privileges-agent-central-config,Central configuration management role>>: To view
APM Agent central configurations.

{es-security-features} provides {ref}/built-in-roles.html[built-in roles] that grant a
subset of the privileges needed by APM users.
When possible, assign users the built-in roles to minimize the affect of future changes on your security strategy.
If no built-in role is available, you can assign users the privileges needed to accomplish a specific task.
In general, there are three types of privileges you'll work with:

* **Elasticsearch cluster privileges**: Manage the actions a user can perform against your cluster.
* **Elasticsearch index privileges**: Control access to the data in specific indices your cluster.
* **Kibana space privileges**: Grant users write or read access to features and apps within Kibana.

////
***********************************  ***********************************
***********************************  ***********************************
////

[[privileges-to-publish-events]]
=== Grant privileges and roles needed for writing events

++++
<titleabbrev>Create a _writer_ user</titleabbrev>
++++

IMPORTANT: {deprecation-notice-config}

APM users that publish events to {es} need privileges to write to APM data streams.

[float]
==== General writer role

To grant an APM user the required privileges for writing events to {es}:

. Create a *general writer role*, called something like `apm_writer`,
that has the following privileges:
+
[options="header"]
|====
|Type | Privilege | Purpose

|Index
|`auto_configure` on `traces-apm*`, `logs-apm*`, and `metrics-apm*` indices
|Permits auto-creation of indices and data streams

|Index
|`create_doc` on `traces-apm*`, `logs-apm*`, and `metrics-apm*` indices
|Write events into {es}
|====

. If <<configuration-rum,real user monitoring>> is enabled, additional privileges are required to read source maps.
See {kibana-ref}/rum-sourcemap-api.html[RUM source map API] for more details.
Assign these extra privileges to the *general writer role*.

. Assign the *general writer role* to users who need to publish APM data.

////
***********************************  ***********************************
***********************************  ***********************************
////

[[privileges-to-publish-monitoring]]
=== Grant privileges and roles needed for monitoring

++++
<titleabbrev>Create a _monitoring_ user</titleabbrev>
++++

IMPORTANT: {deprecation-notice-config}

{es-security-features} provides built-in users and roles for publishing and viewing monitoring data.
The privileges and roles needed to publish monitoring data
depend on the method used to collect that data.

* <<privileges-to-publish-monitoring-write>>
** <<privileges-to-publish-monitoring-internal>>
** <<privileges-to-publish-monitoring-metricbeat>>
* <<privileges-to-publish-monitoring-view>>

[float]
[[privileges-to-publish-monitoring-write]]
==== Publish monitoring data

[IMPORTANT]
====
**{ecloud} users:** This section does not apply to our
https://www.elastic.co/cloud/elasticsearch-service[hosted {ess}].
Monitoring on {ecloud} is enabled by clicking the *Enable* button in the *Monitoring* panel.
====

[float]
[[privileges-to-publish-monitoring-internal]]
===== Internal collection

If you're using <<monitoring-internal-collection,internal collection>> to
collect metrics about {beatname_uc}, {security-features} provides
the +{beat_monitoring_user}+ {ref}/built-in-users.html[built-in user] and
+{beat_monitoring_user}+ {ref}/built-in-roles.html[built-in role] to send
monitoring information. You can use the built-in user, if it's available in your
environment, or create a user who has the the built-in role assigned,
or create a user and manually assign the privileges needed to send monitoring
information.

If you use the built-in +{beat_monitoring_user}+ user,
make sure you set the password before using it.

If you don't use the +{beat_monitoring_user}+ user:

--
. Create a *monitoring role*, called something like
+{beat_default_index_prefix}_monitoring_writer+, that has the following privileges:
+
[options="header"]
|====
|Type | Privilege | Purpose

|Index
|`create_index` on `.monitoring-beats-*` indices
|Create monitoring indices in {es}

|Index
|`create_doc` on `.monitoring-beats-*` indices
|Write monitoring events into {es}
|====
+
. Assign the *monitoring role* to users who need to write monitoring data to {es}.
--

[float]
[[privileges-to-publish-monitoring-metricbeat]]
===== Metricbeat collection

NOTE: When using Metricbeat to collect metrics,
no roles or users need to be created with APM Server.
See <<monitoring-metricbeat-collection>>
for complete details on setting up Metricbeat collection.

If you're <<monitoring-metricbeat-collection,using {metricbeat}>> to collect
metrics about {beatname_uc}, {security-features} provides the `remote_monitoring_user`
{ref}/built-in-users.html[built-in user], and the `remote_monitoring_collector`
and `remote_monitoring_agent` {ref}/built-in-roles.html[built-in roles] for
collecting and sending monitoring information. You can use the built-in user, if
it's available in your environment, or create a user who has the privileges
needed to collect and send monitoring information.

If you use the built-in `remote_monitoring_user` user,
make sure you set the password before using it.

If you don't use the `remote_monitoring_user` user:

--
. Create a *monitoring user* on the production cluster who will collect and send monitoring
information. Assign the following roles to the *monitoring user*:
+
[options="header"]
|====
|Role | Purpose

|`remote_monitoring_collector`
|Collect monitoring metrics from {beatname_uc}

|`remote_monitoring_agent`
|Send monitoring data to the monitoring cluster
|====
--

[float]
[[privileges-to-publish-monitoring-view]]
==== View monitoring data

To grant users the required privileges for viewing monitoring data:

. Create a *monitoring role*, called something like
+{beat_default_index_prefix}_monitoring_viewer+, that has the following privileges:
+
[options="header"]
|====
|Type | Privilege | Purpose

| Spaces
|`Read` on Stack monitoring
|Read-only access to the Stack Monitoring feature in {kib}.

| Spaces
|`Read` on Dashboards
|Read-only access to the Dashboards feature in {kib}.
|====
+
. Assign the *monitoring role*, along with the following built-in roles, to users who
need to view monitoring data for {beatname_uc}:
+
[options="header"]
|====
|Role | Purpose

|`monitoring_user`
|Grants access to monitoring indices for {beatname_uc}
|====

////
***********************************  ***********************************
***********************************  ***********************************
////

[[privileges-api-key]]
=== Grant privileges and roles needed for API key management

++++
<titleabbrev>Create an _API key_ user</titleabbrev>
++++

IMPORTANT: {deprecation-notice-config}

You can configure <<api-key-legacy,API keys>> to authorize requests to APM Server.
To create an APM Server user with the required privileges for creating and managing API keys:

. Create an **API key role**, called something like `apm_agent_key_role`,
that has the following `cluster` level privileges:
+
[options="header"]
|====
| Privilege | Purpose

|`manage_own_api_key`
|Allow {beatname_uc} to create, retrieve, and invalidate API keys
|====

. Depending on what the **API key role** will be used for,
also assign any or all of the following `apm` application-level privileges:
+
* To **receive Agent configuration**, assign `config_agent:read`.
* To **ingest agent data**, assign `event:write`.
* To **upload sourcemaps**, assign `sourcemap:write`.

. Assign the **API key role** role to users that need to create and manage API keys.
Users with this role can only create API keys that have the same or lower access rights.

[float]
[[privileges-api-key-example]]
=== Example API key role

The following example assigns the required cluster privileges,
and all three `apm` API key application privileges to a role named `apm_agent_key_role`:

[source,kibana]
----
PUT _security/role/apm_agent_key_role <1>
{
  "cluster": [
    "manage_own_api_key" <2>
  ],
  "applications": [
    {
      "application": "apm",
      "privileges": [
        "sourcemap:write", <3>
        "event:write", <4>
        "config_agent:read" <5>
      ],
      "resources": [
        "*"
      ]
    }
  ]
}
----
<1> `apm_agent_key_role` is the name of the role we're assigning these privileges to. Any name can be used.
<2> Required cluster privileges.
<3> Required for API keys that will be used in sourcemap uploads.
<4> Required for API keys that will be used to ingest agent events.
<5> Required for API keys that will be used for Agent configuration.


////
***********************************  ***********************************
***********************************  ***********************************
////

[[privileges-agent-central-config]]
=== Grant privileges and roles needed for APM Agent central configuration

++++
<titleabbrev>Create a _central config_ user</titleabbrev>
++++

IMPORTANT: {deprecation-notice-config}

[[privileges-agent-central-config-server]]
==== APM Server central configuration management

APM Server acts as a proxy between your APM agents and the APM app.
The APM app communicates any changed settings to APM Server so that your agents only need to poll the Server
to determine which central configuration settings have changed.

To grant an APM Server user with the required privileges for managing central configuration,
assign the user the following privileges:

[options="header"]
|====
|Type | Privilege | Purpose

| Spaces
|`Read` on {beat_kib_app}
|Allow {beatname_uc} to manage central configurations via the {beat_kib_app}
|====

TIP: Looking for privileges and roles needed use central configuration from the APM app or APM app API?
See {kibana-ref}/apm-app-central-config-user.html[APM app central configuration user].

////
***********************************  ***********************************
***********************************  ***********************************
////

// [[privileges-create-api-keys]]
// === Grant privileges and roles needed to create APM Server API keys

// ++++
// <titleabbrev>Create an _APM API key_ user</titleabbrev>
// ++++

// CONTENT

////
***********************************  ***********************************
***********************************  ***********************************
////

[[more-security-roles]]
=== Additional APM users and roles

IMPORTANT: {deprecation-notice-config}

In addition to the {beatname_uc} users described in this documentation,
you'll likely need to create users for other APM tasks:

* An {kibana-ref}/apm-app-reader.html[APM reader], for {kib} users who need to view the APM app,
or create and edit visualizations that access +{beat_default_index_prefix}-*+ data.
* Various {kibana-ref}/apm-app-api-user.html[APM app API users],
for interacting with the APIs exposed by the APM app.

[float]
[[learn-more-security]]
=== Learn more about users and roles

Want to learn more about creating users and roles? See
{ref}/secure-cluster.html[Secure a cluster]. Also see:

* {ref}/security-privileges.html[Security privileges] for a description of
available privileges
* {ref}/built-in-roles.html[Built-in roles] for a description of roles that
you can assign to users
