[[jaeger-reference]]
== Configure Jaeger

++++
<titleabbrev>Jaeger</titleabbrev>
++++

IMPORTANT: {deprecation-notice-installation}
If you're using {fleet} and the Elastic APM integration, please see <<jaeger-integration>> instead.

// this content is reused in the how-to guides
// tag::jaeger-intro[]
Elastic APM integrates with https://www.jaegertracing.io/[Jaeger], an open-source, distributed tracing system.
This integration allows users with an existing Jaeger setup to switch from the default Jaeger backend,
to the Elastic Stack -- transform data with APM Server, store data in {es}, and visualize traces in the Kibana APM app.
Best of all, no instrumentation changes are needed in your application code.
// end::jaeger-intro[]

Ready to get started? See the <<jaeger,How to integrate with Jaeger>> guide.

[float]
[[jaeger-supported]]
=== Supported architecture

Jaeger architecture supports different data formats and transport protocols
that define how data can be sent to a collector. Elastic APM, as a Jaeger collector,
supports communication with *Jaeger agents* via gRPC.

* APM Server serves Jaeger gRPC over the same <<host,host and port>> as the Elastic APM agent protocol.

* The APM Server gRPC endpoint supports TLS. If `apm-server.ssl` is configured,
SSL settings will automatically be applied to APM Server's Jaeger gRPC endpoint.

* The gRPC endpoint supports probabilistic sampling.
Sampling decisions can be configured <<jaeger-configure-sampling-central,centrally>> with APM Agent central configuration, or <<jaeger-configure-sampling-local,locally>> in each Jaeger client.

See the https://www.jaegertracing.io/docs/1.22/architecture[Jaeger docs]
for more information on Jaeger architecture.

[float]
[[jaeger-caveats]]
=== Caveats

There are some limitations and differences between Elastic APM and Jaeger that you should be aware of.

*Jaeger integration limitations:*

* Because Jaeger has its own trace context header, and does not currently support W3C trace context headers,
it is not possible to mix and match the use of Elastic's APM agents and Jaeger's clients.
* Elastic APM only supports probabilistic sampling.

*Differences between APM Agents and Jaeger Clients:*

* Jaeger clients only sends trace data.
APM agents support a larger number of features, like
multiple types of metrics, and application breakdown charts.
When using Jaeger, features like this will not be available in the APM app.
* Elastic APM's {apm-overview-ref-v}/apm-data-model.html[data model] is different than Jaegers.
For Jaeger trace data to work with Elastic's data model, we rely on spans being tagged with the appropriate
https://github.com/opentracing/specification/blob/master/semantic_conventions.md[`span.kind`].
** Server Jaeger spans are mapped to Elastic APM {apm-overview-ref-v}/transactions.html[transactions].
** Client Jaeger spans are mapped to Elastic APM {apm-overview-ref-v}/transaction-spans.html[spans] -- unless the span is the root, in which case it is mapped to an Elastic APM {apm-overview-ref-v}/transactions.html[transaction].
