["appendix",role="exclude",id="redirects"]
= Deleted pages

The following pages have moved or been deleted.

// Event Types

[role="exclude",id="event-types"]
=== Event types

This page has moved. Please see {apm-overview-ref-v}/apm-data-model.html[APM data model].

// [role="exclude",id="errors"]
// === Errors

// This page has moved. Please see {apm-overview-ref-v}/errors.html[Errors].

// [role="exclude",id="transactions"]
// === Transactions

// This page has moved. Please see {apm-overview-ref-v}/transactions.html[Transactions].

// [role="exclude",id="transactions-spans"]
// === Spans

// This page has moved. Please see {apm-overview-ref-v}/transaction-spans.html[Spans].

// Error API

[role="exclude",id="error-endpoint"]
=== Error endpoint

The error endpoint has been deprecated. Instead, see <<events-api>>.

[role="exclude",id="error-schema-definition"]
=== Error schema definition

The error schema has moved. Please see <<error-schema>>.

[role="exclude",id="error-api-examples"]
=== Error API examples

The error API examples have moved. Please see <<events-api>>.

[role="exclude",id="error-payload-schema"]
=== Error payload schema

This schema has changed. Please see <<error-api>>.

[role="exclude",id="error-service-schema"]
=== Error service schema

This schema has changed. Please see <<error-api>>.

[role="exclude",id="error-system-schema"]
=== Error system schema

This schema has changed. Please see <<error-api>>.

[role="exclude",id="error-context-schema"]
=== Error context schema

This schema has changed. Please see <<error-api>>.

[role="exclude",id="error-stacktraceframe-schema"]
=== Error stacktrace frame schema

This schema has changed. Please see <<error-api>>.

[role="exclude",id="payload-with-error"]
=== Payload with error

This is no longer helpful. Please see <<error-api>>.

[role="exclude",id="payload-with-minimal-exception"]
=== Payload with minimal exception

This is no longer helpful. Please see <<error-api>>.

[role="exclude",id="payload-with-minimal-log"]
=== Payload with minimal log

This is no longer helpful. Please see <<error-api>>.

// Transaction API

[role="exclude",id="transaction-endpoint"]
=== Transaction endpoint

The transaction endpoint has been deprecated. Instead, see <<events-api>>.

[role="exclude",id="transaction-schema-definition"]
=== Transaction schema definition

The transaction schema has moved. Please see <<transaction-schema>>.

[role="exclude",id="transaction-api-examples"]
=== Transaction API examples

The transaction API examples have moved. Please see <<events-api>>.

[role="exclude",id="transaction-span-schema"]
=== Transaction span schema

This schema has changed. Please see <<span-api>>.

[role="exclude",id="transaction-payload-schema"]
=== Transaction payload schema

This schema has changed. Please see <<transaction-api>>.

[role="exclude",id="transaction-service-schema"]
=== Transaction service schema

This schema has changed. Please see <<transaction-api>>.

[role="exclude",id="transaction-system-schema"]
=== Transaction system schema

This schema has changed. Please see <<transaction-api>>.

[role="exclude",id="transaction-context-schema"]
=== Transaction context schema

This schema has changed. Please see <<transaction-api>>.

[role="exclude",id="transaction-stacktraceframe-schema"]
=== Transaction stacktrace frame schema

This schema has changed. Please see <<transaction-api>>.

[role="exclude",id="transaction-request-schema"]
=== Transaction request schema

This schema has changed. Please see <<transaction-api>>.

[role="exclude",id="transaction-user-schema"]
=== Transaction user schema

This schema has changed. Please see <<transaction-api>>.

[role="exclude",id="payload-with-transactions"]
=== Payload with transactions

This is no longer helpful. Please see <<transaction-api>>.

[role="exclude",id="payload-with-minimal-transaction"]
=== Payload with minimal transaction

This is no longer helpful. Please see <<transaction-api>>.

[role="exclude",id="payload-with-minimal-span"]
=== Payload with minimal span

This is no longer helpful. Please see <<span-api>>.

[role="exclude",id="example-intakev2-events"]
=== Example Request Body

This page has moved. Please see <<example-intake-events>>.

// V1 intake API

[role="exclude",id="request-too-large"]
=== HTTP 413: Request body too large

This error can no longer occur. Please see <<common-problems>> for an updated overview of potential issues.

[role="exclude",id="configuration-v1-api"]
=== Configuration options: v1 Intake API

Intake API v1 is no longer supported. Please see <<configuration-apm-server>> for current configuration options.

[role="exclude",id="max_unzipped_size"]
=== `max_unzipped_size`

This configuration option is no longer supported. Please see <<configuration-apm-server>> for current configuration options.

[role="exclude",id="concurrent_requests"]
=== `concurrent_requests`

This configuration option is no longer supported. Please see <<configuration-apm-server>> for current configuration options.

[role="exclude",id="metrics.enabled"]
=== `metrics.enabled`

This configuration option is no longer supported. Please see <<configuration-apm-server>> for current configuration options.

[role="exclude",id="max_request_queue_time"]
=== `max_request_queue_time`

This configuration option is no longer supported. Please see <<configuration-apm-server>> for current configuration options.

[role="exclude",id="configuration-v2-api"]
=== Configuration options: v2 Intake API

This section has moved. Please see <<configuration-apm-server>> for current configuration options.

[role="exclude",id="configuration-rum-v1"]
=== `configuration-rum-v1`

This configuration option is no longer supported. Please see <<configuration-rum>> for current configuration options.

[role="exclude",id="rate_limit_v1"]
=== `rate_limit_v1`

This configuration option is no longer supported. Please see <<configuration-rum>> for current configuration options.

[role="exclude",id="configuration-rum-v2"]
=== `configuration-rum-v2`

This section has moved. Please see <<configuration-rum>> for current configuration options.

[role="exclude",id="configuration-rum-general"]
=== Configuration options: general

This section has moved. Please see <<configuration-rum>> for current configuration options.

[role="exclude",id="use-v1-and-v2"]
=== Tuning APM Server using both v1 and v2 intake API

This section has moved. Please see <<tune-apm-server>> for how to tune APM Server.

// Dashboards

[role="exclude",id="load-dashboards-logstash"]
=== Tuning APM Server using both v1 and v2 intake API

Loading dashboards from APM Server is no longer supported. Please see the {kibana-ref}/xpack-apm.html[Kibana APM UI] documentation.

[role="exclude",id="url-option"]
=== setup.dashboards.url

Loading dashboards from APM Server is no longer supported. Please see the {kibana-ref}/xpack-apm.html[Kibana APM UI] documentation.

[role="exclude",id="file-option"]
=== setup.dashboards.file

Loading dashboards from APM Server is no longer supported. Please see the {kibana-ref}/xpack-apm.html[Kibana APM UI] documentation.

[role="exclude",id="load-kibana-dashboards"]
=== Dashboards

Loading Kibana dashboards from APM Server is no longer supported.
Please use the {kibana-ref}/xpack-apm.html[Kibana APM UI] instead.
As an alternative, a small number of dashboards and visualizations are available in the
https://github.com/elastic/apm-contrib/tree/master/kibana[apm-contrib] repository.

// [role="exclude",id="rum"]
// === Rum

// This section has moved. Please see <<configuration-rum>>.

// [role="exclude",id="apm-integration"]
// === APM integration

// This section has moved.

// [role="exclude",id="apm-integration-ilm"]
// === APM integration

// This section has moved.

// [role="exclude",id="apm-integration-pipelines"]
// === APM integration

// This section has moved.