[[upgrading-to-65]]
== Upgrade to APM Server version 6.5

++++
<titleabbrev>Upgrade to version 6.5</titleabbrev>
++++

If you're an advanced user, are implementing a custom agent,
or provide custom data to Elasticsearch,
there are some changes in APM Server version 6.5 that you should be aware of.

None of the changes in APM Server v6.5 are breaking changes,
and the APM Server is still compatible with your currently implemented agents.
However, to take advantage of new features,
it's recommended you read about the changes below and update accordingly.
If you'd like to continue using the deprecated Intake API and Elasticsearch Schema,
you can view https://www.elastic.co/guide/en/apm/server/6.4/overview.html[previous documentation].

[float]
[[upgrade-steps-65]]
=== Upgrade Steps

. Upgrade the Elastic Stack: {ref}/setup-upgrade.html[Elasticsearch],
{kibana-ref}/upgrade.html[Kibana],
and APM Server.
. Upgrade your {apm-agents-ref}/index.html[APM Agent].

Check the {apm-overview-ref-v}/agent-server-compatibility.html[agent/server compatibility matrix] for more details on which APM agents are compatible with APM Server version 6.5.

IMPORTANT: You must upgrade the APM Server before upgrading your APM Agent.
New agents do not support APM Server <6.5 and will not work if you upgrade in the wrong order.

[float]
[[intake-api-changes-65]]
=== Intake API Changes

The Intake API is what we call the internal protocol that APM agents use to talk to the APM Server.
This API has been redesigned in 6.5 to increase the memory efficiency and predictability of the APM Server and APM agents.

Notably, most of the endpoints associated with this API have been deprecated,
and replaced with a new endpoint: `intake/v2/events`.

Similarly,
the <<configuration-rum, RUM>> endpoint has been deprecated and replaced with a new endpoint: `intake/v2/rum/events`.

Details about these changes,
and the information you can send to the new endpoint,
is available in the <<events-api,Events API>> documentation.

[float]
[[metadata-api-changes-65]]
==== Metadata

Metadata is now sent to the APM Server only once per request.
APM Server will retain this information and apply it to the applicable documents when it writes to Elasticsearch.

Metadata should be sent to the new `intake/v2/events` endpoint.
See the <<metadata-api, metadata documentation>> for more information.

[float]
[[error-api-changes-65]]
==== Error

The error schema adds three new properties, and deprecates two others.

* _deprecate_ pattern of `error.id`, change format to hex encoded 64 random bits
* _deprecate_ `transaction.id`
* _add_ `transaction_id` (required, hex encoded 64 random bits)
* _add_ `parent_id` (optional, hex encoded 64 random bits)
* _add_ `trace_id` (optional, hex encoded 128 random bits)

Error events should be sent to the new `intake/v2/events` endpoint.
See the <<error-schema, error schema documentation>> for more information.

[float]
[[transaction-api-changes-65]]
==== Transaction

The transaction schema adds two new properties, and deprecates two others.

* _deprecate_ pattern of `transaction.id`, change format to hex encoded 64 random bits
* _deprecate_ spans (don't forbid them, just don't process them)
* _add_ `parent_id` (optional, hex encoded 64 random bits string)
* _add_ `trace_id` (required, hex encoded 128 random bits)

Transaction events should be sent to the new `intake/v2/events` endpoint.
See the <<transaction-schema, transaction schema documentation>> for more information.

[float]
[[span-api-changes-65]]
==== Span

The span schema adds three new properties, removes two, and changes one.

* _change_ pattern of `id` to hex encoded 64 random bits
* _deprecate_ pattern of `transaction_id`
* _deprecate_ use of `parent`
* _add_ `parent_id` (required, hex encoded 64 random bits)
* _add_ `trace_id` (required, hex encoded 128 random bits)
* _add_ `timestamp`

Span events should be sent to the new `intake/v2/events` endpoint.
See the <<span-schema, span schema documentation>> for more information.

[float]
[[healthcheck-api-changes-65]]
==== Healthcheck Endpoint

The Healthcheck endpoint, previously `/healthcheck`, has been deprecated.
The <<server-info,server information>> api has replaced it.

[float]
[[assets-api-changes-65]]
==== Assets Endpoint

The assets endpoint, `/v1/rum/sourcemaps` has been deprecated,
and replaced with the endpoint: `/assets/v1/sourcemaps`.
The data format remains unchanged.

[float]
[[metrics-api-changes-65]]
==== Metricsets Endpoint

The Metricsets endpoint, previously `/v1/metrics`,
has also integrated with the new intake endpoint at `/intake/v2/events`.
There are two changes to be aware of:

* Timestamps are now UTC based and formatted as microseconds since Unix epoch.
* The `metrics.enabled` setting has been deprecated and only applies to `v1/metrics`.
Metricsets can't be disabled in v2.

See the <<metricset-api, metricset schema>> for more information.

[float]
[[server-config-changes-65]]
=== Server Configuration Changes

There are some configuration changes that are worth mentioning.

Deprecated configuration options:

* `max_unzipped_size`
* `max_request_queue_time`

New configuration options:

* <<max_event_size,`max_event_size`>> with a default value: `307200` bytes. You may notice this default value is much smaller than the deprecated `max_unzipped_size` default value. This is because `max_unzipped_size` referred to the whole request, while `max_event_size` only refers to a single event within the request.

Notable options:

* <<read_timeout,`read_timeout`>> and <<write_timeout,`write_timeout`>> remain at 30 seconds,
but if you have a load balancer in front of the APM server you may notice connections are a little bit longer lived than they used to be.

TIP: If you are updating APM Server from version 6.3 or earlier,
you may not be using an updated `apm-server.yml` configuration file. Update your `apm-server.yml` configuration file to take advantage of new configuration options.

RUM configuration changes:

* <<event_rate.limit,`event_rate.limit`>> has replaced the deprecated `rate_limit`. In v1 of the intake API, the RUM rate limiter was bound to the number of _requests_ per second, per IP. In v2, the rate limiter has changed to be bound to the number of _events_ sent per second, per IP.


[float]
[[es-schema-changes-65]]
=== Elasticsearch Schema Changes

The Elasticsearch schema defines how APM data is stored in Elasticsearch.
There have been a number of changes to the Elasticsearch schema for 6.5.

An important change to note is the addition of the `trace` and `parent` keys,
which have been added to errors, transactions, and spans.
Both only hold a field `id`.
These new keys are essential to taking advantage of APM's new {apm-overview-ref-v}/distributed-tracing.html[distributed tracing] feature.

[float]
[[es-error-changes-65]]
==== Error

The Elasticsearch error schema adds two new keys:

* _add_ `trace.id`
* _add_ `parent.id`

View the sample Elasticsearch <<error-indices,error document>> for more information.

[float]
[[es-transaction-changes-65]]
==== Transaction

The Elasticsearch transaction schema adds two new keys:

* _add_ `trace.id`
* _add_ `parent.id`

View the sample Elasticsearch <<transaction-indices,transaction document>> for more information.

[float]
[[es-span-changes-65]]
==== Span

The Elasticsearch span schema adds three new keys, and deprecates two:

* _add_ `trace.id`
* _add_ `parent.id`
* _add_ `hex_id`
* _deprecate_ `parent` long
* _deprecate_ `id` long

View the sample Elasticsearch <<span-indices,span document>> for more information.
