pull_request_rules:
  - name: ask to resolve conflict
    conditions:
      - conflict
    actions:
        comment:
          message: |
            This pull request is now in conflicts. Could you fix it @{{author}}? 🙏
            To fixup this pull request, you can check out it locally. See documentation: https://help.github.com/articles/checking-out-pull-requests-locally/
            ```
            git fetch upstream
            git checkout -b {{head}} upstream/{{head}}
            git merge upstream/{{base}}
            git push upstream {{head}}
            ```
  - name: backport patches to 7.16 branch
    conditions:
      - merged
      - base=master
      - label=backport-7.16
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "7.16"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
  - name: backport patches to 7.15 branch
    conditions:
      - merged
      - base=master
      - label=backport-7.15
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "7.15"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
  - name: backport patches to 7.14 branch
    conditions:
      - merged
      - base=master
      - label=backport-7.14
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "7.14"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
  - name: backport patches to 7.13 branch
    conditions:
      - merged
      - base=master
      - label=backport-7.13
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "7.13"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
  - name: Automatic squash and merge with success checks and the file docker-compose.yml is modified.
    conditions:
      - check-success=apm-ci/pr-merge
      - label=automation
      - files=docker-compose.yml
    actions:
      merge:
        method: squash
        strict: smart+fasttrack
  - name: delete upstream branch with changes on docker-compose.yml after merging/closing it
    conditions:
      - or:
        - merged
        - closed
      - and:
        - label=automation
        - head~=^update-.*-version
        - files=docker-compose.yml
    actions:
      delete_head_branch:
  - name: automatic merge when CI passes for the make update-beats
    conditions:
      - check-success=apm-ci/pr-merge
      - label=automation
      - base~=^update-beats
      - files~=^(go.mod|go.sum|NOTICE.txt)
    actions:
      merge:
        method: squash
        strict: smart+fasttrack
  - name: delete upstream branch after merging changes for the make update-beats
    conditions:
      - or:
        - merged
        - closed
      - and:
        - label=automation
        - head~=^update-beats
    actions:
      delete_head_branch:
  - name: notify the backport policy
    conditions:
      - -label~=^backport
      - base=master
    actions:
      comment:
        message: |
          This pull request does not have a backport label. Could you fix it @{{author}}? 🙏
          To fixup this pull request, you need to add the backport labels for the needed
          branches, such as:
          * `backport-7.x` is the label to automatically backport to the `7.x` branch.
          * `backport-7./d` is the label to automatically backport to the `7./d` branch. `/d` is the digit

          **NOTE**: `backport-skip` has been added to this pull request.
      label:
        add:
          - backport-skip
  - name: remove backport-skip label
    conditions:
      - label~=^backport-\d
    actions:
      label:
        remove:
          - backport-skip
