pull_request_rules:
  - name: ask to resolve conflict
    conditions:
      - conflict
    actions:
        comment:
          message: |
            This pull request is now in conflicts. Could you fix it @{{author}}? 🙏
            To fixup this pull request, you can check out it locally. See documentation: https://help.github.com/articles/checking-out-pull-requests-locally/
            ```
            git fetch upstream
            git checkout -b {{head}} upstream/{{head}}
            git merge upstream/{{base}}
            git push upstream {{head}}
            ```
  - name: backport patches to 7.x branch
    conditions:
      - merged
      - base=master
      - label=v7.15.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "7.x"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
  - name: backport patches to 7.14 branch
    conditions:
      - merged
      - base=master
      - label=v7.14.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "7.14"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
  - name: backport patches to 7.13 branch
    conditions:
      - merged
      - base=master
      - label=v7.13.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "7.13"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
  - name: backport patches to 7.12 branch
    conditions:
      - merged
      - base=master
      - label=v7.12.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "7.12"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
  - name: Automatic squash and merge with success checks and the file docker-compose.yml is modified.
    conditions:
      - check-success=apm-ci/pr-merge
      - label=automation
      - files=docker-compose.yml
    actions:
      merge:
        method: squash
        strict: smart+fasttrack
  - name: delete upstream branch after merging changes on docker-compose.yml
    conditions:
      - merged
      - label=automation
      - head~=^update-stack-version
      - files=docker-compose.yml
    actions:
      delete_head_branch:
