commands_restrictions:
  backport:
    conditions:
      - or:
        - sender-permission>=write
        - sender=github-actions[bot]
queue_rules:
  - name: default
    merge_method: squash
    conditions:
      - check-success=test (macos-latest)
      - check-success=test (windows-latest)
      - check-success=system-test
      - check-success=lint
      - check-success=CLA
defaults:
  actions:
    backport:
      title: "[{{ destination_branch }}] (backport #{{ number }}) {{ title }}"
      assignees:
        - "{{ author }}"
      labels:
        - "backport"
pull_request_rules:
  - name: ask to resolve conflict
    conditions:
      - conflict
    actions:
        comment:
          message: |
            This pull request is now in conflicts. Could you fix it @{{author}}? 🙏
            To fixup this pull request, you can check out it locally. See documentation: https://help.github.com/articles/checking-out-pull-requests-locally/
            ```
            git fetch upstream
            git checkout -b {{head}} upstream/{{head}}
            git merge upstream/{{base}}
            git push upstream {{head}}
            ```
  - name: backport patches to 8.4 branch
    conditions:
      - merged
      - base=main
      - label=backport-8.4
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.4"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
  - name: backport patches to 8.3 branch
    conditions:
      - merged
      - base=main
      - label=backport-8.3
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.3"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
  - name: backport patches to 8.2 branch
    conditions:
      - merged
      - base=main
      - label=backport-8.2
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.2"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
  - name: backport patches to 8.1 branch
    conditions:
      - merged
      - base=main
      - label=backport-8.1
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.1"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
  - name: backport patches to 8.0 branch
    conditions:
      - merged
      - base=main
      - label=backport-8.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.0"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
  - name: backport patches to 7.17 branch
    conditions:
      - merged
      - base=main
      - label=backport-7.17
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "7.17"
        labels:
          - "backport"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
  - name: backport patches to 7.16 branch
    conditions:
      - merged
      - base=main
      - label=backport-7.16
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "7.16"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
  - name: backport patches to 7.15 branch
    conditions:
      - merged
      - base=main
      - label=backport-7.15
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "7.15"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
  - name: backport patches to 7.14 branch
    conditions:
      - merged
      - base=main
      - label=backport-7.14
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "7.14"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
  - name: backport patches to 7.13 branch
    conditions:
      - merged
      - base=main
      - label=backport-7.13
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "7.13"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
  - name: squash and merge updatecli PRs after CI passes
    conditions:
      - label=automation
      - head~=^updatecli
      - -conflict
    actions:
      queue:
        name: default
  - name: delete updatecli branch after merging/closing it
    conditions:
      - or:
        - merged
        - closed
      - and:
        - label=automation
        - head~=^updatecli
    actions:
      delete_head_branch:
  - name: notify the backport policy
    conditions:
      - -label~=^backport
      - base=main
    actions:
      comment:
        message: |
          This pull request does not have a backport label. Could you fix it @{{author}}? 🙏
          To fixup this pull request, you need to add the backport labels for the needed
          branches, such as:
          * `backport-7.17` is the label to automatically backport to the 7.17 branch.
          * `backport-8./d` is the label to automatically backport to the `8./d` branch. `/d` is the digit.
          * `backport-8.x` is the label to automatically backport to the `8.x` branch.

  - name: add backport-8.x for the all the PRs targeting main if no skipped or assigned already
    conditions:
      - -label~=^(backport-skip|backport-8.x)$
      - base=main
    actions:
      comment:
        message: |
          `backport-8.x` has been added to help with the transition to the new branch `8.x`.
          If you don't need it please use `backport-skip` label.
      label:
        add:
          - backport-8.x
  - name: remove backport-skip label
    conditions:
      - label~=^backport-\d
    actions:
      label:
        remove:
          - backport-skip
  - name: remove backport-8.x label if backport-skip is present
    conditions:
      - label~=^backport-skip
    actions:
      label:
        remove:
          - backport-8.x
  - name: notify the backport has not been merged yet
    conditions:
      - -merged
      - -closed
      - author=mergify[bot]
      - "#check-success>0"
      - schedule=Mon-Mon 06:00-10:00[Europe/Paris]
    actions:
      comment:
        message: |
          This pull request has not been merged yet. Could you please review and merge it @{{ assignee | join(', @') }}? 🙏
  - name: squash and merge backport PRs after CI passes
    conditions:
      - label=backport
      - author=mergify[bot]
      - -conflict
    actions:
      queue:
        name: default
  - name: backport patches to 8.5 branch
    conditions:
      - merged
      - base=main
      - label=backport-8.5
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.5"
        labels:
          - "backport"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
  - name: backport patches to 8.6 branch
    conditions:
      - merged
      - base=main
      - label=backport-8.6
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.6"
        labels:
          - "backport"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
  - name: backport patches to 8.7 branch
    conditions:
      - merged
      - base=main
      - label=backport-8.7
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.7"
        labels:
          - "backport"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
  - name: backport patches to 8.8 branch
    conditions:
      - merged
      - base=main
      - label=backport-8.8
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.8"
        labels:
          - "backport"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
  - name: backport patches to 8.9 branch
    conditions:
      - merged
      - base=main
      - label=backport-8.9
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.9"
        labels:
          - "backport"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
  - name: backport patches to 8.10 branch
    conditions:
      - merged
      - base=main
      - label=backport-8.10
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.10"
        labels:
          - "backport"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
  - name: backport patches to 8.11 branch
    conditions:
      - merged
      - base=main
      - label=backport-8.11
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.11"
        labels:
          - "backport"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
  - name: backport patches to 8.12 branch
    conditions:
      - merged
      - base=main
      - label=backport-8.12
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.12"
        labels:
          - "backport"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
  - name: backport patches to 8.13 branch
    conditions:
      - merged
      - base=main
      - label=backport-8.13
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.13"
        labels:
          - "backport"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
  - name: backport patches to 8.14 branch
    conditions:
      - merged
      - base=main
      - label=backport-8.14
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.14"
        labels:
          - "backport"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
  - name: backport patches to 8.15 branch
    conditions:
      - merged
      - base=main
      - label=backport-8.15
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.15"
        labels:
          - "backport"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
  - name: backport patches to 8.x branch
    conditions:
      - merged
      - base=main
      - label=backport-8.x
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.x"
        labels:
          - "backport"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
  - name: backport patches to 8.16 branch
    conditions:
      - merged
      - base=main
      - label=backport-8.16
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.16"
        labels:
          - "backport"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
  - name: backport patches to 8.17 branch
    conditions:
      - merged
      - base=main
      - label=backport-8.17
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.17"
        labels:
          - "backport"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
  - name: backport patches to 8.18 branch
    conditions:
      - merged
      - base=main
      - label=backport-8.18
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.18"
        labels:
          - "backport"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
<<<<<<< HEAD
=======
  - name: backport patches to 9.0 branch
    conditions:
      - merged
      - base=main
      - label=backport-9.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "9.0"
        labels:
          - "backport"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
>>>>>>> ffe8e7e3 (mergify: new way of backporting to active branches using gh action (#16621))
