---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: apm-server
  description: apm-server
  annotations:
    github.com/project-slug: elastic/apm-server
    github.com/team-slug: elastic/apm-server

spec:
  type: tool
  owner: group:apm-server
  lifecycle: production
