# Config file for `updatecli compose ...`.
# https://www.updatecli.io/docs/core/compose/
policies:
  - name: Handle ironbank bumps
    policy: ghcr.io/elastic/oblt-updatecli-policies/ironbank/templates:0.3.0@sha256:b0c841d8fb294e6b58359462afbc83070dca375ac5dd0c5216c8926872a98bb1
    values:
      - .ci/updatecli/values.d/scm.yml
      - .ci/updatecli/values.d/ironbank.yml
  - name: Update Updatecli policies
    policy: ghcr.io/updatecli/policies/autodiscovery/updatecli:0.5.0@sha256:df7fb3a9e3348a9749527edf867be1090f452f9ee0c2116aab6de39729850d53
    values:
      - .ci/updatecli/values.d/scm.yml
      - .ci/updatecli/values.d/updatecli-compose.yml
