// tag::fleet-managed[]
**Is {agent} healthy?**

In {kib} open **{fleet}** and find the host that is running the APM integration;
confirm that its status is **Healthy**.
If it isn't, check the {agent} logs to diagnose potential causes.
See {fleet-guide}/monitor-elastic-agent.html[Monitor {agent}s] to learn more.

**Is APM Server happy?**

In {kib}, open **{fleet}** and select the host that is running the APM integration.
Open the **Logs** tab and select the `elastic_agent.apm_server` dataset.
Look for any APM Server errors that could help diagnose the problem.

**Can the {apm-agent} connect to APM Server**

To determine if the {apm-agent} can connect to the APM Server, send requests to the instrumented service and look for lines
containing `[request]` in the APM Server logs.

If no requests are logged, confirm that:

. SSL isn't <<ssl-client-fails, misconfigured>>.
. The host is correct. For example, if you're using Docker, ensure a bind to the right interface (for example, set
`apm-server.host = 0.0.0.0:8200` to match any IP) and set the `SERVER_URL` setting in the {apm-agent} accordingly.

If you see requests coming through the APM Server but they are not accepted (a response code other than `202`),
see <<common-response-codes>> to narrow down the possible causes.

**Instrumentation gaps**

APM agents provide auto-instrumentation for many popular frameworks and libraries.
If the {apm-agent} is not auto-instrumenting something that you were expecting, data won't be sent to the {stack}.
Reference the relevant {apm-agents-ref}/index.html[{apm-agent} documentation] for details on what is automatically instrumented.
// end::fleet-managed[]

// tag::binary[]
If no data shows up in {es}, first check that the APM components are properly connected.

To ensure that APM Server configuration is valid and it can connect to the configured output, {es} by default,
run the following commands:

["source","sh"]
------------------------------------------------------------
apm-server test config
apm-server test output
------------------------------------------------------------

To see if the agent can connect to the APM Server, send requests to the instrumented service and look for lines
containing `[request]` in the APM Server logs.

If no requests are logged, it might be that SSL is <<ssl-client-fails, misconfigured>> or that the host is wrong.
Particularly, if you are using Docker, ensure to bind to the right interface (for example, set
`apm-server.host = 0.0.0.0:8200` to match any IP) and set the `SERVER_URL` setting in the agent accordingly.

If you see requests coming through the APM Server but they are not accepted (response code other than `202`), consider
the response code to narrow down the possible causes (see sections below).

Another reason for data not showing up is that the agent is not auto-instrumenting something you were expecting, check
the {apm-agents-ref}/index.html[agent documentation] for details on what is automatically instrumented.

APM Server currently relies on {es} to create indices that do not exist.
As a result, {es} must be configured to allow {ref}/docs-index_.html#index-creation[automatic index creation] for APM indices.
// end::binary[]
