[[release-notes-6.2]]
== APM Server version 6.2

https://github.com/elastic/apm-server/compare/6.1...6.2[View commits]

* <<release-notes-6.2.4>>
* <<release-notes-6.2.3>>
* <<release-notes-6.2.2>>
* <<release-notes-6.2.1>>
* <<release-notes-6.2.0>>


[[release-notes-6.2.4]]
=== APM Server version 6.2.4

https://github.com/elastic/apm-server/compare/v6.2.3\...v6.2.4[View commits]

No significant changes.

[[release-notes-6.2.3]]
=== APM Server version 6.2.3

https://github.com/elastic/apm-server/compare/v6.2.2\...v6.2.3[View commits]

No significant changes.

[[release-notes-6.2.2]]
=== APM Server version 6.2.2

https://github.com/elastic/apm-server/compare/v6.2.1\...v6.2.2[View commits]

No significant changes.

[[release-notes-6.2.1]]
=== APM Server version 6.2.1

https://github.com/elastic/apm-server/compare/v6.2.0\...v6.2.1[View commits]

No significant changes.

[[release-notes-6.2.0]]
=== APM Server version 6.2.0

https://github.com/elastic/apm-server/compare/v6.1.4\...v6.2.0[View commits]

[float]
==== Breaking changes
- Renaming and reverse boolean `in_app` to `library_frame` {pull}385[385].
- Renaming `app` to `service` {pull}377[377]
- Move `trace.transaction_id` to `transaction.id` {pull}345[345], {pull}347[347], {pull}371[371]
- Renaming `trace` to `span` {pull}352[352].
- Renaming and reverse boolean `exception.uncaught` to `exception.handled` {pull}434[434].
- Move process related fields to their own namespace {pull}445[445].
- Rename Kibana directories according to changed structure in beats framework. {pull}454[454]
- Change config option `max_header_bytes` to `max_header_size` {pull}492[492].
- Change config option `frontend.sourcemapping.index` to `frontend.source_mapping.index_pattern` and remove adding a '*' by default.{pull}492[492].
- Remove untested config options from config yml files {pull}496[496]

[float]
==== Bug fixes
- Updated systemd doc url {pull}354[354]
- Updated readme doc urls {pull}356[356]
- Use updated stack trace frame values for calculating error `grouping_keys` {pull}485[485]
- Fix panic when a signal is delivered before the server is instantiated {pull}580[580]

[float]
==== Added
- service.environment {pull}366[366]
- Consider exception or log message for grouping key when nothing else is available {pull}435[435]
- Add context.request.url.full {pull}436[436]
- Report more detail on max data size error {pull}442[442]
- Increase default 'MaxUnzippedSize' from 10mb to 50mb {pull}439[439]
- Add transaction.id to errors {pull}437[437]
- Support for `transaction.marks` {pull}430[430]
- Support for uploading sourcemaps {pull}302[302].
- Support for sourcemap mapping on incoming frontend requests {pull}381[381], {pull}462[462], {pull}502[502]
- Support for `transaction.span_count.dropped.total` {pull}448[448].
- Optional field `transaction.sampled` {pull}441[441]
- Add Kibana sourcefilter for `sourcemap.sourcemap` {pull}454[454]
- Increase default 'ConcurrentRequests' from 20 to 40 {pull}492[492]
- Add Config option for excluding stack trace frames from `grouping_key` calculation {pull}482[482]
- Expose expvar {pull}509[509]
- Add `process.ppid` as optional field {pull}564[564]
- Change `error.culprit` after successfully applying sourcemapping {pull}520[520]
- Make `transaction.name` optional {pull}554[554]
- Remove config files from beats. Manually add relevant config options {pull}578[578]
- Use separate index for uploaded `source maps` {pull}582[582].
- Store original values when applying source mapping or changing `library_frame` value {pull}647[647]
