[[release-notes-7.14]]
== APM Server version 7.14

https://github.com/elastic/apm-server/compare/7.13\...7.14[View commits]

* <<release-notes-7.14.0>>

[float]
[[release-notes-7.14.0]]
=== APM Server version 7.14.0

https://github.com/elastic/apm-server/compare/v7.13.4\...v7.14.0[View commits]

[float]
==== Breaking Changes
* Removed monitoring counters `apm-server.processor.stream.errors.{queue,server,closed}` {pull}5453[5453]

[float]
==== Bug fixes
* Fix panic on Fleet policy change when transaction metrics or tail-based sampling are enabled {pull}5670[5670]
* Remove multipart form temporary files left behind by source map uploads {pull}5718[5718]
* Removed service name from dataset {pull}5451[5451]
* Fixed tail-based sampling pubsub to use _seq_no correctly {pull}5126[5126]

[float]
==== Added
* Support fetching sourcemaps from fleet {pull}5410[5410]
* Add support for more input variables in fleet integration {pull}5444[5444]
* Add debug logging of OpenTelemetry payloads {pull}5474[5474]
* Add support for OpenTelemetry labels describing mobile connectivity {pull}5436[5436]
* Introduce `apm-server.auth.*` config {pull}5457[5457]
* Add support for adjusting OTel event timestamps using `telemetry.sdk.elastic_export_timestamp` {pull}5433[5433]
* Add units to metric fields {pull}5395[5395]
* Add support for histograms to metrics intake {pull}5360[5360]
* Display apm-server url in fleet ui's apm-server integration {pull}4895[4895]
* Translate otel messaging.* semantic conventions to ECS {pull}5334[5334]
* Tail-sampling processor now resumes subscription from previous position after restart {pull}5350[5350]
* Add support for dynamic histogram metrics {pull}5239[5239]
* Support setting agent configuration from apm-server.yml {pull}5177[5177]
* Add metric_type and unit to field metadata of system metrics {pull}5230[5230]
* Under fleet, report which agent configs have been applied {pull}5481[5481]
* Server sends its raw config to kibana when running on ECE/ESS {pull}5424[5424]

[float]
==== Deprecated
* Make `destination.service.name` and `destination.service.type` fields optional and deprecated {pull}5468[5468]
* `apm-server.secret_token` is now `apm-server.auth.secret_token` {pull}5457[5457]
* `apm-server.api_key` is now `apm-server.auth.api_key` {pull}5457[5457]
