[[release-notes-7.17]]
== APM version 7.17

https://github.com/elastic/apm-server/compare/7.16\...7.17[View commits]

* <<release-notes-7.17.8>>
* <<release-notes-7.17.7>>
* <<release-notes-7.17.6>>
* <<release-notes-7.17.5>>
* <<release-notes-7.17.4>>
* <<release-notes-7.17.3>>
* <<release-notes-7.17.2>>
* <<release-notes-7.17.1>>
* <<release-notes-7.17.0>>

[float]
[[release-notes-7.17.8]]
=== APM version 7.17.8

https://github.com/elastic/apm-server/compare/v7.17.7\...v7.17.8[View commits]

No significant changes.

[float]
[[release-notes-7.17.7]]
=== APM version 7.17.7

https://github.com/elastic/apm-server/compare/v7.17.6\...v7.17.7[View commits]

[float]
==== Breaking changes

This APM release updates Go to version 1.18.5.
The https://tip.golang.org/doc/go1.18#sha1[Go release notes] for this version note the following change to TLS:

****
**Rejecting SHA-1 certificates**

`crypto/x509`` will now reject certificates signed with the SHA-1 hash function. This doesn't apply to self-signed root certificates. Practical attacks against SHA-1 https://shattered.io/[have been demonstrated since 2017] and publicly trusted Certificate Authorities have not issued SHA-1 certificates since 2015.

This can be temporarily reverted by setting the `GODEBUG=x509sha1=1` environment variable. This option will be removed in a future release.
****

[float]
[[release-notes-7.17.6]]
=== APM version 7.17.6

https://github.com/elastic/apm-server/compare/v7.17.5\...v7.17.6[View commits]

[float]
==== Bug fixes
- Fix a bug where an event's transaction_id is ignored if no transaction object is set {pull}8820[8820]

[float]
[[release-notes-7.17.5]]
=== APM version 7.17.5

https://github.com/elastic/apm-server/compare/v7.17.4\...v7.17.5[View commits]

No significant changes.

[float]
[[release-notes-7.17.4]]
=== APM version 7.17.4

https://github.com/elastic/apm-server/compare/v7.17.3\...v7.17.4[View commits]

No significant changes.

[float]
[[release-notes-7.17.3]]
=== APM version 7.17.3

https://github.com/elastic/apm-server/compare/v7.17.2\...v7.17.3[View commits]

[float]
==== Bug fixes
- APM Server will no longer set `_doc_count` fields when used with an old (<7.11.0) version of Elasticsearch. This metadata field was added in Elasticsearch 7.12.0; setting it in earlier versions causes problems on upgrade. {pull}7704[7704]

[float]
[[release-notes-7.17.2]]
=== APM version 7.17.2

https://github.com/elastic/apm-server/compare/v7.17.1\...v7.17.2[View commits]

[float]
==== Bug fixes
- modelindexer: Fix indexing performance regression due to locking bug {pull}7649[7649]

[float]
[[release-notes-7.17.1]]
=== APM version 7.17.1

https://github.com/elastic/apm-server/compare/v7.17.0\...v7.17.1[View commits]

[float]
==== Bug fixes
- Fix infinite loop in tail-based sampling subscriber causing high CPU and repeated Elasticsearch searches {pull}7211[7211]
- Fix panic when processing OpenTelemetry histogram metrics without bounds {pull}7316[7316]
- Fix waiting for events to be flushed when shutting down APM Server {pull}7352[7352]

[float]
[[release-notes-7.17.0]]
=== APM version 7.17.0

https://github.com/elastic/apm-server/compare/v7.16.3\...v7.17.0[View commits]

[float]
==== Changes
- Change Docker base image from CentOS 7 to Ubuntu 20.04 {pull}7101[7101]
