[[release-notes-8.1]]
== APM version 8.1

https://github.com/elastic/apm-server/compare/8.0\...8.1[View commits]

* <<release-notes-8.1.3>>
* <<release-notes-8.1.2>>
* <<release-notes-8.1.1>>
* <<release-notes-8.1.0>>

[float]
[[release-notes-8.1.3]]
=== APM version 8.1.3

https://github.com/elastic/apm-server/compare/v8.1.2\...v8.1.3[View commits]

This release includes an important APM Server bug fix.
Users running APM Server version 8.0.0 and above should upgrade immediately.

[float]
==== Bug fixes
- Fix a bug that caused the APM Server to run out of memory when it receives events from a high number of APM agents {pull}7809[7809]

[float]
[[release-notes-8.1.2]]
=== APM version 8.1.2

https://github.com/elastic/apm-server/compare/8.1.1\...8.1.2[View commits]

[float]
==== Bug fixes
- When gzip compressing Elasticsearch bulk requests, set the end of stream marker {pull}7624[7624]
- Fix setting a timestamp on RUM data when capturing personal data is disabled {pull}7567[7567]
- modelindexer: Fix indexing performance regression due to locking bug {pull}7649[7649]

[float]
[[release-notes-8.1.1]]
=== APM version 8.1.1

https://github.com/elastic/apm-server/compare/8.1.0\...8.1.1[View commits]

[float]
==== Bug fixes
- Fix missing stack monitoring metrics {pull}7428[7428]


[float]
[[release-notes-8.1.0]]
=== APM version 8.1.0

https://github.com/elastic/apm-server/compare/8.0.1\...8.1.0[View commits]

[float]
==== Added
- Tail-based sampling is now generally available
- Added several dimensions to the aggregated transaction metrics {pull}7033[7033]

[float]
==== Bug fixes
- Fix infinite loop in tail-based sampling subscriber causing high CPU and repeated Elasticsearch searches {pull}7211[7211]
