[[release-notes-8.10]]
== APM version 8.10

https://github.com/elastic/apm-server/compare/8.9\...8.10[View commits]

* <<release-notes-8.10.0>>

[float]
[[release-notes-8.10.0]]
=== APM version 8.10.0

[float]
==== Breaking Changes
- Aggregated metrics now consider global labels to be part of a service's identity, and high cardinality global labels may cause services to be obscured {pull}11386[11386]
- Event protobuf encoding for tail-based sampling changed (to a more efficient encoding) for event timestamp and duration {pull}11386[11386]

[float]
==== Deprecations

[float]
==== Bug fixes
- Add back handling of `queue.*` config for libbeat outputs, such as logstash and kafka {pull}11534[11534]

[float]
==== Intake API Changes
- `null` is no longer an acceptable value for `context.http.request.headers` and `context.http.response.headers` {pull}11386[11386]

[float]
==== Added
- Add a self-instrumentation transaction to the source map periodic refresh action. {pull}11116[11116]
- Add a self-instrumentation transaction to the agent config periodic refresh action. {pull}11129[11129]
- Stop dropping metadata fields from span documents. {pull}11089[11089]
- Add permissions to reroute events in the integration package. {pull}11168[11168]

[float]
==== Aggregation changes and improvements
- Replace aggregation with LSM-based aggregator which has a lower memory footprint {pull}11117[11117]
- Add `service.language.name` to service destination metrics {pull}11117[11117]
- Modify per-service transaction groups limit to consider more than service.name; Add per-service service destination groups limit and per-service service transaction groups limit {pull}11117[11117]
- All aggregations share the MaxServices limit {pull}11117[11117]
