[[release-notes-8.11]]
== APM version 8.11

https://github.com/elastic/apm-server/compare/8.10\...8.11[View commits]

* <<release-notes-8.11.4>>
* <<release-notes-8.11.3>>
* <<release-notes-8.11.2>>
* <<release-notes-8.11.1>>
* <<release-notes-8.11.0>>

[float]
[[release-notes-8.11.4]]
=== APM version 8.11.4

https://github.com/elastic/apm-server/compare/v8.11.3\...v8.11.4[View commits]

[float]
==== Bug fixes
- Fix source maps not being applied when an event contains both a span and an error {pull}12221[12221]

[float]
[[release-notes-8.11.3]]
=== APM version 8.11.3

https://github.com/elastic/apm-server/compare/v8.11.2\...v8.11.3[View commits]

No significant changes.

[float]
[[release-notes-8.11.2]]
=== APM version 8.11.2

https://github.com/elastic/apm-server/compare/v8.11.1\...v8.11.2[View commits]

No significant changes.

[float]
[[release-notes-8.11.1]]
=== APM version 8.11.1

https://github.com/elastic/apm-server/compare/v8.11.0\...v8.11.1[View commits]

No significant changes.

[float]
[[release-notes-8.11.0]]
=== APM version 8.11.0

[float]
==== Breaking Changes
- The `ecs.version` field has been removed from APM data streams {pull}11632[11632]

[float]
==== Bug fixes
- Add back gzip support for grpc otlp endpoint {pull}11434[11434]
- Correctly mark jvm.memory.non_heap.pool.* and jvm.fd.* metrics as internal {pull}11303[11303]
- Fix tail-based sampling discarding low throughput and low sample rate traces {pull}11642[11642]
- Add memory based autoscaling for service destination aggregation groups {pull}11739[11739]

[float]
==== Added
- Support and define DLM data retention period in the apmpackage {pull}11539[11539]
- Expose new metrics into the local batch processor {pull}11582[11582]
- Add geoip processing to app_logs ingest pipeline on `client.ip` {pull}11699[11699]
