[[release-notes-8.12]]
== APM version 8.12

* <<release-notes-8.12.0>>

[float]
[[release-notes-8.12.0]]
=== APM version 8.12.0

https://github.com/elastic/apm-server/compare/v8.11.4\...v8.12.0[View commits]

[float]
==== Breaking Changes
- The unsupported apm_data_stream_migration ingest pipeline has been removed {pull}12102[12102].
- "publish_ready" is always false in the "GET /" response until events are received by apm-server {pull}12150[12150]
- A bug has been introduced, so that `traces-apm@custom` ingest pipeline is now additionally applied to data streams `traces-apm.sampled-*` and `traces-apm.rum-*` and applied twice for `traces-apm-*`. See more details and information around a fix in the Known Issues section.

[float]
==== Bug fixes
- Switch built-in ILM rollover policies from max_size to max_primary_shard_size {pull}11729[11729].
- Handle empty request bodies gracefully {pull}12242[12242].
- Wrap processor errors to provide more details {pull}12242[12242].
- Require only one of exception.{type,message} for log exceptions {pull}12242[12242].

[float]
==== Added
- Update container base image to Ubuntu 22.04 {pull}11778[11778]
- Add support for returning partial success response in OTLP input {pull}11883[11883]
- Setting event timestamp from OTel observed timestamp when needed {pull}11935[11935]
- Field mappings have been added for various formerly unindexed fields {pull}12102[12102]
- We now assert that index templates are installed by attempting to create data streams {pull}12150[12150]
