[[release-notes-8.12]]
== APM version 8.12

* <<release-notes-8.12.2>>
* <<release-notes-8.12.1>>
* <<release-notes-8.12.0>>

[float]
[[release-notes-8.12.2]]
=== APM version 8.12.2

https://github.com/elastic/apm-server/compare/v8.12.1\...v8.12.2[View commits]

[float]
==== Bug fixes
- Tail-based sampling: do not stop sampling processor when failing to delete trace events {pull}12509[12509]
- Define value for all constant_keyword fields in apmpackage to fix integration upgrade issues in rare cases {pull}12219[12219]

[float]
[[release-notes-8.12.1]]
=== APM version 8.12.1

https://github.com/elastic/apm-server/compare/v8.12.0\...v8.12.1[View commits]

[float]
==== Bug fixes
- Tail-based sampling: Fix missing entry TTL in badger.ErrTxnTooBig handling {pull}12453[12453]
- Tail-based sampling: Compute entry size before writing and flush to avoid losing events silently due to storage limit {pull}12120[12120]
- APM instrumentation: Use UpDownCounter for docsActive and availableBulkIndexer {pull}12179[12179]
- Remove field preview in error reason returned by Elasticsearch from logs. https://discuss.elastic.co/t/apm-server-8-12-1-security-update-esa-2024-03/352688[Please see our security advisory for more details]. {pull}12179[12179]

[float]
==== Added
- Disable default instrumentation metrics sending to batch processor by removing local exporter {pull}12228[12228]
- Log a single consolidated line per unique error instead of per each failed document {pull}12179[12179]

[float]
[[release-notes-8.12.0]]
=== APM version 8.12.0

https://github.com/elastic/apm-server/compare/v8.11.4\...v8.12.0[View commits]

[float]
==== Breaking Changes
- The unsupported apm_data_stream_migration ingest pipeline has been removed {pull}12102[12102].
- "publish_ready" is always false in the "GET /" response until events are received by apm-server {pull}12150[12150]
- Reverts a breaking change that ignored the beat name. This is visible in Stack Monitoring {pull}12176[12176]
- A bug has been introduced, so that `traces-apm@custom` ingest pipeline is now additionally applied to data streams `traces-apm.sampled-*` and `traces-apm.rum-*` and applied twice for `traces-apm-*`. See more details and information around a fix in the Known Issues section.

[float]
==== Bug fixes
- Switch built-in ILM rollover policies from max_size to max_primary_shard_size {pull}11729[11729].
- Handle empty request bodies gracefully {pull}12242[12242].
- Wrap processor errors to provide more details {pull}12242[12242].
- Require only one of exception.{type,message} for log exceptions {pull}12242[12242].

[float]
==== Added
- Update container base image to Ubuntu 22.04 {pull}11778[11778]
- Add support for returning partial success response in OTLP input {pull}11883[11883]
- Setting event timestamp from OTel observed timestamp when needed {pull}11935[11935]
- Field mappings have been added for various formerly unindexed fields {pull}12102[12102]
- We now assert that index templates are installed by attempting to create data streams {pull}12150[12150]
