[[apm-release-notes-8.13]]
== APM version 8.13

* <<apm-release-notes-8.13.1>>
* <<apm-release-notes-8.13.0>>

[float]
[[apm-release-notes-8.13.1]]
=== APM version 8.13.1

https://github.com/elastic/apm-server/compare/v8.13.0\...v8.13.1[View commits]

No significant changes.

[float]
[[apm-release-notes-8.13.0]]
=== APM version 8.13.0

https://github.com/elastic/apm-server/compare/v8.12.2\...v8.13.0[View commits]

[float]
==== Added
- map OTel's `span.Status: Unset` to `event.outcome: success` instead of `event.outcome: unknown` {pull}12199[12199]
- Add support for Otel code.stacktrace {pull}12096[12096]
- `http.request.body.bytes` now reports the bytes read from request body even if Content-Length is -1 {pull}12451[12451]
- Use `messaging.system` and `messaging.operation` to detect OTel messaging span for transactions {pull}12506[12506]
- Add support for OTel data stream routing by parsing `data_stream.dataset` and `data_stream.namespace` from: (from lowest to highest precedence) resource attributes, instrumentation scope attributes, and signal-level attributes. This is a breaking change only for users relying on the existing `data_stream` attributes being stored as labels. {pull}12578[12578]
- Map OTel transaction `elastic.profiler_stack_trace_ids` attribute {pull}12493[12493]
- Reduce go-docappender error logging verbosity. Groups all errors by groups and reports a new "document" field {pull}12604[12604]
