[[apm-release-notes-8.15]]
== APM version 8.15

* <<apm-release-notes-8.15.1>>
* <<apm-release-notes-8.15.0>>

[float]
[[apm-release-notes-8.15.1]]
=== APM version 8.15.1

https://github.com/elastic/apm-server/compare/v8.15.0\...v8.15.1[View commits]

[float]
==== Bug fixes

- Fix memory limit fallback check bytes to GB conversion {pull}13838[13838]

[float]
[[apm-release-notes-8.15.0]]
=== APM version 8.15.0

https://github.com/elastic/apm-server/compare/v8.14.3\...v8.15.0[View commits]

[float]
==== Bug fixes

- Avoid data race due to reuse of `bytes.Buffer` in ES bulk requests {pull}13155[13155]
- APM Server now relies on the Elasticsearch apm-data plugin's index templates, which reverts some unsafe uses of `flattened` field types {pull}12066[12066]
- Add `error.id` to jaeger errors {pull}13196[13196]
- Process `host.ip` resource attribute for OTel {pull}13614[13614]
- Fix a bug where indexed OpenTelemetry events and their aggregated metrics may contain incorrect label values from other events when the affected OpenTelemetry event has resource attribute values that are slices. This bug may also cause a panic with a message like "panic: runtime error: slice bounds out of range [-4:]" from apm-aggregation library. {pull}13822[13822]

[float]
==== Breaking Changes

[float]
==== Deprecations

[float]
==== Intake API Changes

[float]
==== Added

- Add `elasticsearch.flushed.uncompressed.bytes` metric {pull}13155[13155]
- APM Server now relies on the Elasticsearch apm-data plugin's index templates, removing the requirement to install the APM integration package {pull}12066[12066]
- Upgraded bundled APM Java agent attacher CLI to version 1.50.0 {pull}13326[13326]
- Enable Kibana curated UIs to work with hostmetrics from OpenTelemetry's https://pkg.go.dev/go.opentelemetry.io/collector/receiver/hostmetricsreceiver[hostmetricsreceiver] {pull}13196[13196]
- Add require data stream to bulk index requests {pull}13398[13398]
- Support self-instrumentation when in managed mode by getting tracing configs via reloader {pull}13514[13514] {pull}13653[13653] {pull}13691[13691] {pull}13790[13790]
- Add mapping for OpenTelemetry attribute `messaging.destination.name` to derive `service.target` correctly {pull}13472[13472]
- APM Server now automatically retries document-level 429s from Elasticsearch to avoid dropping data. `output.elasticsearch.max_retries` now controls both request-level and document-level retries, and defaults to `3`. {pull}13620[13620]
