[[apm-release-notes-8.15]]
== APM version 8.15

* <<apm-release-notes-8.15.4>>
* <<apm-release-notes-8.15.3>>
* <<apm-release-notes-8.15.2>>
* <<apm-release-notes-8.15.1>>
* <<apm-release-notes-8.15.0>>

[float]
[[apm-release-notes-8.15.4]]
=== APM version 8.15.4

https://github.com/elastic/apm-server/compare/v8.15.3\...v8.15.4[View commits]

[float]
==== Bug fixes

- Rollover for all APM data streams is now executing correctly in Elasticsearch 8.15.4, fixing a https://www.elastic.co/guide/en/observability/current/apm-known-issues.html#_upgrading_to_v8_15_x_may_cause_ingestion_to_fail[known issue] present in 8.15.0, 8.15.1, 8.15.2 and 8.15.3.

[float]
[[apm-release-notes-8.15.3]]
=== APM version 8.15.3

https://github.com/elastic/apm-server/compare/v8.15.2\...v8.15.3[View commits]

[float]
==== Bug fixes

- Fix a panic in OTLP label setting when receiving on non-compliant attribute array values {pull}13950[13950]

[float]
==== Added

- Map OpenTelemetry instrumentation scope to `Service.Framework.*` for all signal types. {pull}13903[13903]

[float]
[[apm-release-notes-8.15.2]]
=== APM version 8.15.2

https://github.com/elastic/apm-server/compare/v8.15.1\...v8.15.2[View commits]

[float]
==== Bug fixes

- Fix broken APM Agents configuration cache when there are more than 100 agent config entries {pull}13958[13958]

[float]
[[apm-release-notes-8.15.1]]
=== APM version 8.15.1

https://github.com/elastic/apm-server/compare/v8.15.0\...v8.15.1[View commits]

[float]
==== Bug fixes

- Fix fallback memory limit check conversion from Bytes to Gigabytes {pull}13838[13838]
- Fix Elasticsearch apm-data plugin to fallback to ILM policy for data streams using default APM integration and not explicitly migrated to data stream lifecycle. More details are available in the https://www.elastic.co/guide/en/observability/current/apm-known-issues.html[APM known issues page] {pull}13918[13918]
- Remove from logs the error reason returned by Elasticsearch for `x_content_parse_exception` error {pull}13853[13853]
- Fix ingestion failure when `ip` resource attribute has value `0.0.0.0` in OpenTelemetry events from Jaeger {pull}13852[13852]
- Fix possible nil pointer dereference when parsing stacktraces in OpenTelemetry events {pull}13852[13852]
- Fix missing tracking in instrumentation metrics for certain request-level status codes from Elasticsearch bulk responses {pull}13853[13853]

[float]
==== Added

- Support OpenTelemetry Java agent inferred span links {pull}13852[13852]

[float]
[[apm-release-notes-8.15.0]]
=== APM version 8.15.0

https://github.com/elastic/apm-server/compare/v8.14.3\...v8.15.0[View commits]

[float]
==== Bug fixes

- Avoid data race due to reuse of `bytes.Buffer` in ES bulk requests {pull}13155[13155]
- APM Server now relies on the Elasticsearch apm-data plugin's index templates, which reverts some unsafe uses of `flattened` field types {pull}12066[12066]
- Add `error.id` to jaeger errors {pull}13196[13196]
- Process `host.ip` resource attribute for OTel {pull}13614[13614]
- Fix a bug where indexed OpenTelemetry events and their aggregated metrics may contain incorrect label values from other events when the affected OpenTelemetry event has resource attribute values that are slices. This bug may also cause a panic with a message like "panic: runtime error: slice bounds out of range [-4:]" from apm-aggregation library. {pull}13822[13822]

[float]
==== Breaking Changes

- Integration custom ingest pipelines `logs-apm.integration@custom`, `metrics-apm.integration@custom`, and `traces-apm.integration@custom` are no longer supported. Any existing pipelines above will need to be moved to the more fine-grained `\*-apm*@custom` ingest pipelines {pull}12066[12066]

[float]
==== Added

- Add `elasticsearch.flushed.uncompressed.bytes` metric {pull}13155[13155]
- APM Server now relies on the Elasticsearch apm-data plugin's index templates, removing the requirement to install the APM integration package {pull}12066[12066]
- Upgraded bundled APM Java agent attacher CLI to version 1.50.0 {pull}13326[13326]
- Enable Kibana curated UIs to work with hostmetrics from OpenTelemetry's https://pkg.go.dev/go.opentelemetry.io/collector/receiver/hostmetricsreceiver[hostmetricsreceiver] {pull}13196[13196]
- Add require data stream to bulk index requests {pull}13398[13398]
- Support self-instrumentation when in managed mode by getting tracing configs via reloader {pull}13514[13514] {pull}13653[13653] {pull}13691[13691] {pull}13790[13790]
- Add mapping for OpenTelemetry attribute `messaging.destination.name` to derive `service.target` correctly {pull}13472[13472]
- APM Server now automatically retries document-level 429s from Elasticsearch to avoid dropping data. `output.elasticsearch.max_retries` now controls both request-level and document-level retries, and defaults to `3`. {pull}13620[13620]
