[[apm-release-notes-8.16]]
== APM version 8.16

* <<apm-release-notes-8.16.5>>
* <<apm-release-notes-8.16.4>>
* <<apm-release-notes-8.16.3>>
* <<apm-release-notes-8.16.2>>
* <<apm-release-notes-8.16.1>>
* <<apm-release-notes-8.16.0>>

[float]
[[apm-release-notes-8.16.5]]
=== APM version 8.16.5

https://github.com/elastic/apm-server/compare/v8.16.4\...v8.16.5[View commits]

[float]
==== Bug fixes

[float]
==== Breaking Changes

[float]
==== Deprecations

[float]
==== Intake API Changes

[float]
==== Added

[float]
[[apm-release-notes-8.16.4]]
=== APM version 8.16.4

https://github.com/elastic/apm-server/compare/v8.16.3\...v8.16.4[View commits]

[float]
==== Bug fixes

- Fix unmapped or dropped APM Server tail sampling monitoring metrics in APM Server self-monitoring, Stack monitoring, Metricbeat, and Elastic Agent integration {issue}14247[14247]

[float]
==== Breaking Changes

[float]
==== Deprecations

[float]
==== Intake API Changes

[float]
==== Added

[float]
[[apm-release-notes-8.16.3]]
=== APM version 8.16.3

https://github.com/elastic/apm-server/compare/v8.16.2\...v8.16.3[View commits]

[float]
==== Bug fixes

- Install APM Server in Program Files directory on Windows {pull}14905[14905]
- Fix self instrumentation events inconsistency when dealing with request timeout {pull}15123[15123]
- Drop and recreate tail-based sampling badger db after exceeding storage limit for configured TTL time {pull}15106[15106]

[float]
==== Breaking Changes

[float]
==== Deprecations

[float]
==== Intake API Changes

[float]
==== Added

- Add sampling.tail.discard_on_write_failure config (default=false) to opt in to data loss when tail-based sampling storage limit is reached {pull}15159[15159]

[float]
[[apm-release-notes-8.16.2]]
=== APM version 8.16.2

https://github.com/elastic/apm-server/compare/v8.16.1\...v8.16.2[View commits]

[float]
==== Bug fixes

- Surface config parsing error under EA managed mode by logging and marking EA input unit as failed {pull}14574[14574]
- Remove unnecessary hot reload under EA managed mode when apm tracing config is nil {pull}14865[14865]

[float]
==== Breaking Changes

[float]
==== Deprecations

[float]
==== Intake API Changes

[float]
==== Added

- In this release we've introduced an image based on the hardened https://wolfi.dev/[Wolfi] image to provide additional security to our self-managed customers, and improve our supply chain security posture.

[float]
[[apm-release-notes-8.16.1]]
=== APM version 8.16.1

https://github.com/elastic/apm-server/compare/v8.16.0\...v8.16.1[View commits]

[float]
==== Bug fixes

[float]
==== Breaking Changes

[float]
==== Deprecations

[float]
==== Intake API Changes

[float]
==== Added

[float]
[[apm-release-notes-8.16.0]]
=== APM version 8.16.0

https://github.com/elastic/apm-server/compare/v8.15.2\...v8.16.0[View commits]

[float]
==== Bug fixes

- Track all bulk request response status codes {pull}13574[13574]
- Fix a concurrent map write panic in monitoring middleware {pull}14335[14335]
- Apply shutdown timeout to http server {pull}14339[14339]
- Tail-based sampling: Fix rare gc thread failure after EA hot reload causing storage not reclaimed and stuck with "storage limit reached" {pull}14340[14340]

[float]
==== Breaking Changes

[float]
==== Deprecations
- Support for Jaeger is now deprecated, and will be removed in a future release {pull}13809[13809]

[float]
==== Intake API Changes

[float]
==== Added

- APM Server will no longer retry an HTTP request that returned 502s, 503s, 504s. It will only retry 429s. {pull}13523[13523]
- APM Server now supports emitting distributed tracing for its own operation when running under Elastic Agent, and adds support for configuring a sampling rate {pull}14231[14231]
