[[apm-release-notes-8.17]]
== APM version 8.17

* <<apm-release-notes-8.17.7>>
* <<apm-release-notes-8.17.6>>
* <<apm-release-notes-8.17.5>>
* <<apm-release-notes-8.17.4>>
* <<apm-release-notes-8.17.3>>
* <<apm-release-notes-8.17.2>>
* <<apm-release-notes-8.17.1>>
* <<apm-release-notes-8.17.0>>

[float]
[[apm-release-notes-8.17.7]]
=== APM version 8.17.7

https://github.com/elastic/apm-server/compare/v8.17.6\...v8.17.7[View commits]

[float]
==== Bug fixes

[float]
==== Breaking Changes

[float]
==== Deprecations

[float]
==== Intake API Changes

[float]
==== Added

[float]
[[apm-release-notes-8.17.6]]
=== APM version 8.17.6

https://github.com/elastic/apm-server/compare/v8.17.5\...v8.17.6[View commits]

[float]
==== Bug fixes

- Tail-based sampling: ignore subscriber position read error and proceed as if file does not exist to avoid crash looping {pull}16736[16736]

[float]
==== Breaking Changes

[float]
==== Deprecations

[float]
==== Intake API Changes

[float]
==== Added

[float]
[[apm-release-notes-8.17.5]]
=== APM version 8.17.5

https://github.com/elastic/apm-server/compare/v8.17.4\...v8.17.5[View commits]

[float]
==== Bug fixes

- Tail-based sampling: Fix an issue with the "drop and recreate Badger DB on storage limit exceeded" mitigation introduced in 8.17.1 and 8.16.3. Previously, a bug in this mitigation caused the tail sampling storage size to remain between 90% and 100% of the configured limit indefinitely without triggering the intended mitigation after TTL time. {pull}16385[16385]

[float]
==== Breaking Changes

[float]
==== Deprecations

[float]
==== Intake API Changes

[float]
==== Added

[float]
[[apm-release-notes-8.17.4]]
=== APM version 8.17.4

https://github.com/elastic/apm-server/compare/v8.17.3\...v8.17.4[View commits]

[float]
==== Bug fixes

[float]
==== Breaking Changes

[float]
==== Deprecations

[float]
==== Intake API Changes

[float]
==== Added

[float]
[[apm-release-notes-8.17.3]]
=== APM version 8.17.3

https://github.com/elastic/apm-server/compare/v8.17.2\...v8.17.3[View commits]

[float]
==== Bug fixes

[float]
==== Breaking Changes

[float]
==== Deprecations

[float]
==== Intake API Changes

[float]
==== Added

[float]
[[apm-release-notes-8.17.2]]
=== APM version 8.17.2

https://github.com/elastic/apm-server/compare/v8.17.1\...v8.17.2[View commits]

[float]
==== Bug fixes

- Fix unmapped or dropped APM Server tail sampling monitoring metrics in APM Server self-monitoring, Stack monitoring, Metricbeat, and Elastic Agent integration {issue}14247[14247]

[float]
==== Breaking Changes

[float]
==== Deprecations

[float]
==== Intake API Changes

[float]
==== Added

[float]
[[apm-release-notes-8.17.1]]
=== APM version 8.17.1

https://github.com/elastic/apm-server/compare/v8.17.0\...v8.17.1[View commits]

[float]
==== Bug fixes

- Install APM Server in Program Files directory on Windows {pull}14905[14905]
- Fix self instrumentation events inconsistency when dealing with request timeout {pull}15123[15123]
- Drop and recreate tail-based sampling badger db after exceeding storage limit for configured TTL time {pull}15106[15106]

[float]
==== Breaking Changes

[float]
==== Deprecations

[float]
==== Intake API Changes

[float]
==== Added

- Add sampling.tail.discard_on_write_failure config (default=false) to opt in to data loss when tail-based sampling storage limit is reached {pull}15159[15159]

[float]
[[apm-release-notes-8.17.0]]
=== APM version 8.17.0

https://github.com/elastic/apm-server/compare/v8.16.0\...v8.17.0[View commits]

[float]
==== Bug fixes

- Clear scroll after completing scroll requests {pull}14551[14551]
- Surface config parsing error under EA managed mode by logging and marking EA input unit as failed {pull}14574[14574]
- Remove unnecessary hot reload under EA managed mode when apm tracing config is nil {pull}14865[14865]
- The mappings are updated to disable date_detection for all APM data streams.
  The change is applied through https://github.com/elastic/elasticsearch/pull/116995[elasticsearch#116995]

[float]
==== Breaking Changes

[float]
==== Deprecations

[float]
==== Intake API Changes

[float]
==== Added

- The default data lifecycle management mechanism is getting reverted from Data Stream Lifecycle (DSL) to Index Lifecycle Management (ILM), as originally used prior to the introduction of the APM data plugin in release 8.15.0.
  No action is required from users for this change.
  However, any custom DSL settings will not be preserved during the migration.
  The change is applied through https://github.com/elastic/elasticsearch/pull/115687[elasticsearch#115687]