[[apm-release-notes-8.17]]
== APM version 8.17
* <<apm-release-notes-8.17.0>>

[float]
[[apm-release-notes-8.17.0]]
=== APM version 8.17.0

https://github.com/elastic/apm-server/compare/v8.16.0\...v8.17.0[View commits]

[float]
==== Bug fixes

- Clear scroll after completing scroll requests {pull}14551[14551]
- Surface config parsing error under EA managed mode by logging and marking EA input unit as failed {pull}14574[14574]
- Remove unnecessary hot reload under EA managed mode when apm tracing config is nil {pull}14865[14865]
- The mappings are updated to disable date_detection for all APM data streams.
  The change is applied through https://github.com/elastic/elasticsearch/pull/116995[elasticsearch#116995]

[float]
==== Breaking Changes

[float]
==== Deprecations

[float]
==== Intake API Changes

[float]
==== Added

- The default data lifecycle management mechanism is getting reverted from Data Stream Lifecycle (DSL) to Index Lifecycle Management (ILM), as originally used prior to the introduction of the APM data plugin in release 8.15.0.
  No action is required from users for this change.
  However, any custom DSL settings will not be preserved during the migration.
  The change is applied through https://github.com/elastic/elasticsearch/pull/115687[elasticsearch#115687]