[[apm-release-notes-8.18]]
== APM version 8.18

* <<apm-release-notes-8.18.8>>
* <<apm-release-notes-8.18.7>>
* <<apm-release-notes-8.18.6>>
* <<apm-release-notes-8.18.5>>
* <<apm-release-notes-8.18.4>>
* <<apm-release-notes-8.18.3>>
* <<apm-release-notes-8.18.2>>
* <<apm-release-notes-8.18.1>>
* <<apm-release-notes-8.18.0>>

[float]
[[apm-release-notes-8.18.8]]
=== APM version 8.18.8

https://github.com/elastic/apm-server/compare/v8.18.7\...v8.18.8[View commits]

[float]
==== Bug fixes

- APM Integration on ECH or ECE uses recommended frozen values for infrastructure related configs. See the https://github.com/elastic/kibana/issues/234384[Kibana PR #234384].

[float]
[[apm-release-notes-8.18.7]]
=== APM version 8.18.7

https://github.com/elastic/apm-server/compare/v8.18.6\...v8.18.7[View commits]

No significant changes in this release.

[float]
[[apm-release-notes-8.18.6]]
=== APM version 8.18.6

https://github.com/elastic/apm-server/compare/v8.18.5\...v8.18.6[View commits]

[float]
==== Bug fixes

- Fix a 8.18.1 and 8.19.0 regression in docker image causing permission denied when accessing /etc/pki/tls/certs/ca-bundle.crt due to incorrect directory permissions {pull}18141[18141]

[float]
==== Added

- Migrate UBI docker base image to upstream Red Hat UBI image {pull}18123[18123]

[float]
[[apm-release-notes-8.18.5]]
=== APM version 8.18.5

https://github.com/elastic/apm-server/compare/v8.18.4\...v8.18.5[View commits]

No significant changes in this release.

[float]
[[apm-release-notes-8.18.4]]
=== APM version 8.18.4

https://github.com/elastic/apm-server/compare/v8.18.3\...v8.18.4[View commits]

No significant changes in this release.

[float]
[[apm-release-notes-8.18.3]]
=== APM version 8.18.3

https://github.com/elastic/apm-server/compare/v8.18.2\...v8.18.3[View commits]

[float]
==== Bug fixes
- Log Tail Based Sampling pubsub errors at error or warn level instead of debug {pull}17178[17178]

[float]
==== Breaking Changes

[float]
==== Deprecations

[float]
==== Intake API Changes

[float]
==== Added

[float]

[[apm-release-notes-8.18.2]]
=== APM version 8.18.2

https://github.com/elastic/apm-server/compare/v8.18.1\...v8.18.2[View commits]

[float]
==== Bug fixes

[float]
==== Breaking Changes

[float]
==== Deprecations

[float]
==== Intake API Changes

[float]
==== Added

[float]
[[apm-release-notes-8.18.1]]
=== APM version 8.18.1

https://github.com/elastic/apm-server/compare/v8.18.0\...v8.18.1[View commits]

[float]
==== Bug fixes

- Tail-based sampling: ignore subscriber position read error and proceed as if file does not exist to avoid crash looping {pull}16736[16736]

[float]
==== Breaking Changes

[float]
==== Deprecations

[float]
==== Intake API Changes

[float]
==== Added

- Use `ca-bundle.crt` from Chainguard image instead of vendoring in Docker image {pull}16928[16928] {pull}16956[16956]

[float]
[[apm-release-notes-8.18.0]]
=== APM version 8.18.0

https://github.com/elastic/apm-server/compare/v8.17.1\...v8.18.0[View commits]

[float]
==== Bug fixes
- Fix overflow in validation of `apm-server.agent.config.cache.expiration` on 32-bit architectures {pull}15216[15216]
- Change permissions of `apm-server.yml` in `tar.gz` artifacts to `0600` {pull}15627[15627]
- Tail-based sampling: Fix an issue with the "drop and recreate Badger DB on storage limit exceeded" mitigation introduced in 8.17.1 and 8.16.3. Previously, a bug in this mitigation caused the tail sampling storage size to remain between 90% and 100% of the configured limit indefinitely without triggering the intended mitigation after TTL time. {pull}16385[16385]

[float]
==== Breaking Changes

[float]
==== Deprecations

[float]
==== Intake API Changes

[float]
==== Added
