[[apm-release-notes-8.18]]
== APM version 8.18

* <<apm-release-notes-8.18.1>>
* <<apm-release-notes-8.18.0>>

[float]
[[apm-release-notes-8.18.1]]
=== APM version 8.18.1

https://github.com/elastic/apm-server/compare/v8.18.0\...v8.18.1[View commits]

[float]
==== Bug fixes

- Tail-based sampling: ignore subscriber position read error and proceed as if file does not exist to avoid crash looping {pull}16736[16736]

[float]
==== Breaking Changes

[float]
==== Deprecations

[float]
==== Intake API Changes

[float]
==== Added

[float]
[[apm-release-notes-8.18.0]]
=== APM version 8.18.0

https://github.com/elastic/apm-server/compare/v8.17.1\...v8.18.0[View commits]

[float]
==== Bug fixes
- Fix overflow in validation of `apm-server.agent.config.cache.expiration` on 32-bit architectures {pull}15216[15216]
- Change permissions of `apm-server.yml` in `tar.gz` artifacts to `0600` {pull}15627[15627]
- Tail-based sampling: Fix an issue with the "drop and recreate Badger DB on storage limit exceeded" mitigation introduced in 8.17.1 and 8.16.3. Previously, a bug in this mitigation caused the tail sampling storage size to remain between 90% and 100% of the configured limit indefinitely without triggering the intended mitigation after TTL time. {pull}16385[16385]

[float]
==== Breaking Changes

[float]
==== Deprecations

[float]
==== Intake API Changes

[float]
==== Added
