[[apm-release-notes-8.19]]
== APM version 8.19
* <<apm-release-notes-8.19.8>>
* <<apm-release-notes-8.19.7>>
* <<apm-release-notes-8.19.6>>
* <<apm-release-notes-8.19.5>>
* <<apm-release-notes-8.19.4>>
* <<apm-release-notes-8.19.3>>
* <<apm-release-notes-8.19.2>>
* <<apm-release-notes-8.19.1>>
* <<apm-release-notes-8.19.0>>

[float]
[[apm-release-notes-8.19.8]]
=== APM version 8.19.8

https://github.com/elastic/apm-server/compare/v8.19.7\...v8.19.8[View commits]

[float]
==== Bug fixes

[float]
[[apm-release-notes-8.19.7]]
=== APM version 8.19.7

https://github.com/elastic/apm-server/compare/v8.19.6\...v8.19.7[View commits]

[float]
==== Bug fixes

- Fix build pipeline to ensure resulting binary info shows `vcs.modified=false` {pull}19510[19510]

[float]
[[apm-release-notes-8.19.6]]
=== APM version 8.19.6

https://github.com/elastic/apm-server/compare/v8.19.5\...v8.19.6[View commits]

[float]
==== Bug fixes

- Fix `output.elasticsearch.bulk_requests.available` metric to correctly report the available bulk indexers {pull}18951[18951]

[float]
[[apm-release-notes-8.19.5]]
=== APM version 8.19.5

https://github.com/elastic/apm-server/compare/v8.19.4\...v8.19.5[View commits]

[float]
==== Bug fixes

- APM Integration on ECH or ECE uses recommended frozen values for infrastructure related configs. The fix is applied through https://github.com/elastic/kibana/pull/235306[kibana#235306].

[float]
[[apm-release-notes-8.19.4]]
=== APM version 8.19.4

https://github.com/elastic/apm-server/compare/v8.19.3\...v8.19.4[View commits]

No significant changes.

[float]
[[apm-release-notes-8.19.3]]
=== APM version 8.19.3

https://github.com/elastic/apm-server/compare/v8.19.2\...v8.19.3[View commits]

[float]
==== Bug fixes

- Fix a 8.18.1 and 8.19.0 regression in docker image causing permission denied when accessing /etc/pki/tls/certs/ca-bundle.crt due to incorrect directory permissions {pull}18126[18126]

[float]
==== Added

- Migrate UBI docker base image to upstream Red Hat UBI image {pull}18122[18122]

[float]
[[apm-release-notes-8.19.2]]
=== APM version 8.19.2

https://github.com/elastic/apm-server/compare/v8.19.1\...v8.19.2[View commits]

[float]
==== Bug fixes

[float]
[[apm-release-notes-8.19.1]]
=== APM version 8.19.1

https://github.com/elastic/apm-server/compare/v8.19.0\...v8.19.1[View commits]

[float]
==== Bug fixes

- Fix Fleet-managed apm-server hanging or crashing on config hot reload due to duplicate monitoring registry {pull}17872[17872]

[float]
[[apm-release-notes-8.19.0]]
=== APM version 8.19.0

https://github.com/elastic/apm-server/compare/v8.18.1\...v8.19.0[View commits]

[float]
==== Bug fixes

- Fix default tracer `http request sent to https endpoint` error when both self-instrumentation and TLS are enabled {pull}17293[17293]
- TBS: Surface pubsub subscriber errors by logging at Warn level for `429` and Error level for others, instead of Debug level {pull}17135[17135]

[float]
==== Breaking Changes

[float]
==== Deprecations

[float]
==== Intake API Changes

[float]
==== Added

- Add config for tail-based sampling discard on write {pull}13950[13950]
- Add config for tail-based sampling TTL {pull}16579[16579]
- Use `ca-bundle.crt` from Chainguard image instead of vendoring in Docker image {pull}16928[16928] {pull}16956[16956]
