[[release-notes-8.3]]
== APM version 8.3

https://github.com/elastic/apm-server/compare/8.2\...8.3[View commits]

* <<release-notes-8.3.0>>

[float]
[[release-notes-8.3.0]]
=== APM version 8.3.0

https://github.com/elastic/apm-server/compare/8.2.2\...8.3.0[View commits]

[float]
==== Breaking Changes
- [experimental] Removed support for experimental firehose endpoint for CloudWatch metric streams {pull}8109[8109]

[float]
==== Deprecations
- `span.context.destination.service.resource` is deprecated {pull}7925[7925]

[float]
==== Bug fixes
- Propagate datastream namespace changes from apm-integration into server {pull}8176[8176]
- Allow 100% tail-based sampling {pull}8233[8233]

[float]
==== Intake API Changes
- For OpenTelemetry exception span events, stack traces that cannot be parsed will now be stored in `event.stack_trace` {pull}7706[7706]
- Support for ingesting `service.target.type` and `service.target.name` added to intake API for spans {pull}7870[7870]
- Derive `service.target.{type, name}` fields for older agents from `span.context.destination.service.resource` {pull}7925[7925]
- Support `service.target.*` in metrics aggregation {pull}7924[7924]

[float]
==== Added
- System, process, and well-defined runtime metrics are now sent to the shared `metrics-apm.internal-<namespace>` data stream {pull}7882[7882]
- Number of parallel bulk requests are now configurable via `output.elasticsearch.max_requests` {pull}8055[8055]
- OTLP/HTTP protocol is now supported {pull}8156[8156]
