[[release-notes-8.3]]
== APM version 8.3

https://github.com/elastic/apm-server/compare/8.2\...8.3[View commits]

* <<release-notes-8.3.3>>
* <<release-notes-8.3.2>>
* <<release-notes-8.3.1>>
* <<release-notes-8.3.0>>

[float]
[[release-notes-8.3.3]]
=== APM version 8.3.3

https://github.com/elastic/apm-server/compare/v8.3.2\...v8.3.3[View commits]

[float]
==== Bug fixes
- Update APM integration description {pull}8592[8592]

[float]
[[release-notes-8.3.2]]
=== APM version 8.3.2

https://github.com/elastic/apm-server/compare/v8.3.1\...v8.3.2[View commits]

[float]
==== Bug fixes
- When tail-based sampling is enabled, limit the local disk space for the feature to 3GB {pull}8407[8407]

[float]
[[release-notes-8.3.1]]
=== APM version 8.3.1

https://github.com/elastic/apm-server/compare/v8.3.0\...v8.3.1[View commits]

No significant changes.

[float]
[[release-notes-8.3.0]]
=== APM version 8.3.0

https://github.com/elastic/apm-server/compare/v8.2.2\...v8.3.0[View commits]

[float]
==== Breaking Changes
- [experimental] Removed support for experimental firehose endpoint for CloudWatch metric streams {pull}8109[8109]

[float]
==== Deprecations
- `span.context.destination.service.resource` is deprecated {pull}7925[7925]

[float]
==== Bug fixes
- Propagate datastream namespace changes from apm-integration into server {pull}8176[8176]
- Correct the `libbeat.output.write.bytes` metric to count the written bytes after the compressed writer has been flushed {pull}8221[8221]
- Allow 100% tail-based sampling {pull}8233[8233]

[float]
==== Intake API Changes
- For OpenTelemetry exception span events, stack traces that cannot be parsed will now be stored in `event.stack_trace` {pull}7706[7706]
- Support for ingesting `service.target.type` and `service.target.name` added to intake API for spans {pull}7870[7870]
- Derive `service.target.{type, name}` fields for older agents from `span.context.destination.service.resource` {pull}7925[7925]
- Support `service.target.*` in metrics aggregation {pull}7924[7924]

[float]
==== Added
- System, process, and well-defined runtime metrics are now sent to the shared `metrics-apm.internal-<namespace>` data stream {pull}7882[7882]
- Number of parallel bulk requests are now configurable via `output.elasticsearch.max_requests` {pull}8055[8055]
- OTLP/HTTP protocol is now supported {pull}8156[8156]

[float]
==== Performance improvements
- Limit the number of gomaxprocs when CPU limits have been set within a cgroup, yielding significant performance improvements, particularly when the APM Server experiences high traffic from a high number of APM agents {pull}8175[8175] {pull}8278[8278]
