[[release-notes-8.5]]
== APM version 8.5

https://github.com/elastic/apm-server/compare/8.4\...8.5[View commits]

* <<release-notes-8.5.3>>
* <<release-notes-8.5.2>>
* <<release-notes-8.5.1>>
* <<release-notes-8.5.0>>

[float]
[[release-notes-8.5.3]]
=== APM version 8.5.3

[float]
==== Bug fixes
- OpenTelemetry GRPC Spans from the Javascript API/SDK/Instrumentations are now correctly transformed into transactions with type=`request` {pull}9308[9308]

[float]
[[release-notes-8.5.2]]
=== APM version 8.5.2

This release includes an important APM Server bug fix.
Users running APM Server with Tail Sampling enabled in version >=8.3.0 and above should upgrade immediately.

https://github.com/elastic/apm-server/compare/v8.5.1\...v8.5.2[View commits]

[float]
==== Bug fixes
- Fix Tail Sampling OOM issues when storage limit is reached {pull}9583[9583]
- Null APM agent configuration entries are now treated as empty, and will not cause the server to exit with an error {pull}9546[9546]

[float]
[[release-notes-8.5.1]]
=== APM version 8.5.1

https://github.com/elastic/apm-server/compare/v8.5.0\...v8.5.1[View commits]

[float]
==== Bug fixes
- Set `error.id` for OpenTelemetry exception span events {pull}9327[9327]
- Add an `apm-server` user to /etc/passwd in the Docker images {pull}9496[9496]

[float]
[[release-notes-8.5.0]]
=== APM version 8.5.0

https://github.com/elastic/apm-server/compare/v8.4.3\...v8.5.0[View commits]

[float]
==== Known issue
Due to a recent change in the Red Hat scan verification process,
this version of APM Server is not available in the Red Hat Ecosystem Catalog.
This bug will be fixed in the next release.
Please use the https://www.docker.elastic.co/r/apm[Elastic docker registry] to download the 8.5.0 APM Server image.

[float]
==== Breaking Changes
- `event.action` is no longer recorded for OTLP logs, due to breaking OTLP changes {pull}8765[8765]
- Experimental support for ingesting profile data has been removed {pull}8911[8911]
- `process.ppid` has been renamed to `process.parent.pid` for alignment with ECS {pull}8783[8783]

[float]
==== Deprecations

[float]
==== Bug fixes
- Set `message` instead of `labels.event` for Jaeger span events {pull}8765[8765]
- Reach full support (still technical preview) for Java agent auto attachment on Linux by allowing attachment to a JVM of any user {pull}8803[8803]
- The OTLP/HTTP handlers now support gzip and deflate compression {pull}9067[9067]
- The Fleet integration now applies source maps correctly when they have been uploaded with a relative bundle_filepath {pull}9082[9082]
- Dynamically map all simple numerical metrics as `double`, to avoid mapping conflicts {pull}8868[8868]
- Fix data stream migration ingest pipeline, upgrading old `observer.*` and `process.ppid` fields {pull}9095[9095]
- Fix ordering of processors to ensure `host.hostname` is set consistently in aggregated metrics {pull}8983[8983]

[float]
==== Intake API Changes
- Add a new `async` boolean query parameter (`intake/v2/events?async=<true|false>`).
  When set to `true`, the batch will be processed asynchronously if the APM Server can
  service the incoming request immediately, otherwise a "503 queue is full" error will
  be returned {pull}8979[8979]
- experimental:[] Add logs support to v2 intake API {pull}9068[9068]

[float]
==== Added
- Set a default User-Agent field value when making HTTP requests {pull}8758[8758]
- OTLP support updated to opentelemetry-collector v0.56.0 {pull}8765[8765]
- Map additional fields from mobile agents {pull}8784[8784]
- Include global labels to the transaction metric dimensions {pull}8839[8839]
- Add an experimental integration of the Profiling collection agent gRPC service {pull}9005[9005]
- Clarify tail-based sampling storage limit reached errors {pull}9085[9085]
- Added support for new OTel JVM metric names, as changed in OTel Java SDK v1.13.0 {pull}8777[8777]
- experimental:[] Added technical preview of aggregated service metrics {pull}8607[8607]
