[[release-notes-8.6]]
== APM version 8.6

https://github.com/elastic/apm-server/compare/8.5\...8.6[View commits]

* <<release-notes-8.6.2>>
* <<release-notes-8.6.1>>
* <<release-notes-8.6.0>>

[float]
[[release-notes-8.6.2]]
=== APM version 8.6.2

https://github.com/elastic/apm-server/compare/v8.6.1\...v8.6.2[View commits]

No significant changes.

[float]
[[release-notes-8.6.1]]
=== APM version 8.6.1

https://github.com/elastic/apm-server/compare/v8.6.0\...v8.6.1[View commits]

[float]
==== Bug fixes
- Fix panic when memory limits are missing in cgroupV1 {pull}10098[10098]
- Fix internal traffic filter handling on Elastic Cloud when managed by Elastic Agent (Integrations Server)

[float]
[[release-notes-8.6.0]]
=== APM version 8.6.0

[float]
==== Breaking Changes
- `apm-server.decoder.*` stack monitoring metrics are no longer recorded {pull}9210[9210]
- `ecs.version` is no longer added to document `_source`; it is added as a `constant_keyword` field {pull}9208[9208]
- `context.http.response.*_size` fields now enforce integer values {pull}9429[9429]
- `observer.id` and `observer.ephemeral_id` are no longer added to APM documents {pull}9412[9412]
- `timeseries.instance` has been removed from transaction metrics docs; it was never used {pull}9565[9565]

[float]
==== Deprecations
- `apm-server apikey` commands have been deprecated. API Keys should be managed through Kibana or the Elasticsearch REST API {pull}9446[9446]

[float]
==== Bug fixes
- Change ownership of apm-server.yml and data/ to apm-server user in Docker image {pull}9604[9604]

[float]
==== Intake API Changes
- experimental:[] Extend logs v2 intake API to support ECS logging fields {pull}9349[9349]
- experimental:[] Add support for string timestamp format(`2006-01-02T15:04:05.999-0700`) {pull}9376[9376]
- `context.http.response.*_size` fields have been changed from floating-point to integer types {pull}9429[9429]

[float]
==== Added
- Service metrics now support global labels {pull}9248[9248]
- OpenTelemetry GRPC Spans from the Javascript API/SDK/Instrumentations are now correctly transformed into transactions with type=`request` {pull}9308[9308]
- Improve Elasticsearch output performance, particularly when compression is enabled (default) {pull}9318[9318]
- Java attacher support for macOS {pull}9413[9413]
- Improve Elasticsearch output performance in instances with more than 6 cores {pull}9393[9393]
- Tune internal server configuration based on available cgroup or machine RAM, improving resource utilization and performance {pull}9358[9358]
- Disallow auto-scaling of active indexers when Elasticsearch 429 response rate exceeds 1% of total requests issued {pull}9463[9463]
- We now record `transaction.representative_count` and `span.representative_count` -- the inverse sample rate {pull}9458[9458]
