[[release-notes-8.7]]
== APM version 8.7

https://github.com/elastic/apm-server/compare/8.6\...8.7[View commits]

* <<release-notes-8.7.2>>
* <<release-notes-8.7.1>>
* <<release-notes-8.7.0>>

[float]
[[release-notes-8.7.2]]
=== APM version 8.7.2

https://github.com/elastic/apm-server/compare/v8.7.1\...v8.7.2[View commits]

[float]
==== Bug fixes

[float]
[[release-notes-8.7.1]]
=== APM version 8.7.1

https://github.com/elastic/apm-server/compare/v8.7.0\...v8.7.1[View commits]

[float]
==== Bug fixes
- Fix indexing failures for metric, error and log documents when `agent.activation_method` is set {pull}10552[10552]
- Use droppedspan outcome in service destination aggregation {pull}10592[10592]
- metrics: Count context.DeadlineExceeded as timeout {pull}10594[10594]
- metrics: Count GRPC codes.Canceled as timeout {pull}10605[10605]
- Remove global labels from aggregations for RUM services {pull}10624[10624]
- Remove redundant aggregation groups on `faas.coldstart` in transaction metrics {pull}10635[10635]

[float]
[[release-notes-8.7.0]]
=== APM version 8.7.0

[float]
==== Breaking Changes
- `transaction.failure_count` has been removed. `transaction.success_count` type has changed to `aggregated_metric_double` {pull}9791[9791]
- `transaction.success_count` has been moved to `event.success_count` {pull}9819[9819]
- Stop indexing transaction metrics to `metrics-apm.internal` {pull}9846[9846]
- Stop indexing span destination metrics to `metrics-apm.internal` {pull}9926[9926]
- `apmserver.aggregation.txmetrics.overflowed` metric has been renamed to `apmserver.aggregation.txmetrics.overflowed.total` {pull}10330[10330]
- Elasticsearch sourcemapping credentials require access to the `.apm-source-map` index {pull}9722[9722]
- Change APM Server default host to 127.0.0.1 {pull}9877[9877]

[float]
==== Bug fixes
- We no longer unconditionally block shutdown for 5 seconds when tail-based sampling is enabled {pull}9838[9838]
- Fix a panic caused by accepting new grpc connections during shutdown {pull}10013[10013]
- Fix goroutine leak in libbeat final processor {pull}10247[10247]
- Fix servicemetrics aggregator name typo {pull}10022[10022]

[float]
==== Intake API Changes
- Add `request.id` to `span.context.http` {pull}9673[9673]
- Add `agent.activation_method` metadata field {pull}9850[9850]

[float]
==== Added
- Metrics data streams now use synthetic source {pull}9756[9756]
- Translate otel log events to error events {pull}10066[10066] {pull}10128[10128]
- Use Elasticsearch fetcher for agent remote configuration where possible {pull}9720[9720] {pull}10088[10088] {pull}10115[10115]
- Fetch sourcemaps from Elasticsearch {pull}9722[9722] {pull}10367[10367] {pull}10360[10360] {pull}10106[10106]
- Add support for RHEL 9 {pull}10317[10317]

[float]
==== Transaction metric improvements
- Add `event.success_count` to transaction metrics {pull}9819[9819] {pull}10165[10165]
- Add `transaction.duration.summary` to transaction metrics {pull}9973[9973] {pull}10214[10214]
- Introduce overflow buckets to limit cardinality and scale the max groups based on available memory {pull}9856[9856] {pull}10157[10157] {pull}10362[10362] {pull}9911[9911] {pull}10012[10012] {pull}10190[10190]
- Add overflow metrics collection {pull}10330[10330]
- Improve APM UI query performance by producing `1m`, `10m` and `60m` aggregation intervals for transaction metrics. Store them into hidden data streams `metrics-apm.transaction.${interval}` {pull}9846[9846] {pull}10070[10070]
- Reduce memory footprint of transaction aggregations {pull}10178[10178]

[float]
==== Service transaction metric improvements
- Introduce overflow buckets to limit cardinality and scale the max groups based on available memory {pull}9856[9856] {pull}10157[10157] {pull}9911[9911] {pull}10012[10012]
- Add overflow metrics collection {pull}10330[10330]
- Rename service metrics to service transaction metrics {pull}10095[10095] {pull}10110[10110]
- Improve APM UI query performance by producing `1m`, `10m` and `60m` aggregation intervals for service metrics. Store them into hidden data streams `metrics-apm.service.${interval}` {pull}9960[9960] {pull}10070[10070]
- Add `service.language.name` {pull}10111[10111]
- Add histogram support {pull}9864[9864] {pull}10214[10214] {pull}10127[10127] {pull}10216[10216]
- Always enable metrics aggregaton and remove config option {pull}10060[10060] {pull}10109[10109]
- Reduce memory footprint of service transaction aggregations {pull}10178[10178]

[float]
==== Service destination metric improvements
- Introduce overflow buckets to limit cardinality {pull}10069[10069]
- Add overflow metrics collection {pull}10330[10330]
- Set `_doc_count` for service destination metrics {pull}9931[9931]
- Add global labels to service destination metrics {pull}10056[10056] {pull}10297[10297]
- Improve APM UI query performance by producing `1m`, `10m` and `60m` aggregation intervals for service destination metrics. Store them into data streams `metrics-apm.service_destination.${interval}` and make them hidden for non-default intervals {pull}9926[9926] {pull}10070[10070]

[float]
==== Introducing Service summary metric improvements
- Introduce service summary metrics {pull}10111[10111]
- Introduce overflow buckets to limit cardinality {pull}10061[10061] {pull}10302[10302]
- Add overflow metrics collection {pull}10330[10330]
- Improve APM UI query performance by adding an always enabled service summary metrics aggregator which produces `1m`, `10m` and `60m` aggregation intervals. Store them into data streams `metrics-apm.service_summary.${interval}` and make them hidden for
non-default intervals {pull}10029[10029] {pull}10060[10060] {pull}10070[10070]
- Add `service.language.name` {pull}10111[10111]
