[[apm-release-notes-9.0]]
== APM version 9.0
* <<apm-release-notes-9.0.0>>

[float]
[[apm-release-notes-9.0.0]]
=== APM version 9.0.0

https://github.com/elastic/apm-server/compare/v\...v9.0.0[View commits]

[float]
==== Bug fixes
- Fix overflow in validation of `apm-server.agent.config.cache.expiration` on 32-bit architectures {pull}15216[15216]
- Change permissions of `apm-server.yml` in `tar.gz` artifacts to `0600` {pull}15627[15627]

[float]
==== Breaking Changes
- Change `sampling.tail.storage_limit` default to `0`. While `0` means unlimited local tail-sampling database size, it now enforces a max 80% disk usage on the disk where the data directory is located. Any tail sampling writes after this threshold will be rejected, similar to what happens when tail-sampling database size exceeds a non-0 storage limit. Setting `sampling.tail.storage_limit` to non-0 maintains the existing behavior which limits the tail-sampling database size to `sampling.tail.storage_limit` and does not have the new disk usage threshold check. {pull}15467[15467] {pull}15524[15524]

[float]
==== Deprecations

[float]
==== Intake API Changes

[float]
==== Added
- Tail-based sampling: Storage layer is rewritten to use Pebble database instead of BadgerDB. The new implementation offers a substantial throughput increase while consuming significantly less memory. Disk usage is lower and more stable. See PR for benchmark details. {pull}15235[15235]
