[[release-notes-head]]
== APM Server version HEAD

https://github.com/elastic/apm-server/compare/6.4\...master[View commits]

[float]
=== Added

- Provide basic server information at `/` {pull}1197[1197]
- Add pipeline registration and pipeline usage {pull}1258[1258],{pull}1296[1296]
- Allow sending `tags` for `spans`, that get indexed in ES {pull}1156[1156].
- Add pipeline registration and pipeline usage {pull}1258[1258]
- Update JSON schema spec for v2 {pull}1303[1303]
- Make JSON schema spec distributed tracing compliant {pull}1303[1303]
- Add required `transaction.span_count.started` to Intake v2 {pull}1351[1351]
- Rename `transaction.span_count.dropped.total` to `transaction.span_count.dropped` on Intake API v2 {pull}1351[1351]
- Require either `message` or `type` for `error.exception` {pull}1354[1354].
- Require `span.parent_id`, forbid `null` for `span.trace_id`, `transaction.trace_id` {pull}1391[1391]
- Require `error.id` and changed description to 128 random bits ID {pull}1384[1384]
- Add apm-server monitoring {pull}1382[1382].
