[[release-notes-head]]
== APM Server version HEAD

https://github.com/elastic/apm-server/compare/6.5\...6.x[View commits]

[float]
=== Added

- Set some configuration defaults (setup.template.settings.index.*, logging.metrics.enabled) in code {pull}1494[1494].
- Add `span.sync` property to intake json spec and index field in ES. {pull}1548[1548].
- Make `service.framework` properties optional and nullable {pull}1546[1546].
- Add `transaction.sampled` to errors {pull}1662[1662].
- Remove formatting of `duration.us` to milliseconds in index pattern pull{1717}[1717].
- Allow numbers and boolean values for `transaction.tags`, `span.tags`, `metricset.tags` {pull}1712[1712].
- Lookup sourcemaps by full URL and URL path only {pull}1661[1661].

[float]
==== Removed
- Remove support for using dots in tags for experimental metricset endpoint {pull}1712[1712].

[float]
==== Bug fixes

- Fix index pattern bundled with Kibana to be in sync with ES template pull{1571}[1571].
- Ensure all `transaction.marks.*.*` values are stored as scaled floats. pull{1704}[1704].
- Prevent slice out of bounds panic when sourcemap line numbers are off {pull}1764[1764].
