[[release-notes-head]]
== APM Server version HEAD

https://github.com/elastic/apm-server/compare/7.13\...master[View commits]

[float]
==== Breaking Changes
- `network.connection_type` is now `network.connection.type` {pull}5671[5671]
- `transaction.page` and `error.page` no longer recorded {pull}5872[5872]
- experimental:["This breaking change applies to the experimental tail-based sampling feature."] `apm-server.sampling.tail` now requires `apm-server.data_streams.enabled` {pull}5952[5952]
- beta:["This breaking change applies to the beta <<apm-integration>>."] The `traces-sampled-*` data stream is now `traces-apm.sampled-*` {pull}5952[5952]
- Removed unused stacktrace/frame monitoring counters {pull}5984[5984]
- Removed unused support for top-level metricsets and metricset tags for RUMv3 {pull}6065[6065]
- Removed `apm-server.mode` configuration, and "experimental" fields {pull}6086[6086]
- `transaction.sampled` is now only set for sampled transactions {pull}6066[6066]
- Unknown metrics are dropped when `transaction.*` or `span.*` are present in a metricset {pull}6111[6111]
- Removed `metricset.period` from service_destination metrics {pull}6111[6111]

[float]
==== Bug fixes
- Fix apm_error_grouping_name and apm_convert_destination_address {pull}5876[5876]
- corrected OTel attribute names for `net.host.connection.*` {pull}5671[5671]
- Fix response to agent config when running under Fleet with no agent config defined {pull}5917[5917]
- Fix handling of OTLP sum/gauge metrics with integer values {pull}6106[6106]

[float]
==== Intake API Changes
- `network.connection.type` was added to stream metadata {pull}5671[5671]

[float]
==== Added
- `service_destination` span metrics now take into account composite spans {pull}5896[5896]
- add zero-downtime config reloads via `SO_REUSEPORT` {pull}5911[5911]
- experimental support for writing data streams in standalone mode {pull}5928[5928]
- Data streams now define a default `dynamic` mapping parameter, overridable in the `<data-stream>@custom` template {pull}5947[5947]
- The `error.log.message` or `error.exception.message` field of errors will be copied to the ECS field `message` {pull}5974[5974]

[float]
==== Deprecated
