[[release-notes-head]]
== APM version HEAD

https://github.com/elastic/apm-server/compare/8.1\...main[View commits]

[float]
==== Breaking Changes
- APM Server now emits events with `event.duration`, and renames the field to `<event>.duration.us` in an ingest pipeline {pull}7261[7261]

[float]
==== Bug fixes
- Do not overwrite `service version` if no transaction/error/... specific `service.name` is given {pull}7281[7281]
- Fix missing stack monitoring metrics {pull}7428[7428]

[float]
==== Intake API Changes
- Support for `faas.name` and `faas.version` added to intake and transaction metrics {pull}7427[7427]
- If proxy headers are present: `source.ip` and `client.ip` set to header values, and `source.nat.ip` set to incoming request IP {pull}7444[7444]

[float]
==== Added
- Implemented translation of OpenTelemetry host system metrics (CPU utilization / Memory usage) {pull}7090[7090]
- Added support for storing OpenTelemetry span links as `span.links` {pull}7291[7291]
- seccomp is disabled by default {pull}7308[7308]
- Added data stream namespace configuration for standalone with `apm-server.data_streams.namespace` {pull}7314[7314]



// Added but still being debugged
- `apm-server` artifacts now have the apm java-attacher.jar packaged alongside them {pull}6593[6593]
- Run the java attacher jar when configured and not in a cloud environment {pull}6617[6617]
