[[release-notes-head]]
== APM version HEAD

https://github.com/elastic/apm-server/compare/8.12\...main[View commits]

[float]
==== Breaking Changes

[float]
==== Bug fixes

[float]
==== Deprecations

[float]
==== Intake API Changes

[float]
==== Added
- map OTel's `span.Status: Unset` to `event.outcome: success` instead of `event.outcome: unknown`
- Add support for Otel code.stacktrace {pull}12096[12096]
- `http.request.body.bytes` now reports the bytes read from request body even if Content-Length is -1 {pull}12451[12451]
- Use `messaging.system` and `messaging.operation` to detect OTel messaging span for transactions {pull}12506[12506]
- Add support for OTel data stream routing by parsing `data_stream.dataset` and `data_stream.namespace` from: (from lowest to highest precedence) resource attributes, instrumentation scope attributes, and signal-level attributes. This is a breaking change only for users relying on the existing `data_stream` attributes being stored as labels. {pull}12578[12578]
