[[release-notes-head]]
== APM version HEAD

https://github.com/elastic/apm-server/compare/8.6\...main[View commits]

[float]
==== Breaking Changes
- `transaction.failure_count` has been removed. `transaction.success_count` type has changed to `aggregated_metric_double` {pull}9791[9791]
- `transaction.success_count` has been moved to `event.success_count` {pull}9819[9819]
- Improve APM UI query performance by introducing `10m` and `60m` aggregation intervals for transaction metrics. Store them into dedicated data streams `metrics-apm.transaction.${interval}`, and remove transaction metrics from `metrics-apm.interval` {pull}9846[9846]

[float]
==== Deprecations

[float]
==== Bug fixes
- We no longer unconditionally block shutdown for 5 seconds when tail-based sampling is enabled {pull}9838[9838]

[float]
==== Intake API Changes
- Add `request.id` to `span.context.http` {pull}9673[9673]
- Add `agent.activation_method` metadata field {pull}9850[9850]

[float]
==== Added
- Metrics data streams now use synthetic source {pull}9756[9756]
- Add `event.success_count` to transaction events and transaction metrics {pull}9819[9819]
- Dedicated overflow buckets for transaction and service aggregation to limit cardinality {pull}9856[9856]
- Automatically scale `MaxGroups` and `MaxTransactionGroups` based on available memory {pull}9856[9856]
