[[release-notes-head]]
== APM Server version HEAD

[float]
==== Added

- Update Elastic APM Go agent to v1.1.2 {pull}1711[1711], {pull}1728[1728].
- Allow numbers and boolean values for `transaction.tags`, `span.tags`, `metricset.tags` {pull}1712[1712].
- Update response format of the healthcheck handler and prettyfy all JSON responses {pull}1748[1748].
- Add transaction.type to error data {pull}1781[1781].
- Rename transaction.span_count.dropped.total to transaction.span_count.dropped {pull}1809[1809].
- Rename span.hex_id to span.id {pull}1811[1811].
- Index error.exception as array of objects {pull}1825[1825]
- Update Go version to 1.11.5 {pull}1840[1840].
- Change ownership to apm-server user/group for deb/rpm installs {pull}1833[1833].
- Retrieve `span.subtype` and `span.action` from `span.type` if not given {pull}1843[1843].
- Add observer.version_major {pull}1857[1857].
- Change transaction.name to keyword, add transaction.name.text {pull}1859[1859].
- Change error.culprit to keyword, limit length on intake {pull}1859[1859].
- Change default user-agent pipeline to index information under root key `user_agent` {pull}[].

[float]
==== Removed
- Remove support for using dots in tags for experimental metricset endpoint {pull}1712[1712].
- Remove formatting of `duration.us` to milliseconds in index pattern pull{1717}[1717].
- Remove support for deprecated Intake v1 endpoints {pull}1731[1731].
- Remove `concurrent_requests` setting and use number of CPUs instead {pull}1749[1749].
- Remove `frontend` setting {pull}1751[1751].
- Remove `metrics.enabled` setting {pull}1759[1759].
- Remove dashboards from being shipped with APM Server and all logic around them {pull}[1815].

https://github.com/elastic/apm-server/compare/v7.0.0-alpha2...master[View commits]
