[[release-notes-head]]
== APM version HEAD

https://github.com/elastic/apm-server/compare/8.5\...main[View commits]

[float]
==== Breaking Changes
- `event.action` is no longer recorded for OTLP logs, due to breaking OTLP changes {pull}8765[8765]
- Experimental support for ingesting profile data has been removed {pull}8911[8911]

[float]
==== Deprecations

[float]
==== Bug fixes
- Set `message` instead of `labels.event` for Jaeger span events {pull}8765[8765]
- Reach full support (still technical preview) for Java agent auto attachment on Linux by allowing attachment to a JVM of any user {pull}8803[8803]
- The OTLP/HTTP handlers now support gzip and deflate compression {pull}9067[9067]
- The Fleet integration now applies source maps correctly when they have been uploaded with a relative bundle_filepath {pull}9082[9082]

[float]
==== Intake API Changes
- Add a new `async` boolean query parameter (`intake/v2/events?async=<true|false>`).
  When set to `true`, the batch will be processed asynchronously if the APM Server can
  service the incoming request immediately, otherwise a "503 queue is full" error will
  be returned {pull}8979[8979]
- experimental:[] Add logs support to v2 intake API {pull}9068[9068]

[float]
==== Added
- Set a default User-Agent field value when making HTTP requests {pull}8758[8758]
- OTLP support updated to opentelemetry-collector v0.56.0 {pull}8765[8765]
- Map additional fields from mobile agents {pull}8784[8784]
- Include global labels to the transaction metric dimensions {pull}8839[8839]
- Add an experimental integration of the Profiling collection agent gRPC service {pull}9005[9005]
- Clarify tail-based sampling storage limit reached errors {pull}9085[9085]
