[[release-notes-head]]
== APM version HEAD

https://github.com/elastic/apm-server/compare/8.1\...main[View commits]

[float]
==== Breaking Changes
- APM Server now emits events with `event.duration`, and renames the field to `<event>.duration.us` in an ingest pipeline {pull}7261[7261]
- Remove `observer.version_major` {pull}7399[7399]
- APM Server no longer ships with SystemV init scripts or the go-daemon wrapper; use systemd {pull}7576[7576]
- When gzip compressing Elasticsearch bulk requests, set the end of stream marker {pull}7624[7624]

[float]
==== Deprecations
- Deprecation of APM Server support for 32-bit architecture {pull}7678[7678]

[float]
==== Bug fixes
- Do not overwrite `service version` if no transaction/error/... specific `service.name` is given {pull}7281[7281]
- modelindexer: Fix indexing performance regression due to locking bug {pull}7649[7649]
- Set transaction name to "<method> unknown route" for unknown HTTP routes, in APM Server instrumentation {pull}7679[7679]

[float]
==== Intake API Changes
- Support for `faas.name` and `faas.version` added to intake and transaction metrics {pull}7427[7427]
- If proxy headers are present: `source.ip` and `client.ip` set to header values, and `source.nat.ip` set to incoming request IP {pull}7444[7444]
- Updated intake v2 with support for `links` in `transaction` and `span` events {pull}7553[7553]
- If an agent sends a transaction or span with type unspecified, the server now sets a default value of "unknown" {pull}7688[7688]

[float]
==== Added
- Implemented translation of OpenTelemetry host system metrics (CPU utilization / Memory usage) {pull}7090[7090]
- Added support for storing OpenTelemetry span links as `span.links` {pull}7291[7291]
- seccomp is disabled by default {pull}7308[7308]
- Added data stream namespace configuration for standalone with `apm-server.data_streams.namespace` {pull}7314[7314]



// Added but still being debugged
- `apm-server` artifacts now have the apm java-attacher.jar packaged alongside them {pull}6593[6593]
- Run the java attacher jar when configured and not in a cloud environment {pull}6617[6617]
