[[release-notes-head]]
== APM version HEAD

https://github.com/elastic/apm-server/compare/8.5\...main[View commits]

[float]
==== Breaking Changes
- `apm-server.decoder.*` stack monitoring metrics are no longer recorded {pull}9210[9210]
- `ecs.version` is no longer added to document `_source`; it is added as a `constant_keyword` field {pull}9208[9208]
- `context.http.response.*_size` fields now enforce integer values {pull}9429[9429]

[float]
==== Deprecations

[float]
==== Bug fixes
Set error.id for OpenTelemetry exception span events {pull}9372[9372]

[float]
==== Intake API Changes
- experimental:[] Extend logs v2 intake API to support ECS logging fields {pull}9349[9349]
- experimental:[] Add support for string timestamp format(`2006-01-02T15:04:05.999-0700`) {pull}9376[9376]
- `context.http.response.*_size` fields have been changed from floating-point to integer types {pull}9429[9429]

[float]
==== Added
- Metrics data streams now use synthetic source {pull}9215[9215]
- Service metrics now support global labels {pull}9248[9248]
- OpenTelemetry GRPC Spans from the Javascript API/SDK/Instrumentations are now correctly transformed into transactions with type=`request`
- Improve Elasticsearch output performance, particularly when compression is enabled (default) {pull}9318[9318]
- Java attacher support for macOS {pull}9413[9413]
