[[release-notes-head]]
== APM Server version HEAD

https://github.com/elastic/apm-server/compare/7.6\...master[View commits]

[float]
==== Breaking Changes

* Remove enroll subcommand {pull}3270[3270].

[float]
==== Bugfixes
* Merge default values with custom Elasticsearch config for API Keys and add `required` tag for `host` {pull}3342[3342]
* Merge default values with custom Sourcemap Elasticsearch config {pull}3355[3355]

[float]
==== Intake API Changes
* Add `transfer_size`, `encoded_body_size`  and `decoded_body_size` to `transaction.context.http.response` {pull}3327[3327]
* Add `transfer_size`, `encoded_body_size`, `decoded_body_size` and `headers` to `span.context.http.response` {pull}3327[3327]
* Deprecate `span.context.http.status_code` in favor of newly introduced `span.context.http.response.status_code` {pull}3327[3327]

[float]
==== Added

* Instrumentation for go-elasticsearch {pull}3305[3305]
* Make configurable the list of Access-Control-Allow-Headers for RUM preflight requests {pull}3299[3299]
* Initial RUM V3 endpoint {pull}3328[3328]
* Upgrade Go to 1.13.8 {pull}3326[3326]
* Add fingerprint field for servicemaps {pull}3374[3374]
