---
description: Pipeline for ingesting APM transaction metrics.
processors:
  - pipeline:
      name: observer_version
  - pipeline:
      name: observer_ids
  - pipeline:
      name: ecs_version
  - pipeline:
      name: set_metrics
  - remove:
      field: _dynamic_templates
      ignore_missing: true
