---

name: generate-smoke-tests-list
description: Generate smoke tests list

inputs:
  aws-csv-file:
    description: 'Content with the AWS csv file'
    required: true
  aws-profile:
    description: 'aws profile'
    required: true
outputs:
  tests:
    description: "List of smoke tests"
    value: ${{ steps.generate.outputs.tests }}
  date:
    description: "Current date"
    value: ${{ steps.generate.outputs.date }}

runs:
  using: "composite"
  steps:
    - name: Setup cluster env
      uses: ./.github/workflows/setup-cluster-env

    - uses: elastic/oblt-actions/aws/auth@v1
    - id: generate
      name: Generate matrix and date
      run: |
        # remove the full path and use a relative path instead to be github runner agnostic
        echo "tests=$(make smoketest/discover | sed "s#${GITHUB_WORKSPACE}/#./#g")" >> "${GITHUB_OUTPUT}"
        echo "date=$(date +%s)" >> "${GITHUB_OUTPUT}"
      shell: 'bash'
