---
description: Pipeline for ingesting APM internal metrics.
processors:
  - pipeline:
      name: observer_version
  - pipeline:
      name: observer_ids
  - pipeline:
      name: ecs_version
  - pipeline:
      name: user_agent
  - pipeline:
      name: process_ppid
  - pipeline:
      name: client_geoip
  - remove:
      # timeseries.instance removed in 8.6.0
      field: timeseries
      ignore_missing: true
  - pipeline:
      name: set_metrics
  - remove:
      field: _dynamic_templates
      ignore_missing: true
  - remove:
      field: event.received
      ignore_missing: true
      ignore_failure: true
      description: The field is used for internal statistics but does not need to be indexed.
