---
description: Pipeline for ingesting APM internal metrics.
processors:
  - pipeline:
      name: observer_version
  - pipeline:
      name: user_agent
  - pipeline:
      name: process_ppid
  - pipeline:
      name: client_geoip
