---
description: Pipeline for ingesting APM internal metrics.
processors:
  - pipeline: # drop transaction metrics coming from older APM Server versions.
      name: drop_tx_metrics
  - pipeline:
      name: observer_version
  - pipeline:
      name: observer_ids
  - pipeline:
      name: ecs_version
  - pipeline:
      name: user_agent
  - pipeline:
      name: process_ppid
  - pipeline:
      name: client_geoip
  - remove:
      field: _metric_descriptions
      ignore_missing: true
  - remove:
      # Removed in 8.6.0
      field: timeseries.instance
      ignore_missing: true
