---
description: Pipeline for ingesting APM application metrics.
processors:
  - pipeline:
      name: observer_version
  - pipeline:
      name: observer_ids
  - pipeline:
      name: ecs_version
  - pipeline:
      name: user_agent
  - pipeline:
      name: process_ppid
  - pipeline:
      name: client_geoip
  - pipeline:
      name: set_metrics
  - remove:
      field: event.received
      ignore_missing: true
      ignore_failure: true
      description: The field is used for internal statistics but does not need to be indexed.
