---
agents:
  - REPO: "apm-agent-dotnet"
    SPEC_FILEPATH: "src/Elastic.Apm.Specification/specs"
  - REPO: "apm-agent-go"
    SPEC_FILEPATH: "internal/apmschema/jsonschema"
  - REPO: "apm-agent-java"
    SPEC_FILEPATH: "apm-agent-core/src/test/resources/apm-server-schema/current"
  - REPO: "apm-agent-nodejs"
    SPEC_FILEPATH: "test/integration/api-schema/apm-server-schema"
  - REPO: "apm-agent-php"
    SPEC_FILEPATH: "tests/APM_Server_intake_API_schema/latest_used"
  - REPO: "apm-agent-python"
    SPEC_FILEPATH: "tests/upstream/json-specs"
  - REPO: "apm-agent-ruby"
    SPEC_FILEPATH: "spec/fixtures"
