include::../../version.asciidoc[]
include::{asciidoc-dir}/../../shared/attributes.asciidoc[]

:apm-ref-all: https://www.elastic.co/guide/en/apm/get-started/

ifdef::env-github[]
NOTE: For the best reading experience,
please view this documentation at https://www.elastic.co/guide/en/apm/get-started[elastic.co]
endif::[]

ifndef::apm-integration-docs[]
[[gettting-started]]
= APM Overview
endif::[]

ifdef::apm-integration-docs[]
// Overwrite links to the APM Overview and APM Server Ref. Point to APM Guide instead.
:apm-overview-ref-v: {apm-guide-ref}
:apm-guide-ref: {apm-guide-ref}
:apm-server-ref-v: {apm-guide-ref}
:apm-server-ref: {apm-guide-ref}

[[legacy-apm-overview]]
= Legacy APM Overview

****
{deprecation-notice-installation}
****

Elastic APM is an application performance monitoring system built on the Elastic Stack.
It allows you to monitor software services and applications in real-time, by
collecting detailed performance information on response time for incoming requests,
database queries, calls to caches, external HTTP requests, and more.
This makes it easy to pinpoint and fix performance problems quickly.

Elastic APM also automatically collects unhandled errors and exceptions.
Errors are grouped based primarily on the stacktrace,
so you can identify new errors as they appear and keep an eye on how many times specific errors happen.

Metrics are another vital source of information when debugging production systems.
Elastic APM agents automatically pick up basic host-level metrics and agent-specific metrics,
like JVM metrics in the Java Agent, and Go runtime metrics in the Go Agent.

[float]
== Give Elastic APM a try

Learn more about the <<components,components>> that make up Elastic APM,
or jump right into the <<install-and-run,quick start guide>>.

NOTE: These docs will indiscriminately use the word "service" for both services and applications.
endif::[]

include::./overview.asciidoc[]

include::./apm-doc-directory.asciidoc[]

include::./install-and-run.asciidoc[]

include::./quick-start-overview.asciidoc[]

include::./apm-data-model.asciidoc[]

include::./features.asciidoc[]

include::./agent-server-compatibility.asciidoc[]

include::./troubleshooting.asciidoc[]

include::./apm-breaking-changes.asciidoc[]

include::./redirects.asciidoc[]
