[[opentracing]]
=== OpenTracing bridge

IMPORTANT: {deprecation-notice-data}

Most Elastic APM agents have https://opentracing.io/[OpenTracing] compatible bridges.

The OpenTracing bridge allows you to create Elastic APM <<transactions,transactions>> and <<transaction-spans,spans>> using the OpenTracing API.
This means you can reuse your existing OpenTracing instrumentation to quickly and easily begin using Elastic APM.

[float]
==== Agent specific details

Not all features of the OpenTracing API are supported, and there are some Elastic APM-specific tags you should be aware of. Please see the relevant Agent documentation for more detailed information:

* {apm-go-ref-v}/opentracing.html[Go agent]
* {apm-java-ref-v}/opentracing-bridge.html[Java agent]
* {apm-node-ref-v}/opentracing.html[Node.js agent]
// * {apm-py-ref-v}/opentelemetry-bridge.html[Python agent]
* https://www.elastic.co/guide/en/apm/agent/python/6.x/opentelemetry-bridge.html[Python agent]
* {apm-ruby-ref-v}/opentracing.html[Ruby agent]
* {apm-rum-ref-v}/opentracing.html[JavaScript Real User Monitoring (RUM) agent]

Additionally, the iOS agent can utilize the https://github.com/open-telemetry/opentelemetry-swift/tree/main/Sources/Importers/OpenTracingShim[`opentelemetry-swift/OpenTracingShim`].
