ifndef::apm-integration-docs[]
["appendix",role="exclude",id="redirects"]
= Deleted pages
endif::[]

ifdef::apm-integration-docs[]
["appendix",role="exclude",id="legacy-apm-redirects"]
= Deleted pages
endif::[]

The following pages do not exist. They may have moved, been deleted, or have not been created yet.

[role="exclude",id="go-compatibility"]
=== Go Agent Compatibility

This page has moved. Please see <<agent-server-compatibility>>.

[role="exclude",id="java-compatibility"]
=== Java Agent Compatibility

This page has moved. Please see <<agent-server-compatibility>>.

[role="exclude",id="dotnet-compatibility"]
=== .NET Agent Compatibility

This page has moved. Please see <<agent-server-compatibility>>.

[role="exclude",id="nodejs-compatibility"]
=== Node.js Agent Compatibility

This page has moved. Please see <<agent-server-compatibility>>.

[role="exclude",id="python-compatibility"]
=== Python Agent Compatibility

This page has moved. Please see <<agent-server-compatibility>>.

[role="exclude",id="ruby-compatibility"]
=== Ruby Agent Compatibility

This page has moved. Please see <<agent-server-compatibility>>.

[role="exclude",id="rum-compatibility"]
=== RUM Agent Compatibility

This page has moved. Please see <<agent-server-compatibility>>.

[role="exclude",id="apm-release-notes"]
=== APM release highlights

This page has moved.
Please see {observability-guide}/whats-new.html[What's new in Observability {minor-version}].

Please see <<whats-new>>.

[role="exclude",id="whats-new"]
=== What's new in APM {minor-version}

This page has moved.
Please see {observability-guide}/whats-new.html[What's new in Observability {minor-version}].
