[[apm-release-notes]]
== Release highlights

This section summarizes the most important APM changes in each release.

For a full list of changes, see the
{apm-server-ref-v}/release-notes.html[APM Server Release Notes] or the
{kibana-ref}/release-notes.html[Kibana Release Notes].

* <<release-highlights-7.0.0>>
* <<release-notes-6.7.0>>
* <<release-notes-6.6.0>>
* <<release-notes-6.5.0>>
* <<release-notes-6.4.1>>
* <<release-notes-6.4.0>>


[[release-highlights-7.0.0]]
=== APM version 7.0.0

[float]
==== Breaking Changes

See <<breaking-7.0.0>>

[float]
==== New features

*APM UI*

* Added support for frozen indices.

[float]
==== Known issues

*APM UI*

* Links from APM to Infra may produce unexpected results due to a problem with the time range included in those links.
Fixed in 7.0.1.

[[release-notes-6.7.0]]
=== APM version 6.7.0

No new features.

[[release-notes-6.6.0]]
=== APM version 6.6.0

[float]
==== New features

* Elastic APM agents now automatically record certain <<metrics,infrastructure and application metrics>>.
* Elastic APM agents support the W3C Trace Context.
All agents now have <<opentracing,OpenTracing compatible bridges>>.
* <<distributed-tracing,Distributed tracing>> is generally available.

[[release-notes-6.5.0]]
=== APM version 6.5.0

[float]
==== New features

Elastic APM now enables {apm-overview-ref-v}/distributed-tracing.html[distributed tracing].

*APM Server*

* Intake protocol v2 with distributed tracing support
* Ingest node pipeline registration and use when ingesting documents
* apm-server monitoring

*APM UI*

* Distributed tracing UI
* Monitoring UI for apm-server

*APM agents*

* Intake protocol v2 with distributed tracing support in all Elastic agents
* Java is now GA
* Go is now GA
* Python switched to contextvars instead of thread locals for context tracking in Python 3.7
* Node added support for Restify Framework, dropped support for Node.js 4 and 9

[[release-notes-6.4.1]]
=== APM version 6.4.1

[float]
==== Bug Fixes
Changes introduced in 6.4.0 potentially caused an empty APM Kibana UI.
This happened in case the APM Server was using an outdated configuration file, not configured to index events into separate indices. 
To fix this, the APM Kibana UI now falls back to use `apm-*` as default indices to query.
Users can still leverage separate indices for queries by overriding the default values described in {kibana-ref}/apm-settings-kb.html[Kibana APM settings].


[[release-notes-6.4.0]]
=== APM version 6.4.0

[float]
==== Breaking changes

See <<breaking-6.4.0>>.

[float]
==== New features

*APM Server*

* Logstash output
* Kafka output


*APM UI*

* Query bar
* Machine Learning integration: Anomaly detection on service response times
* Kibana objects (index pattern, dashboards, etc.) can now be imported via the Kibana setup instructions


*APM agents*

* RUM is now GA
* Ruby is now GA
* Java is now Beta
* Go is now Beta
* Python added instrumentation for Cassandra, PyODBC and PyMSSQL
* Node.js added instrumentation for Cassandra and broader MySQL support
