[[doc-directory]]
== Documentation directory

The following sections are designed to guide you through the available Elastic APM documentation.

[float]
=== APM Overview

You're here!
The APM Overview is your launchpad for getting started with APM.
We recommend reading through this documentation to gain a deeper understanding of the Elastic APM ecosystem.

* <<overview>>
* <<install-and-run>>
* <<apm-data-model>>
* <<distributed-tracing>>
* <<agent-server-compatibility>>

TIP: Want to skip straight to installation?
Simply use an existing cluster or grab a fresh installation of the Elastic Stack,
spin up an APM Server, and add a bit of code to instrument your app with agents.
Full details are available on the <<install-and-run,install and run>> page.

[float]
=== APM Server

The APM Server receives data from APM agents and converts that data into Elasticsearch documents.
The {apm-server-ref-v}/index.html[APM Server reference] provides everything you need when it comes to working with the server.
Here you can learn about {apm-server-ref-v}/installing.html[installation],
{apm-server-ref-v}/configuring-howto-apm-server.html[configuration],
{apm-server-ref-v}/securing-apm-server.html[security],
{apm-server-ref-v}/monitoring.html[monitoring], and more.

[float]
=== APM Agents

APM agents are open source libraries that you install into your services.
You may only need one, or you might use all of them.
Each agent has its own documentation:

* {apm-go-ref}/introduction.html[Go agent]
* {apm-java-ref}/intro.html[Java agent]
* {apm-dotnet-ref-v}/intro.html[.NET agent]
* {apm-node-ref}/intro.html[Node.js agent]
* {apm-py-ref}/getting-started.html[Python agent]
* {apm-ruby-ref}/introduction.html[Ruby agent]
* {apm-rum-ref}/intro.html[JavaScript Real User Monitoring (RUM) agent]

[float]
=== APM Kibana UI

Application performance monitoring is all about visualizing data and detecting bottlenecks, so it's crucial you understand how to use the {kibana-ref}/xpack-apm.html[Kibana APM UI]. The following sections will help you get started:

* {kibana-ref}/apm-getting-started.html[Getting Started]
* {kibana-ref}/apm-bottlenecks.html[Visualizing application bottlenecks]
* {kibana-ref}/apm-ui.html[Using the APM UI]

APM also has built-in integrations with Machine Learning. To learn more about this feature, refer to the Kibana UI documentation for {kibana-ref}/machine-learning-integration.html[Machine learning integration].

TIP: If you'd like to dive deeper into Kibana, the general {kibana-ref}/index.html[Kibana documentation] is also helpful.

[float]
=== Troubleshooting

If you run into trouble, there are three places you can look for help:
Troubleshooting documentation, GitHub repositories, and our discussion forum.

[float]
==== Troubleshooting documentation

The APM Server and some of the APM agents have troubleshooting guides:

* {apm-server-ref-v}/troubleshooting.html[Server troubleshooting]
* {apm-java-ref}/trouble-shooting.html[Java agent troubleshooting]
* {apm-node-ref}/troubleshooting.html[Node.js agent troubleshooting]
* {apm-rum-ref}/troubleshooting.html[RUM troubleshooting]

[float]
==== GitHub repositories

Elastic APM is open source! Our https://github.com/elastic?utf8=%E2%9C%93&q=apm[GitHub repositories] have a plethora of knowledge available in the form of code, issues, and PRs.

[float]
==== Discussion forum

For additional questions and feature requests,
visit our https://discuss.elastic.co/c/apm[discussion forum].
