[[apm-data-model]]
== Data Model

Elastic APM agents capture different types of information from within their instrumented applications - namely `spans`, `transactions`, and `errors`. 

* <<transaction-spans>>
* <<transactions>>
* <<errors>>

[[transaction-spans]]
=== Spans

*Spans* contain information about a specific code path that has been executed.
They measure from the start to end of an activity,
and they can have a parent/child relationship with other spans.

Agents automatically instrument a variety of libraries to capture these spans from within your application.
In addition, you can use the Agent API for ad hoc instrumentation of specific code paths. 

Spans have a `transaction.id` attribute that refers to their parent <<transactions,transaction>>.
They also have a `parent.id` attribute that refers to their parent span, or their transaction.
Other span data includes:

* start time
* duration
* name
* type
* `stack trace` (optional)

Spans are stored in {apm-server-ref-v}/span-indices.html[span indices].
Note that these indices are separate from {apm-server-ref-v}/transaction-indices.html[transaction indices] by default.

[float]
[[dropped-spans]]
==== Dropped Spans

For performance reasons, some APM agents can choose to purposefully sample or omit spans.
One example of this might be for long running transactions with over 100 spans.
These edge cases can overload both the agent and the APM Server.
To avoid this, agents will drop spans. When they do this,
they notify the server of exactly how many spans were dropped.
This note is then passed on to the user in the UI.

Settings affecting dropped spans, and more details on why they might occur,
are available in the relevant agent documentation:

* {apm-node-ref}/configuration.html#transaction-max-spans[Node.js Agent max spans]
* {apm-py-ref}/configuration.html[Python Agent max spans]

[float]
[[missing-spans]]
==== Missing Spans

Similarly to dropped spans, transactions may have missing spans.
This can happen because spans are streamed from the APM Agent to the APM Server separately from their transaction.
Unforseen errors may cause spans to go missing.
Because the agent notifies the server about how many spans there should be,
the number of missing spans is able to be calculated and shown in the UI.

[[transactions]]
=== Transactions

*Transactions* are a special kind of <<transaction-spans,span>> that have additional attributes associated with them.
They describe an event captured by an Elastic APM agent instrumenting a service.
You can think of transactions as the highest level of work you’re measuring within a service.
As an example, a transaction might be a:

* request to your server
* batch job
* background job
* custom transaction type.

Agents decide whether to sample transactions or not,
and provide settings to control sampling behavior.
If sampled, the <<transaction-spans,spans>> of a transaction are sent and stored as separate documents.
Within one transaction there can be 0, 1, or many spans captured.

A transaction contains:

* The timestamp and duration of the event
* A unique id, type, and name
* A result (e.g. a response code)
* Some contextual data (see below for details)
* Other relevant information depending on the agent. Example: The JavaScript RUM captures transaction marks,
which are points in time relative to the start of the transaction with some label.

[[transactions-context]]
include::../context.asciidoc[]

Transactions are stored in {apm-server-ref-v}/transaction-indices.html[transaction indices].

[[errors]]
=== Errors

An error event contains at least
information about the original `exception` that occurred
or about a `log` created when the exception occurred.
For simplicity, errors are represented by a unique ID.

Error data includes:

* Both the captured `exception` and the captured `log` of an error can contain a `stack trace`,
which is helpful for debugging.
* The `culprit` of an error indicates where it originated.
* An error might relate to the <<transactions,transaction>> during which it happened,
via the `transaction.id`.
* Some contextual data (see below).

include::../context.asciidoc[]

Errors are stored in {apm-server-ref-v}/error-indices.html[error indices].
