[[kibana]]
[[apm-release-notes]]
== Release notes

[float]
=== APM version 7.0.0-beta

[float]
==== Breaking Changes

*APM Server*

* Removal of deprecated Intake v1 API endpoints.
* Move fields in Elasticsearch to be ECS compliant.

*APM UI*

* Moving to new data endpoints. We are filtering out 6.x or lower. 
We offer a Kibana Migration Assistant (in the Kibana Management section) to help you migrate your data. 
Be aware that this script is **not** supposed to be run on production data at this stage, as this is a beta release.

[float]
==== New features

*APM Server*

* Change ownership to apm-server user/group for deb/rpm installs.

*APM UI*

* Added support for frozen indices.


[float]
=== APM version 7.0.0-alpha2

No significant changes.

[float]
=== APM version 7.0.0-alpha1

No significant changes.

////
[float]
=== APM version 6.6.0
////

[float]
=== APM version 6.5.0

[float]
==== New features

Elastic APM now enables {apm-overview-ref-v}/distributed-tracing.html[distributed tracing].

*APM Server*

* Intake protocol v2 with distributed tracing support
* Ingest node pipeline registration and use when ingesting documents
* apm-server monitoring

*APM UI*

* Distributed tracing UI
* Monitoring UI for apm-server

*APM agents*

* Intake protocol v2 with distributed tracing support in all Elastic agents
* Java is now GA
* Go is now GA
* Python switched to contextvars instead of thread locals for context tracking in Python 3.7
* Node added support for Restify Framework, dropped support for Node.js 4 and 9

[float]
=== APM version 6.4.1

[float]
==== Bug Fixes
Changes introduced in 6.4.0 potentially caused an empty APM Kibana UI.
This happened in case the APM Server was using an outdated configuration file, not configured to index events into separate indices. 
To fix this, the APM Kibana UI now falls back to use `apm-*` as default indices to query.
Users can still leverage separate indices for queries by overriding the default values described in {kibana-ref}/apm-settings-kb.html[Kibana APM settings].


[float]
=== APM version 6.4.0

[float]
==== Breaking changes

We previously split APM data into separate indices (transaction, span, error, etc.).
In 6.4 APM Kibana UI starts to leverage those separate indices for queries.

In case you only update Kibana but run an older version of APM Server you will not be able to see any APM data by default.
To fix this, use the {kibana-ref}/apm-settings-kb.html[Kibana APM settings] to specify the location of the APM index:
["source","sh"]
------------------------------------------------------------
apm_oss.errorIndices: apm-*
apm_oss.spanIndices: apm-*
apm_oss.transactionIndices: apm-*
apm_oss.onboardingIndices: apm-*
------------------------------------------------------------

In case you are upgrading APM Server from an older version, you might need to refresh your APM index pattern for certain APM UI features to work.
Also ensure to add the new config options in `apm-server.yml` in case you keep your existing configuration file:
["source","sh"]
------------------------------------------------------------
output.elasticsearch:
  indices:
    - index: "apm-%{[observer.version]}-sourcemap"
      when.contains:
        processor.event: "sourcemap"
    - index: "apm-%{[observer.version]}-error-%{+yyyy.MM.dd}"
      when.contains:
        processor.event: "error"
    - index: "apm-%{[observer.version]}-transaction-%{+yyyy.MM.dd}"
      when.contains:
        processor.event: "transaction"
    - index: "apm-%{[observer.version]}-span-%{+yyyy.MM.dd}"
      when.contains:
        processor.event: "span"
    - index: "apm-%{[observer.version]}-metric-%{+yyyy.MM.dd}"
      when.contains:
        processor.event: "metric"
    - index: "apm-%{[observer.version]}-onboarding-%{+yyyy.MM.dd}"
      when.contains:
        processor.event: "onboarding"
------------------------------------------------------------

[float]
==== New features

*APM Server*

* Logstash output
* Kafka output


*APM UI*

* Query bar
* Machine Learning integration: Anomaly detection on service response times
* Kibana objects (index pattern, dashboards, etc.) can now be imported via the Kibana setup instructions


*APM agents*

* RUM is now GA
* Ruby is now GA
* Java is now Beta
* Go is now Beta
* Python added instrumentation for Cassandra, PyODBC and PyMSSQL
* Node.js added instrumentation for Cassandra and broader MySQL support
