[[doc-directory]]
== Documentation directory

This page is designed to guide you through the available Elastic APM documentation. The links provided below are helpful to understanding and adapting the product to your specific needs.

[float]
=== APM Overview

The APM Overview is your launchpad for getting started with APM. After <<install-and-run,installing and running Elastic APM>>, we recommend reading the following topics to gain a deeper understanding of how Elastic APM works:

* <<concepts,Concepts>>
* <<apm-data-model,Data model>>
* <<distributed-tracing,Distributed tracing>>

[float]
=== APM Server

The {apm-server-ref-v}/index.html[APM Server reference] provides everything you need when it comes to working with the server. Here you can learn about installation, configuration, security, monitoring, and more.

[float]
=== APM Agents

For agent specific documentation, visit the relevant agent reference:

* {apm-go-ref}/introduction.html[Go agent]
* {apm-java-ref}/intro.html[Java agent]
* {apm-node-ref}/intro.html[Node.js agent]
* {apm-py-ref}/getting-started.html[Python agent]
* {apm-ruby-ref}/introduction.html[Ruby agent]
* {apm-rum-ref}/intro.html[JavaScript Real User Monitoring (RUM) agent]

[float]
=== APM Kibana UI

Application performance monitoring is all about visualizing data and bottlenecks, so it's crucial you understand how to use the APM Kibana UI. The following sections will help you get started:

* {kibana-ref}/xpack-apm.html[APM UI]
** {kibana-ref}/apm-getting-started.html[Getting Started]
** {kibana-ref}/apm-bottlenecks.html[Visualizing application bottlenecks]
** {kibana-ref}/apm-ui.html[Using the APM UI]

In addition, the Kibana UI documentation includes information on Machine Learning integration, Watcher alerts, and other useful tips and tricks.

TIP: If you'd like to dive deeper into Kibana, the general Kibana documentation is also accessible via any of the above links. 

[float]
=== Discussion forum

For questions and feature requests,
visit our https://discuss.elastic.co/c/apm[discussion forum].

[float]
=== GitHub repositories

Elastic APM is open source! Our https://github.com/elastic?utf8=%E2%9C%93&q=apm[GitHub repositories] have a plethora of knowledge available in the form of code, issues, and PRs. 