[[install-and-run]]
== Install and run

This page is designed to make it easy to install and run the components of Elastic APM.
Simply follow the step-by-step links below, and you'll be up and running in no time.
Let's get started.

[TIP]
==============
You can skip having to install {es}, {kib}, and APM Server by using our
https://www.elastic.co/cloud/elasticsearch-service[hosted {es} Service] on
Elastic Cloud. The {es} Service is available on both AWS and GCP,
and automatically configures APM Server to work with {es} and {kib}.
Additional {cloud}/ec-manage-apm-settings.html[APM user settings] are also available.

https://www.elastic.co/cloud/elasticsearch-service/signup[Try out the {es}
Service for free].
==============

* <<before-installation>>
* <<install-elasticsearch>>
* <<install-kibana>>
* <<apm-server>>
* <<agents>>

[float]
[[before-installation]]
=== Before you begin

* See the https://www.elastic.co/support/matrix[Elastic Support Matrix]
for information about supported operating systems and product compatibility.
We recommend you use the same version of Elasticsearch, Kibana, and APM Server.
* Verify that your system meets the
https://www.elastic.co/support/matrix#matrix_jvm[minimum JVM requirements] for {es}.
* The following links assume you're using the current version of the Elastic Stack.
If you're not, it's easy to adjust the version of the documentation after you land on each page.

[float]
[[install-elasticsearch]]
=== Install and run Elasticsearch

You'll need to install an Elasticsearch cluster, and make sure it's up and running:

* {stack-gs}/get-started-elastic-stack.html#install-elasticsearch[Install Elasticsearch]
* {stack-gs}/get-started-elastic-stack.html#_make_sure_elasticsearch_is_up_and_running[Make sure elasticsearch is up and running]

[float]
[[install-kibana]]
=== Install and run Kibana

Now we'll install Kibana and open up the web interface:

* {stack-gs}/get-started-elastic-stack.html#install-kibana[Install Kibana]
* {stack-gs}/get-started-elastic-stack.html#_launch_the_kibana_web_interface[Launch the Kibana Web Interface]

[[apm-server]]
[float]
=== Install and run APM Server

You've made it to the fun part - Let's get APM Server up and running:

* {apm-server-ref-v}/installing.html[Install APM Server]
* {apm-server-ref-v}/setting-up-and-running.html[Set up and Run APM Server]

Use the config file if you need to change the default configuration that APM Server uses to connect to Elasticsearch,
or if you need to specify credentials:

* {apm-server-ref-v}/configuring-howto-apm-server.html[Configuring APM Server]
** {apm-server-ref-v}/configuration-process.html[General configuration options]
** {apm-server-ref-v}/elasticsearch-output.html[Configure the Elasticsearch output]

[[secure-api-access]]
If you do change the listen address from `localhost` to something that is accessible from outside of the machine,
we recommend setting up firewall rules to ensure that only your own systems can access the API.
Alternatively,
you can use a {apm-server-ref-v}/securing-apm-server.html[secret token and TLS].

If you have APM Server running on the same host as your service,
you can configure it to listen on a Unix domain socket.

[[more-information]]
TIP: For detailed instructions on how to install and secure APM Server in your server environment,
including details on how to run APM Server in a highly available environment,
please see the full {apm-server-ref-v}/index.html[APM Server documentation].

[[agents]]
[float]
=== Install and configure APM agents

Agents are written in the same language as your service.
Currently Elastic APM has agents for Go, Java, .NET, Node.js, Python, Ruby, and JavaScript RUM.

// todo: fix this sentence
Setting up a new service to be monitored requires installing the agent,
and configuring it with the address of your APM Server and the service name.

NOTE: Check the <<agent-server-compatibility,Agent/Server compatibility matrix>> to ensure you're using agents that are compatible with your version of Elasticsearch.

[cols="h,,,"]
|=======================================================================
|Agent
3+| More information

.2+|Go
3+|The Go agent automatically instruments Gorilla and Gin, and has support for Go’s built-in net/http and database/sql drivers.
|{apm-go-ref}/introduction.html[Introduction]
|{apm-go-ref}/supported-tech.html[Supported technologies]
|{apm-go-ref}/configuration.html[Config]

.2+|Java
3+|The Java agent automatically instruments Servlet API, Spring MVC, and Spring Boot out of the box.
|{apm-java-ref}/intro.html[Introduction]
|{apm-java-ref}/supported-technologies-details.html[Supported technologies]
|{apm-java-ref}/configuration.html[Config]

.2+|.NET
3+|The .NET agent automatically instruments ASP.NET Core applications, while .NET Framework applications can be instrumented with the public API.
|{apm-dotnet-ref-v}/intro.html[Introduction]
|
|{apm-dotnet-ref-v}/configuration.html[Config]

.2+|Node.js
3+|The Node.js agent automatically instruments Express, hapi, Koa, and Restify out of the box.
|{apm-node-ref}/intro.html[Introduction]
|{apm-node-ref}/supported-technologies.html[Supported technologies]
|{apm-node-ref}/configuring-the-agent.html[Config]

.2+|Python
3+|The Python agent automatically instruments Django and Flask out of the box.
|{apm-py-ref}/getting-started.html[Getting Started]
|{apm-py-ref}/supported-technologies.html[Supported technologies]
|{apm-py-ref}/configuration.html[Config]

.2+|Ruby
3+|The Ruby agent automatically instruments Rails out of the box.
|{apm-ruby-ref}/introduction.html[Introduction]
|{apm-ruby-ref}/supported-technologies.html[Supported technologies]
|{apm-ruby-ref}/configuration.html[Config]

.2+|RUM
3+|Real User Monitoring (RUM) captures user interactions with clients such as web browsers.
|{apm-rum-ref}/intro.html[Introduction]
|{apm-rum-ref}/supported-technologies.html[Supported technologies]
|{apm-rum-ref}/configuration.html[Config]
|=======================================================================

[[choose-service-name]]
[float]
==== Choose a service name

The service name is used by Elastic APM to differentiate between data coming from different services.

Elastic APM includes the service name field on every document that it saves in Elasticsearch.
If you change the service name after using Elastic APM,
you will see the old service name and the new service name as two separate services.
Make sure you choose a good service name before you get started.

The service name can only contain alphanumeric characters,
spaces, underscores, and dashes (must match `^[a-zA-Z0-9 _-]+$`).

[float]
=== Next steps

You're now up and running with Elastic APM!
Don't forget to check out the <<concepts>> and <<apm-data-model>> documentation to gain a deeper understanding of how Elastic APM works. 
