[[overview]]
== Overview

Elastic APM is an application performance monitoring system built on the Elastic Stack.
It allows you to monitor software services and applications in real time,
collecting detailed performance information on response time for incoming requests,
database queries, calls to caches, external HTTP requests,
etc.
This makes it easier to pinpoint and fix performance problems quickly.

Elastic APM also automatically collects unhandled errors and exceptions.
Errors are grouped based primarily on the stacktrace,
so you can identify new errors as they appear and keep an eye on how many times specific errors happen. 

NOTE: This guide will indiscriminately use the word "service" for both services and applications.

Gain a deeper understanding of the Elastic APM ecosystem by reading the following topics:

* <<components>>
* <<install-and-run>>
* <<apm-data-model>>
* <<distributed-tracing>>
* <<rum>>
* <<opentracing>>
* <<agent-server-compatibility>>
* <<troubleshooting>>
