[[configure-agent-config]]
= Configure APM agent configuration

++++
<titleabbrev>APM agent configuration</titleabbrev>
++++

****
image:./binary-yes-fm-yes.svg[supported deployment methods]

APM agent configuration is supported by all APM Server deployment methods.
****

APM agent configuration allows you to fine-tune your APM agents from within the APM app.
Changes are automatically propagated to your APM agents, so there's no need to redeploy your applications.

To learn more about this feature, see {kibana-ref}/agent-configuration.html[APM agent configuration].

Here's a sample configuration:

[source,yaml]
----
apm-server.agent.config.cache.expiration: 45s
apm-server.agent.config.elasticsearch.api_key: TiNAGG4BaaMdaH1tRfuU:KnR6yE41RrSowb0kQ0HWoA
----

[float]
= APM agent configuration options

The following options are only supported for APM Server binary users.
You can specify these options in the `apm-server.agent.config` section of the
+{beatname_lc}.yml+ config file:

[float]
[[agent-config-cache]]
== `apm-server.agent.config.cache.expiration`

When using APM agent configuration, information fetched from {es} will be cached in memory for some time.
Specify the cache expiration time via this setting. Defaults to `30s` (30 seconds).

[float]
[[agent-config-elasticsearch]]
== `apm-server.agent.config.elasticsearch`

Takes the same options as <<elasticsearch-output,output.elasticsearch>>.

For APM Server binary users and Elastic Agent standalone-managed APM Server,
APM agent configuration is automatically fetched from {es} using the `output.elasticsearch`
configuration. If `output.elasticsearch` isn't set or doesn't have sufficient privileges,
use these {es} options to provide {es} access.

[float]
== Common problems

You may see either of the following HTTP 403 errors from APM Server when it attempts to fetch APM agent configuration:

APM agent log:

[source,log]
----
"Your Elasticsearch configuration does not support agent config queries. Check your configurations at `output.elasticsearch` or `apm-server.agent.config.elasticsearch`."
----

APM Server log:

[source,log]
----
rejecting fetch request: no valid elasticsearch config
----

This occurs because the user or API key set in either `apm-server.agent.config.elasticsearch` or `output.elasticsearch`
(if `apm-server.agent.config.elasticsearch` is not set) does not have adequate permissions to read source maps from {es}.

To fix this error, add the following index-level privileges to the API key:

* `read` privileges on the `.apm-agent-configuration` index
* `allow_restricted_indices: true`
