[[apm-agent-auth]]
= APM agent authorization

****
image:./binary-yes-fm-yes.svg[supported deployment methods]

Most options in this section are supported by all APM Server deployment methods.
****

Agent authorization APM Server configuration options.

include::./tab-widgets/auth-config-widget.asciidoc[]

[float]
[[api-key-auth-settings]]
= API key authentication options

These settings apply to API key communication between the APM Server and APM Agents.

NOTE: These settings are different from the API key settings used for {es} output and monitoring.

[float]
== API key for agent authentication

Enable API key authorization by setting `enabled` to `true`.
By default, `enabled` is set to `false`, and API key support is disabled. (bool)

|====
| APM Server binary | `auth.api_key.enabled`
| Fleet-managed     | `API key for agent authentication`
|====

TIP: Not using Elastic APM agents?
When enabled, third-party APM agents must include a valid API key in the following format:
`Authorization: ApiKey <token>`. The key must be the base64 encoded representation of the API key's `id:name`.

[float]
== API key limit

Each unique API key triggers one request to {es}.
This setting restricts the number of unique API keys are allowed per minute.
The minimum value for this setting should be the number of API keys configured in your monitored services.
The default `limit` is `100`. (int)

|====
| APM Server binary | `auth.api_key.limit`
| Fleet-managed     | `Number of keys`
|====

[float]
== Secret token

Authorization token for sending APM data.
The same token must also be set in each {apm-agent}.
This token is not used for RUM endpoints. (text)

|====
| APM Server binary | `auth.api_key.token`
| Fleet-managed     | `Secret token`
|====

[float]
= `auth.api_key.elasticsearch.*` configuration options

****
image:./binary-yes-fm-no.svg[supported deployment methods]

The below options are only supported by the APM Server binary.

All of the `auth.api_key.elasticsearch.*` configurations are optional.
If none are set, configuration settings from the `apm-server.output` section will be reused.
****

[float]
== `elasticsearch.hosts`

API keys are fetched from {es}.
This configuration needs to point to a secured {es} cluster that is able to serve API key requests.


[float]
== `elasticsearch.protocol`

The name of the protocol {es} is reachable on.
The options are: `http` or `https`. The default is `http`.
If nothing is configured, configuration settings from the `output` section will be reused.

[float]
== `elasticsearch.path`

An optional HTTP path prefix that is prepended to the HTTP API calls.
If nothing is configured, configuration settings from the `output` section will be reused.

[float]
== `elasticsearch.proxy_url`

The URL of the proxy to use when connecting to the {es} servers.
The value may be either a complete URL or a "host[:port]", in which case the "http"scheme is assumed.
If nothing is configured, configuration settings from the `output` section will be reused.

[float]
== `elasticsearch.timeout`

The HTTP request timeout in seconds for the {es} request.
If nothing is configured, configuration settings from the `output` section will be reused.

[float]
= `auth.api_key.elasticsearch.ssl.*` configuration options

SSL is off by default. Set `elasticsearch.protocol` to `https` if you want to enable `https`.

[float]
== `elasticsearch.ssl.enabled`

Enable custom SSL settings.
Set to false to ignore custom SSL settings for secure communication.

[float]
== `elasticsearch.ssl.verification_mode`

Configure SSL verification mode.
If `none` is configured, all server hosts and certificates will be accepted.
In this mode, SSL based connections are susceptible to man-in-the-middle attacks.
**Use only for testing**. Default is `full`.

[float]
== `elasticsearch.ssl.supported_protocols`

List of supported/valid TLS versions.
By default, all TLS versions from 1.0 to 1.2 are enabled.

[float]
== `elasticsearch.ssl.certificate_authorities`

List of root certificates for HTTPS server verifications.

[float]
== `elasticsearch.ssl.certificate`

The path to the certificate for SSL client authentication.

[float]
== `elasticsearch.ssl.key`

The client certificate key used for client authentication.
This option is required if certificate is specified.

[float]
== `elasticsearch.ssl.key_passphrase`

An optional passphrase used to decrypt an encrypted key stored in the configured key file.

[float]
== `elasticsearch.ssl.cipher_suites`

The list of cipher suites to use. The first entry has the highest priority.
If this option is omitted, the Go crypto library’s default suites are used (recommended).

[float]
== `elasticsearch.ssl.curve_types`

The list of curve types for ECDHE (Elliptic Curve Diffie-Hellman ephemeral key exchange).

[float]
== `elasticsearch.ssl.renegotiation`

Configure what types of renegotiation are supported.
Valid options are `never`, `once`, and `freely`. Default is `never`.

* `never` - Disables renegotiation.
* `once` - Allows a remote server to request renegotiation once per connection.
* `freely` - Allows a remote server to repeatedly request renegotiation.
