[role="xpack"]
[[feature-roles]]
== Grant users access to secured resources

You can use role-based access control to grant users access to secured
resources. The roles that you set up depend on your organization's security
requirements and the minimum privileges required to use specific features.

Typically, you need to create the following separate roles:

* <<privileges-to-setup-beats,Setup role>>, for setting up index templates and
other dependencies.
* <<privileges-to-publish-monitoring,Monitoring role>>, one for sending monitoring
information, and another for viewing it.
* <<privileges-to-publish-events,Writer role>>, for publishing events collected
by {beatname_uc}.
* <<kibana-user-privileges,Reader roles>>, for {kib} users who need to view the APM app,
or create and edit visualizations that access +{beat_default_index_prefix}-*+ data.
* <<privileges-agent-central-config,Central config management roles>>, for viewing, creating, updating, and deleting
APM Agent central configurations.
* Various <<privileges-apm-app-api,APM app API roles>>, for interacting with the APIs exposed by the APM app.

{es-security-features} provides {ref}/built-in-roles.html[built-in roles] that grant a
subset of the privileges needed by APM users.
When possible, use the built-in roles to minimize the affect of future changes on your security strategy.
If no built-in role is available, you can create a custom user and assign
them the privileges needed to accomplish a specific task.
In general, there are three types of privileges you'll work with:

* **Elasticsearch cluster privileges**: Manage the actions a user can perform against your cluster.
* **Elasticsearch index privileges**: Control access to the data in specific indices your cluster.
* **Kibana space privileges**: Grant users write or read access to features and apps within Kibana.

////
***********************************  ***********************************
***********************************  ***********************************
////

[[privileges-to-setup-beats]]
=== Grant privileges and roles needed for setup

++++
<titleabbrev>Create a _setup_ user</titleabbrev>
++++

IMPORTANT: Setting up {beatname_uc} is an admin-level task that requires extra
privileges. As a best practice, grant the setup role to administrators only, and
use a more restrictive role for event publishing.

Administrators who set up {beatname_uc} typically need to load the index template,
set up ILM aliases, templates and policies, and register ingest pipelines.

To grant users the required privileges for setup:

. Create a *setup role*, called something like +{beat_default_index_prefix}_setup+, that has
the following privileges:
+
[options="header"]
|====
|Type | Privilege | Purpose

|Cluster
|`manage_ilm`
|All index lifecycle management operations related to managing policies

|Index
|`manage` on +{beat_default_index_prefix}-*+ indices
|All index administration privileges
|====

. Assign the *setup role*, along with the following built-in roles, to users who
need to set up {beatname_uc}:
+
[options="header"]
|====
|Role | Purpose

|`ingest_admin`
|Set up index templates and ingest pipelines
|====

NOTE: These instructions assume that you are using the default name for
{beatname_uc} indices (+{beat_default_index_prefix}-*+).
If you are using a custom index name, modify the privileges to
match your index naming pattern.

[float]
==== Partial setup

If you've previously set up {beatname_uc} and only need to preform a partial set up,
you can find the minimum required privileges for all setup tasks in the tables below:

[float]
===== Set up index templates

[options="header"]
|====
|Type | Privilege | Purpose

|Cluster
|`manage_index_template`
|All operations on index templates
|====

See <<configuration-template>> for more information.

[float]
===== Set up ILM

[options="header"]
|====
|Type | Privilege | Purpose

|Cluster
|`manage_index_template`
|All operations on index templates

|Cluster
|`manage_ilm`
|All index lifecycle management operations related to managing policies.

|Index
|`manage` on +{beat_default_index_prefix}-*+ indices
|All index administration privileges
|====

See <<ilm-reference>> for more information.

[float]
===== Set up ingest pipelines

[options="header"]
|====
|Type | Privilege | Purpose

|Cluster
|`manage_pipeline`
|All operations on ingest pipelines
|====

See <<pipeline-option-es>> for more information.

////
***********************************  ***********************************
***********************************  ***********************************
////

[[privileges-to-publish-events]]
=== Grant privileges and roles needed for writing events

++++
<titleabbrev>Create a _writer_ user</titleabbrev>
++++

IMPORTANT: To minimize the privileges required by the writer role, use the
<<privileges-to-setup-beats,setup role>> to pre-load dependencies. This section
assumes that you've pre-loaded dependencies.

{beatname_uc} users that publish events to {es} need to create and write to +{beat_default_index_prefix}-*+
indices, upload and read sourcemaps, read API keys from Elasticsearch, and perform self-instrumentation.

[float]
==== General writer role

To grant an APM Server user the required privileges for writing to {es}:

. Create a *general writer role*, called something like +{beat_default_index_prefix}_writer+,
that has the following privileges:
+
[options="header"]
|====
|Type | Privilege | Purpose

|Index
|`create_doc` on +{beat_default_index_prefix}-*+ indices
|Write events into {es}

|Index
|`create_index` on +{beat_default_index_prefix}-*+ indices
|Create APM indices in {es}

|Index
|`read` on +{beat_default_index_prefix}-*sourcemap+ indices
|Read sourcemaps from {es}
|====

. Assign the *general writer role* to users who need to publish {beatname_uc} data.

[float]
==== Specific writer roles

Instead of creating a *general writer role*,
individual publishing tasks, like writing events or uploading sourcemaps,
can be performed by dedicated users with stricter privileges.

[float]
===== Event writer role

To create an {beatname_uc} user that can publish APM Agent data to {es}:

. Create a *event writer role*, called something like +{beat_default_index_prefix}_event_writer+,
that has the following privileges:
+
[options="header"]
|====
|Type | Privilege | Purpose

|Index
|`create_doc` on +{beat_default_index_prefix}-*+ indices
|Write APM events into {es}

|Index
|`create_index` on +{beat_default_index_prefix}-*+ indices
|Create APM indices in {es}

|Index
|`read` on +{beat_default_index_prefix}-*sourcemap+ indices
|Read sourcemaps
|====

. Assign the *event writer role* to users who need to publish APM Agent data.

[float]
===== Sourcemap writer role

To create an {beatname_uc} user that can write sourcemaps to {es}:

. Create a *sourcemap writer role*, called something like +{beat_default_index_prefix}_sourcemap+,
that has the following privileges:
+
[options="header"]
|====
|Type | Privilege | Purpose

|Index
|`create_doc` on +{beat_default_index_prefix}-*+ indices
|Write APM events into {es}

|Index
|`create_index` on +{beat_default_index_prefix}-*+ indices
|Create APM indices in {es}
|====

. Assign the *sourcemap writer role* to users who need to publish sourcemaps.

////
***********************************  ***********************************
***********************************  ***********************************
////

[[privileges-to-publish-monitoring]]
=== Grant privileges and roles needed for monitoring

++++
<titleabbrev>Create a _monitoring_ user</titleabbrev>
++++

{es-security-features} provides built-in users and roles for publishing and viewing monitoring data.
The privileges and roles needed to publish monitoring data
depend on the method used to collect that data.

* <<privileges-to-publish-monitoring-write>>
** <<privileges-to-publish-monitoring-internal>>
** <<privileges-to-publish-monitoring-metricbeat>>
* <<privileges-to-publish-monitoring-view>>

[float]
[[privileges-to-publish-monitoring-write]]
==== Publish monitoring data

[IMPORTANT]
====
**{ecloud} users:** This section does not apply to our
https://www.elastic.co/cloud/elasticsearch-service[hosted {ess}].
Monitoring on {ecloud} is enabled by clicking the *Enable* button in the *Monitoring* panel.
====

[float]
[[privileges-to-publish-monitoring-internal]]
===== Internal collection

If you're using <<monitoring-internal-collection,internal collection>> to
collect metrics about {beatname_uc}, {security-features} provides
the +{beat_monitoring_user}+ {ref}/built-in-users.html[built-in user] and
+{beat_monitoring_user}+ {ref}/built-in-roles.html[built-in role] to send
monitoring information. You can use the built-in user, if it's available in your
environment, or create a user who has the privileges needed to send monitoring
information.

If you use the built-in +{beat_monitoring_user}+ user,
make sure you set the password before assigning it to users that need to write monitoring data to {es}.

If you don't use the +{beat_monitoring_user}+ user:

--
. Create a *monitoring role*, called something like
+{beat_default_index_prefix}_monitoring_writer+, that has the following privileges:
+
[options="header"]
|====
|Type | Privilege | Purpose

|Index
|`create_index` on `.monitoring-beats-*` indices
|Create monitoring indices in {es}

|Index
|`create_doc` on `.monitoring-beats-*` indices
|Write monitoring events into {es}
|====
+
. Assign the *monitoring role* to users who need to write monitoring data to {es}.
--

[float]
[[privileges-to-publish-monitoring-metricbeat]]
===== Metricbeat collection

If you're <<monitoring-metricbeat-collection,using {metricbeat}>> to collect
metrics about {beatname_uc}, {security-features} provides the `remote_monitoring_user`
{ref}/built-in-users.html[built-in user], and the `remote_monitoring_collector`
and `remote_monitoring_agent` {ref}/built-in-roles.html[built-in roles] for
collecting and sending monitoring information. You can use the built-in user, if
it's available in your environment, or create a user who has the privileges
needed to collect and send monitoring information.

If you use the built-in `remote_monitoring_user` user,
make sure you set the password before assigning it to users that need to write monitoring data to {es}.

If you don't use the `remote_monitoring_user` user:

--
. Create a *monitoring user* on the production cluster who will collect and send monitoring
information. Assign the following roles to the *monitoring user*:
+
[options="header"]
|====
|Role | Purpose

|`remote_monitoring_collector`
|Collect monitoring metrics from {beatname_uc}

|`remote_monitoring_agent`
|Send monitoring data to the monitoring cluster
|====

TIP: See <<monitoring-metricbeat-collection>>
for complete details on setting up Metricbeat collection.
--

[float]
[[privileges-to-publish-monitoring-view]]
==== View monitoring data

To grant users the required privileges for viewing monitoring data:

. Create a *monitoring role*, called something like
+{beat_default_index_prefix}_monitoring_viewer+, that has the following privileges:
+
[options="header"]
|====
|Type | Privilege | Purpose

| Spaces
|`Read` on Stack monitoring
|Read-only access to the Stack Monitoring feature in {kib}.

| Spaces
|`Read` on Dashboards
|Read-only access to the Dashboards feature in {kib}.
|====
+
. Assign the *monitoring role*, along with the following built-in roles, to users who
need to view monitoring data for {beatname_uc}:
+
[options="header"]
|====
|Role | Purpose

|`monitoring_user`
|Grants access to monitoring indices for {beatname_uc}
|====

////
***********************************  ***********************************
***********************************  ***********************************
////

[[kibana-user-privileges]]
=== Grant privileges and roles needed to read APM data in {kib}

++++
<titleabbrev>Create a _reader_ user</titleabbrev>
++++

{kib} users typically need to view apps, dashboards, and visualizations that contain
APM data. These users might also need to create and edit dashboards, visualizations, and machine learning jobs.

To grant users the required privileges:

. Assign the following built-in roles to users who need to read APM data:
+
[options="header"]
|====
|Role | Purpose

|`kibana_user`
|Use the APM UI

|`apm_user`
|Use the APM UI
|====
+
. If you're using any of the APM, Dashboard, Visualize, Discover, etc., apps,
you'll need assign space privileges:
+
[options="header"]
|====
|Type | Privilege | Purpose

| Spaces
| `Read` or `All` on {beat_kib_app}
| Allow the use of the {beat_kib_app}

| Spaces
| `Read` or `All` on Dashboards, Visualize, and Discover
| Allow the user to view, edit, and create dashboards, as well as browse data.
|====
+
. Finally, assign the following role if a user needs to enable and edit machine learning features:
+
[options="header"]
|====
|Role | Purpose

|`machine_learning_admin`
|NEED DESCRIPTION
|====

////
***********************************  ***********************************
***********************************  ***********************************
////

[[privileges-agent-central-config]]
=== Grant privileges and roles needed for APM Agent central configuration

++++
<titleabbrev>Create a _central config_ user</titleabbrev>
++++

[[privileges-agent-central-config-server]]
==== APM Server central configuration management

[options="header"]
|====
|Type | Privilege | Purpose

| Spaces
|`Read` on {beat_kib_app}
|Allow the use of the {beat_kib_app}
|====

[[privileges-agent-central-config-kib]]
==== Kibana central configuration management

. If you're using APM Agent configuration, create a user with the following built-in roles:
+
[options="header"]
|====
|Role | Purpose

|`apm_user`
|Read and update APM Agent configuration via {kib}
|====
+
. The user will also need Kibana space access:
+
[options="header"]
|====
|Type | Privilege | Purpose

| Spaces
|`All` on {beat_kib_app}
|Allow the use of the {beat_kib_app}
|====

TIP: Looking for privileges and roles needed for the central configuration
API? See <<privileges-agent-central-config-api>>.

////
***********************************  ***********************************
***********************************  ***********************************
////

// [[privileges-create-api-keys]]
// === Grant privileges and roles needed to create APM Server API keys

// ++++
// <titleabbrev>Create an _APM API key_ user</titleabbrev>
// ++++

// CONTENT

////
***********************************  ***********************************
***********************************  ***********************************
////

[[privileges-apm-app-api]]
=== Grant privileges and roles needed for APM app APIs

++++
<titleabbrev>Create an _APM app API_ user</titleabbrev>
++++

[[privileges-apm-app-annotation-api]]
==== Annotation API

. Create a user with the following privileges:
+
[options="header"]
|====
|Type | Privilege | Purpose

|Index
|`create_doc` on +observability-annotations+ indices
|Write events into {es}

|Index
|`create_index` on +observability-annotations+ indices
|Create the indices

|Index
|`manage` on +observability-annotations+ indices
|Manage the indices

|Index
|`read` on +observability-annotations+ indices
|Read the indices
|====
+
. The user will also need Kibana space access:
+
[options="header"]
|====
|Type | Privilege | Purpose

| Spaces
|`All` on {beat_kib_app}
|Allow the use of the {beat_kib_app}
|====

[[privileges-agent-central-config-api]]
==== Central configuration management API

. To list and search for Agent configurations, create a user with the following privileges:
+
[options="header"]
|====
|Type | Privilege | Purpose

| Spaces
|`Read` on {beat_kib_app}
|Allow the use of the {beat_kib_app}
|====
+
. To create or delete Agent configurations, create a user with the following privileges:
+
[options="header"]
|====
|Type | Privilege | Purpose

| Spaces
|`All` on {beat_kib_app}
|Allow the use of the {beat_kib_app}
|====

////
***********************************  ***********************************
***********************************  ***********************************
////

[[learn-more-security]]
=== Learn more about users and roles

Want to learn more about creating users and roles? See
{ref}/secure-cluster.html[Secure a cluster]. Also see:

* {ref}/security-privileges.html[Security privileges] for a description of
available privileges
* {ref}/built-in-roles.html[Built-in roles] for a description of roles that
you can assign to users
