[role="xpack"]
[[feature-roles]]
== Grant users access to secured resources

You can use role-based access control to grant users access to secured
resources. The roles that you set up depend on your organization's security
requirements and the minimum privileges required to use specific features.

{security-features} provides {ref}/built-in-roles.html[built-in roles] that grant a
subset of the privileges needed by {beatname_uc} users. When possible, use the
built-in roles to minimize the affect of future changes on your security
strategy.

For other roles, you'll need to grant the privileges necessary to achieve each task.
In general, there are three types of privileges:

* **Elasticsearch cluster privileges**: Manage the actions a role can perform against your cluster.
* **Elasticsearch index privileges**: Control access to the data in specific indices your cluster.
* **Kibana space privileges**: Grant users write or read access to features within Kibana.

Typically you need to create the following separate roles:

* <<privileges-to-setup-beats,setup role>> for setting up index templates and
other dependencies
* <<privileges-to-publish-monitoring,monitoring role>> for sending monitoring
information
* <<privileges-to-publish-events,writer role>>  for publishing events collected
by {beatname_uc}
* <<kibana-user-privileges,reader role>> for {kib} users who need to view and
create visualizations that access {beatname_uc} data

////
***********************************  ***********************************
***********************************  ***********************************
////

[[privileges-to-setup-beats]]
=== Grant privileges and roles needed for setup

++++
<titleabbrev>Create a _setup_ user</titleabbrev>
++++

IMPORTANT: Setting up {beatname_uc} is an admin-level task that requires extra
privileges. As a best practice, grant the setup role to administrators only, and
use a more restrictive role for event publishing.

Administrators who set up {beatname_uc} typically need to load mappings,
dashboards, and other objects used to index data into {es} and visualize it in
{kib}.

To grant users the required privileges for setup:

. Create a *setup role*, called something like +{beat_default_index_prefix}_setup+, that has
the following privileges:
+
[options="header"]
|====
|Type | Privilege | Purpose

|Cluster
|`manage_ilm`
|Set up and manage index lifecycle management (ILM) policy

|Index
|`manage` on +{beat_default_index_prefix}-*+ indices
|Set up aliases used by ILM
|====

. Assign the *setup role*, along with the following built-in roles, to users who
need to set up {beatname_uc}:
+
[options="header"]
|====
|Role | Purpose

|`ingest_admin`
|Set up index templates and, if available, ingest pipelines
|====

NOTE: These instructions assume that you are using the default name for
{beatname_uc} indices (+{beat_default_index_prefix}-*+).
If you are using a custom index name, modify the privileges to
match your index naming pattern.

[float]
==== Partial setup

Only need to setup a specific feature?
To grant users the required privileges for a partial set up,
find the relevant feature in the table below:

[float]
===== Set up index templates

[options="header"]
|====
|Type | Privilege | Purpose

|Cluster
|`manage_index_template`
| NEED DESCRIPTION
|====

[float]
===== Set up ILM

[options="header"]
|====
|Type | Privilege | Purpose

|Cluster
|`manage_index_template`
| NEED DESCRIPTION

|Cluster
|`manage_ilm`
|Set up and manage index lifecycle management (ILM) policy

|Index
|`manage` on +{beat_default_index_prefix}-*+ indices
|Set up aliases used by ILM
|====

[float]
===== Set up ingest pipelines

[options="header"]
|====
|Type | Privilege | Purpose

|Cluster
|`manage_pipeline`
| NEED DESCRIPTION
|====

////
***********************************  ***********************************
***********************************  ***********************************
////

[[privileges-to-publish-monitoring]]
=== Grant privileges and roles needed for monitoring

++++
<titleabbrev>Create a _monitoring_ user</titleabbrev>
++++

{es-security-features} provides built-in users and roles for publishing and viewing monitoring data.

* <<privileges-to-publish-monitoring-write>>
** <<privileges-to-publish-monitoring-internal>>
** <<privileges-to-publish-monitoring-metricbeat>>
* <<privileges-to-publish-monitoring-view>>

[float]
[[privileges-to-publish-monitoring-write]]
==== Publish monitoring data

[IMPORTANT]
====
**{ecloud} users:** This section does not apply to our
https://www.elastic.co/cloud/elasticsearch-service[hosted {ess}].
Monitoring on {ecloud} is enabled by clicking the *Enable* button in the *Monitoring* panel.
====

The privileges and roles needed to publish monitoring data
depend on the method used to collect that data.

[float]
[[privileges-to-publish-monitoring-internal]]
===== Internal collection

If you're using <<monitoring-internal-collection,internal collection>> to
collect metrics about {beatname_uc}, {security-features} provides
the +{beat_monitoring_user}+ {ref}/built-in-users.html[built-in user] and
+{beat_monitoring_user}+ {ref}/built-in-roles.html[built-in role] to send
monitoring information. You can use the built-in user, if it's available in your
environment, or create a user who has the privileges needed to send monitoring
information.

If you use the built-in +{beat_monitoring_user}+ user,
make sure you set the password before assigning it to users that need to write monitoring data to {es}.

If you don't use the +{beat_monitoring_user}+ user:

--
. Create a *monitoring role*, called something like
+{beat_default_index_prefix}_monitoring_writer+, that has the following privileges:
+
[options="header"]
|====
|Type | Privilege | Purpose

|Index
|`create_index` on `.monitoring-beats-*` indices
|Create monitoring indices in {es}

|Index
|`create_doc` on `.monitoring-beats-*` indices
|Write monitoring events into {es}
|====
+
. Assign the *monitoring role* to users who need to writer monitoring data to {es}.
--

[float]
[[privileges-to-publish-monitoring-metricbeat]]
===== Metricbeat collection

If you're <<monitoring-metricbeat-collection,using {metricbeat}>> to collect
metrics about {beatname_uc}, {security-features} provides the `remote_monitoring_user`
{ref}/built-in-users.html[built-in user], and the `remote_monitoring_collector`
and `remote_monitoring_agent` {ref}/built-in-roles.html[built-in roles] for
collecting and sending monitoring information. You can use the built-in user, if
it's available in your environment, or create a user who has the privileges
needed to collect and send monitoring information.

If you use the built-in `remote_monitoring_user` user,
make sure you set the password before assigning it to users that need to write monitoring data to {es}.

If you don't use the `remote_monitoring_user` user:

--
. Create a user on the production cluster who will collect and send monitoring
information.

. Assign the following roles to the user:
+
[options="header"]
|====
|Role | Purpose

|`remote_monitoring_collector`
|Collect monitoring metrics from {beatname_uc}

|`remote_monitoring_agent`
|Send monitoring data to the monitoring cluster
|====
--

[float]
[[privileges-to-publish-monitoring-view]]
==== View monitoring data

For users that need to view monitoring data:

. Create a *monitoring role*, called something like
+{beat_default_index_prefix}_monitoring_viewer+, that has the following privileges:
+
[options="header"]
|====
|Type | Privilege | Purpose

| Spaces
|`Read` on Stack monitoring
|Allows the user to view the Stack Monitoring feature in {kib}.
|====
+
. Assign the *monitoring role*, along with the following built-in roles, to users who
need to view monitoring data for {beatname_uc}:
+
[options="header"]
|====
|Role | Purpose

|`monitoring_user`
|Use *Stack Monitoring* in {kib} to monitor {beatname_uc}
|====

////
***********************************  ***********************************
***********************************  ***********************************
////

[[privileges-to-publish-events]]
=== Grant privileges and roles needed for publishing

++++
<titleabbrev>Create a _publishing_ user</titleabbrev>
++++

Users who publish events to {es} need to create and write to +{beat_default_index_prefix}+
indices. To minimize the privileges required by the writer role, use the
<<privileges-to-setup-beats,setup role>> to pre-load dependencies. This section
assumes that you've pre-loaded dependencies.

ifndef::no_ilm[]
When using ILM, turn off the ILM setup check in the {beatname_uc} config file before
running {beatname_uc} to publish events:

[source,yaml]
----
setup.ilm.check_exists: false
----
endif::no_ilm[]

To grant the required privileges:

. Create a *writer role*, called something like +{beat_default_index_prefix}_writer+,
that has the following privileges:
+
[options="header"]
|====
|Type | Privilege | Purpose

|Index
|`create_doc` on +{beat_default_index_prefix}-*+ indices
|Write events into {es}

|Index
|`create_index` on +{beat_default_index_prefix}-*+ indices
|Create daily indices when connecting to clusters that do not support ILM.
Not needed when using ILM.

|Index
|`read` on +{beat_default_index_prefix}-*sourcemap+ indices
|Read sourcemaps
|====

. Assign the *writer role* to users who will index events into {es}.

[float]
==== Ingest tasks

Certain ingest tasks can be performed with stricter privileges. Consider the following tasks:

[float]
===== Ingest Agent data

[options="header"]
|====
|Type | Privilege | Purpose

|Index
|`create_doc` on +{beat_default_index_prefix}-*+ indices
|Write events into {es}

|Index
|`create_index` on +{beat_default_index_prefix}-*+ indices
|Create daily indices when connecting to clusters that do not support ILM.
Not needed when using ILM.

|Index
|`read` on +{beat_default_index_prefix}-*sourcemap+ indices
|Read sourcemaps
|====

[float]
===== Upload sourcemaps

[options="header"]
|====
|Type | Privilege | Purpose

|Index
|`create_doc` on +{beat_default_index_prefix}-*+ indices
|Write events into {es}

|Index
|`create_index` on +{beat_default_index_prefix}-*+ indices
|Create daily indices when connecting to clusters that do not support ILM.
Not needed when using ILM.
|====

////
***********************************  ***********************************
***********************************  ***********************************
////

[[kibana-user-privileges]]
=== Grant privileges and roles needed to read APM data from {kib}

++++
<titleabbrev>Create a _reader_ user</titleabbrev>
++++

{kib} users typically need to view apps, dashboards, and visualizations that contain
APM data. These users might also need to create and edit dashboards, visualizations, and machine learning jobs.

To grant users the required privileges:

. Assign the following built-in roles to users who need to read APM data:
+
[options="header"]
|====
|Role | Purpose

|`kibana_user`
|Use the APM UI

|`apm_user`
|Use the APM UI
|====
+
. If you're using any of the APM, Dashboard, Visualize, Discover, etc., apps,
you'll need assign space privileges:
+
[options="header"]
|====
|Type | Privilege | Purpose

| Spaces
| `Read` or `All` on {beat_kib_app}
| Allow the use of the {beat_kib_app}

| Spaces
| `Read` or `All` on Dashboards, Visualize, and Discover
| Allow the user to view, edit, and create dashboards, as well as browse data.
|====
+
. If you're using APM Agent configuration, add the following built-in roles:
+
[options="header"]
|====
|Role | Purpose

|`admin`
|Read and update APM Agent configuration via {kib}
|====
+
. Finally, assign the following role if a user needs to enable and edit machine learning features:
+
[options="header"]
|====
|Role | Purpose

|`machine_learning_admin`
|NEED DESCRIPTION
|====

////
***********************************  ***********************************
***********************************  ***********************************
////

[[privileges-agent-central-config]]
=== Grant privileges and roles needed for APM Agent central configuration

++++
<titleabbrev>Create a _central config management_ user</titleabbrev>
++++

[[privileges-agent-central-config-server]]
==== APM Server central configuration management

CONTENT

[[privileges-agent-central-config-kib]
==== Kibana central configuration management

CONTENT

[[privileges-agent-central-config-api]]
==== Central configuration management API

CONTENT

////
***********************************  ***********************************
***********************************  ***********************************
////

[[privileges-apm-app]]
=== Grant privileges and roles needed for using the APM app

++++
<titleabbrev>Create an _APM app_ user</titleabbrev>
++++

CONTENT

////
***********************************  ***********************************
***********************************  ***********************************
////

[[privileges-create-api-keys]]
=== Grant privileges and roles needed to create APM Server API keys

++++
<titleabbrev>Create an _APM API key_ user</titleabbrev>
++++

CONTENT

////
***********************************  ***********************************
***********************************  ***********************************
////

[[privileges-annotation-api]]
=== Grant privileges and roles needed for the Annotation API

++++
<titleabbrev>Create an _annotation API_ user</titleabbrev>
++++

CONTENT

////
***********************************  ***********************************
***********************************  ***********************************
////

[[learn-more-security]]
=== Learn more about users and roles

Want to learn more about creating users and roles? See
{ref}/secure-cluster.html[Secure a cluster]. Also see:

* {ref}/security-privileges.html[Security privileges] for a description of
available privileges
* {ref}/built-in-roles.html[Built-in roles] for a description of roles that
you can assign to users
