---
description: Pipeline for ingesting APM error events.
processors:
  - pipeline:
      name: observer_version
  - pipeline:
      name: observer_ids
  - pipeline:
      name: ecs_version
  - pipeline:
      name: user_agent
  - pipeline:
      name: process_ppid
  - pipeline:
      name: client_geoip
  - script:
      if: ctx.error?.exception?.length != null && ctx.error?.exception?.length > 0
      source: ctx.error.grouping_name = ctx.error.exception[0].message
  - set:
      if: ctx.error?.log?.message != null
      field: error.grouping_name
      copy_from: error.log.message
