---
description: Pipeline for ingesting APM trace events.
processors:
  - pipeline:
      name: observer_version
  - pipeline:
      name: observer_ids
  - pipeline:
      name: ecs_version
  - pipeline:
      name: user_agent
  - pipeline:
      name: process_ppid
  - pipeline:
      name: client_geoip
  - pipeline:
      name: event_duration
  # event.success_count logic
  - set:
      if: ctx.event?.outcome == 'success'
      field: event.success_count
      value: 1
      ignore_failure: true
  - set:
      if: ctx.event?.outcome == 'failure'
      field: event.success_count
      value: 0
      ignore_failure: true
