---
description: Pipeline for ingesting APM trace events.
processors:
  - pipeline:
      name: user_agent
  - pipeline:
      name: client_geoip
  - remove:
      # Remove some metadata from spans that is available in the parent transaction, to cut down on storage costs.
      if: ctx.processor?.event == 'span'
      field:
        - host
        - process
        - user
        - user_agent
        - container
        - kubernetes
        - service.node
        - service.version
        - service.language
        - service.runtime
        - service.framework
      ignore_missing: true
      ignore_failure: true

