---
name: generate-bc-upgrade-paths
description: Generate BC upgrade paths

outputs:
  upgrade_paths:
    description: "List of BC upgrade paths"
    value: ${{ steps.generate.outputs.upgrade_paths }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - id: generate
      name: Generate BC upgrade paths
      run: |
        echo "upgrade_paths=$(./bc.sh)" >> "${GITHUB_OUTPUT}"
      shell: 'bash'
      working-directory: ./.github/workflows/generate-bc-upgrade-paths