---
name: generate-upgrade-paths
description: Generate upgrade paths

inputs:
  snapshots:
    description: "Use SNAPSHOT versions for test"
    required: false
    default: 'false'

outputs:
  upgrade_paths:
    description: "List of SNAPSHOT upgrade paths"
    value: ${{ steps.generate.outputs.upgrade_paths }}

runs:
  using: "composite"
  steps:
    - name: Setup
      uses: ./.github/workflows/setup-integration-server-test
    - id: generate
      name: Generate upgrade paths
      run: |
        echo "upgrade_paths=$(go run ./scripts/genpath --target='pro' --snapshots=${{ inputs.snapshots }})" >> "${GITHUB_OUTPUT}"
      shell: 'bash'
      working-directory: ./integrationservertest/