---
name: setup-integration-server-test
description: Setup Integration Server Test

runs:
  using: composite
  steps:
    - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
      with:
        terraform_version: "${{ env.TERRAFORM_VERSION }}"
    - uses: actions/setup-go@v6
      with:
        go-version-file: 'integrationservertest/go.mod'
        cache: false
    - uses: elastic/oblt-actions/google/auth@v1
      with:
        project-number: '911195782929'
        project-id: 'elastic-observability-ci'
    - uses: google-github-actions/get-secretmanager-secrets@bc9c54b29fdffb8a47776820a7d26e77b379d262 # v3.0.0
      with:
        export_to_environment: true
        secrets: |-
          EC_API_KEY:elastic-observability-ci/elastic-cloud-observability-team-pro-api-key