[[apm-integration-configure]]
== Configure APM integration

++++
<titleabbrev>Configure</titleabbrev>
++++

beta::[]

Templates, pipelines, index lifecycle management, etc.,
cannot be configured with APM Server or Fleet, and must instead be configured in {kib} or with
{es} APIs.

[id="apm-integration-templates",canonical-url="https://www.elastic.co/guide/en/apm/guide/current/custom-index-template.html"]
=== Index templates

The APM integration loads default index templates into {es}.
These templates configure the APM data stream indices.
To view and edit these templates in {kib},
select *Stack Management* / *Index Management* / *Index Templates*.
Search for `apm`.

See {ref}/index-templates.html[index templates] for more information.

[id="apm-integration-pipelines",canonical-url="https://www.elastic.co/guide/en/apm/guide/current/ingest-pipelines.html"]
=== Pipelines

The APM integration loads default ingest node pipelines into {es}.
These pipelines preprocess and enrich APM documents before indexing them.
To view and edit these pipelines in {kib},
select *Stack Management* / *Index Node Pipelines*.
Search for `apm`.

See {ref}/ingest.html[ingest node pipelines] for more information.

[id="apm-integration-ilm",canonical-url="https://www.elastic.co/guide/en/apm/guide/current/ilm-how-to.html"]
=== Index lifecycle management (ILM)

The index lifecycle management (ILM) feature in {es} allows you to automate the
lifecycle of your APM Server indices as they grow and age.
ILM is enabled by default, and a default policy is applied to all APM indices.

To view and edit these index lifecycle policies in {kib},
select *Stack Management* / *Index Lifecycle Management*.
Search for `apm`.

See {ref}/getting-started-index-lifecycle-management.html[manage the index lifecycle] for more information.

// to do
// [[apm-integration-sourcemaps]]
// === RUM Source maps
