[[apm-integration-data-streams]]
== Data streams

All Elastic Agent integrations store data in indices following the data stream naming scheme.
If you're new to data streams, see the [Fleet user guide] to learn more before continuing.

All `apm` input data will be stored in the following indices:

// Turn this into a table
- Application logs: `logs-<service.name>-<namespace>`
- APM error/exception logging: `logs-apm.error.<service.name>-<namespace>`
- Application defined metrics: `metrics-apm.<service.name>-<namespace>`
- APM internal metrics: `metrics-apm.internal.<service.name>-<namespace>`
- APM profiling metrics: `metrics-apm.profiling.<service.name>-<namespace>`
- APM transactions and spans: `traces-apm.<service.name>-<namespace>`

Index templates configure data streams and their backing indices.
For example, the index template for `traces-apm` has in index pattern of `traces-apm.*-*`,
and creates the `traces-apm.*-*` indices.

[discrete]
[[apm-integration-service-name]]
=== Service name requirements

The APM integration maps an instrumented service's name–defined in each APM agent's configuration–
to the index that its data is stored in {es}.
This process provides more granular security and retentions policies,
and simplifies the overall APM experience.
Service names therefore must follow index naming rules:

* Service names are case-insensitive and must be unique.
For example, you cannot have a service named `Foo` and another named `foo`.
* Special characters will be removed from service names and replaced with underscores (`_`).
Special characters include:
+
[source,text]
----
'\\', '/', '*', '?', '"', '<', '>', '|', ' ', ',', '#', ':', '-'
----

[discrete]
[[apm-integration-namespace]]
=== Namespace

There is no recommendation for what to use as your namespace;
it's intentionally flexible which allows greater control over how your data is indexed.
For example, you might create namespaces for each of your environments,
like `dev`, `prod`, `production`, etc.
Or, you might create namespaces that correspond to strategic business units within your organization.
