[[agent-configuration-api]]
== Agent configuration API

++++
<titleabbrev>Agent configuration</titleabbrev>
++++

APM Server exposes an API endpoint that allows agents to query the server for configuration changes.
More information on this feature is available in {kibana-ref}/agent-configuration.html[APM Agent configuration in Kibana].

Starting with release 7.14, agent configuration can be declared directly within
`apm-server.yml`. Requests to the endpoint are unchanged; `apm-server` responds
directly without querying kibana for the agent configuration. Refer to the
example in `apm-server.yml` under Agent Configuration.

[[agent-config-endpoint]]
[float]
=== Agent configuration endpoint

The Agent configuration endpoint accepts both `HTTP GET` and `HTTP POST` requests.
If an <<api-key>> or <<secret-token>> has been configured, it will also apply to this endpoint.

[[agent-config-api-get]]
[float]
==== HTTP GET

`service.name` is a required query string parameter.

[source,bash]
------------------------------------------------------------
http(s)://{hostname}:{port}/config/v1/agents?service.name=SERVICE_NAME
------------------------------------------------------------

[[agent-config-api-post]]
[float]
==== HTTP POST

Encode parameters as a JSON object in the body.
`service.name` is a required parameter.

[source,bash]
------------------------------------------------------------
http(s)://{hostname}:{port}/config/v1/agents
{
  "service": {
      "name": "test-service",
      "environment": "all"
  },
  "CAPTURE_BODY": "off"
}
------------------------------------------------------------

[[agent-config-api-response]]
[float]
==== Responses

* Successful - `200`
* Kibana endpoint is disabled - `403`
* Kibana is unreachable - `503`

[[agent-config-api-example]]
[float]
==== Example request

Example Agent configuration `GET` request including the service name "test-service":

["source","sh",subs="attributes"]
---------------------------------------------------------------------------
curl -i http://127.0.0.1:8200/config/v1/agents?service.name=test-service
---------------------------------------------------------------------------

Example Agent configuration `POST` request including the service name "test-service":

["source","sh",subs="attributes"]
---------------------------------------------------------------------------
curl -X POST http://127.0.0.1:8200/config/v1/agents \
  -H "Authorization: Bearer secret_token" \
  -H 'content-type: application/json' \
  -d '{"service": {"name": "test-service"}}'
---------------------------------------------------------------------------

[[agent-config-api-ex-response]]
[float]
==== Example response

["source","sh",subs="attributes"]
---------------------------------------------------------------------------
HTTP/1.1 200 OK
Cache-Control: max-age=30, must-revalidate
Content-Type: application/json
Etag: "7b23d63c448a863fa"
Date: Mon, 24 Feb 2020 20:53:07 GMT
Content-Length: 98

{
    "capture_body": "off",
    "transaction_max_spans": "500",
    "transaction_sample_rate": "0.3"
}
---------------------------------------------------------------------------
