[[api-otlp]]
=== OpenTelemetry intake API

APM Server supports receiving traces, metrics, and logs over the
https://opentelemetry.io/docs/specs/otlp/[OpenTelemetry Protocol (OTLP)].
OTLP is the default transfer protocol for OpenTelemetry and is supported natively by APM Server.

APM Server supports two OTLP communication protocols on the same port:
* OTLP/HTTP (protobuf)
* OTLP/gRPC

**OTLP/gRPC paths**

[options="header"]
|====
|Name |Endpoint
|OTLP metrics intake |`/opentelemetry.proto.collector.metrics.v1.MetricsService/Export`
|OTLP trace intake |`/opentelemetry.proto.collector.trace.v1.TraceService/Export`
|OTLP logs intake |`/opentelemetry.proto.collector.logs.v1.LogsService/Export`
|====

**OTLP/HTTP paths**

[options="header"]
|====
|Name |Endpoint
|OTLP metrics intake |`/v1/metrics`
|OTLP trace intake |`/v1/traces`
|OTLP logs intake |`/v1/logs`
|====

TIP: See our OpenTelemetry documentation to learn how to send data to the APM Server from an
<<instrument-apps-otel,OpenTelemetry agent>> or
<<connect-open-telemetry-collector,OpenTelemetry collector>>.
