:issue: https://github.com/elastic/apm-server/issues/
:pull: https://github.com/elastic/apm-server/pull/

[[apm-breaking]]
=== Breaking Changes

// These tagged regions are required for the stack-docs repo includes
// tag::notable-v8-breaking-changes[]
// end::notable-v8-breaking-changes[]

This section describes the breaking changes and deprecations introduced in this release
and previous minor versions.

[float]
[[breaking-changes-8.0]]
=== 8.0

// tag::80-bc[]
The following breaking changes are introduced in APM version 8.0.

[float]
==== Indices are now manged by {fleet}

All index management has been removed from APM Server;
{fleet} is now entirely responsible for setting up index templates, index lifecycle polices,
and index pipelines.

As a part of this change, the following settings have been removed:

* `apm-server.ilm.*`
* `apm-server.register.ingest.pipeline.*`
* `setup.*`

[float]
==== Data streams by default

APM Server now only writes to well-defined data streams;
writing to classic indices is no longer supported.

As a part of this change, the following settings have been removed:

* `apm-server.data_streams.enabled`
* `output.elasticsearch.index`
* `output.elasticsearch.indices`
* `output.elasticsearch.pipeline`
* `output.elasticsearch.pipelines`

[float]
==== New {es} output

APM Server has a new {es} output implementation with defaults that should be sufficient for
most use cases; it should no longer be necessary to manually tune the output
of APM Server.

As a part of this change, the following settings have been removed:

* `output.elasticsearch.bulk_max_size`
* `output.elasticsearch.worker`
* `queue.*`

[float]
==== New source map upload endpoint

The source map upload endpoint has been removed from APM Server.
Source maps should now be uploaded directly to {kib} instead.

[float]
==== Legacy Jaeger endpoints have been removed

The legacy Jaeger gRPC and HTTP endpoints have been removed from APM Server.

As a part of this change, the following settings have been removed:

* `apm-server.jaeger`

[float]
==== All removed and changed settings

A complete list of all removed settings (in alphabetical order)

[source,yml]
----
apm-server.data_streams.enabled
apm-server.ilm.*
apm-server.jaeger
apm-server.register.ingest.pipeline.*
apm-server.sampling.keep_unsampled
output.elasticsearch.bulk_max_size
output.elasticsearch.index
output.elasticsearch.indices
output.elasticsearch.pipeline
output.elasticsearch.pipelines
output.elasticsearch.worker
queue.*
setup.*
----

A complete list of renamed settings (in alphabetical order)

[source,yml]
----
previous setting                --> new setting

apm-server.api_key              --> apm-server.auth.api_key
apm-server.instrumentation      --> instrumentation
apm-server.rum.allowed_service  --> apm-server.auth.anonymous.allow_service
apm-server.rum.event_rate       --> apm-server.auth.anonymous.rate_limit
apm-server.secret_token         --> apm-server.auth.secret_token
----
// end::80-bc[]
