:issue: https://github.com/elastic/apm-server/issues/
:pull: https://github.com/elastic/apm-server/pull/

[[apm-breaking]]
=== Breaking Changes

// These tagged regions are required for the stack-docs repo includes
// tag::88-bc[]
// end::88-bc[]
// tag::notable-v8-breaking-changes[]
// end::notable-v8-breaking-changes[]

This section describes the breaking changes and deprecations introduced in this release
and previous minor versions.

// tag::87-bc[]
[float]
[[breaking-changes-8.7]]
=== 8.7

The following breaking changes and deprecations are introduced in APM version 8.7.0:

- `transaction.failure_count` has been removed. `transaction.success_count` type has changed to `aggregated_metric_double`.
For more details, see https://github.com/elastic/apm-server/pull/9791[PR #9791].

- `transaction.success_count` has been moved to `event.success_count`.
For more details, see https://github.com/elastic/apm-server/pull/9819[PR #9819].

- Stopped indexing transaction metrics to `metrics-apm.internal`.
For more details, see https://github.com/elastic/apm-server/pull/9846[PR #9846].

- Stopped indexing span destination metrics to `metrics-apm.internal`.
For more details, see https://github.com/elastic/apm-server/pull/9926[PR #9926].

- `apmserver.aggregation.txmetrics.overflowed` metric has been renamed to `apmserver.aggregation.txmetrics.overflowed.total`.
For more details, see https://github.com/elastic/apm-server/pull/10330[PR #10330].

- Elasticsearch source mapping credentials now require access to the `.apm-source-map` index.
For more details, see https://github.com/elastic/apm-server/pull/9722[PR #9722].

- Changed APM Server default host to `127.0.0.1`.
For more details, see https://github.com/elastic/apm-server/pull/9877[PR #9877].
// end::87-bc[]

// tag::86-bc[]
[float]
[[breaking-changes-8.6]]
=== 8.6

The following breaking changes and deprecations are introduced in APM version 8.6.0:

[float]
==== `apm-server.decoder.*` no longer recorded
The stack monitoring metrics, `apm-server.decoder.*`, are no longer recorded.
These metrics were not used by stack monitoring, so there should be no noticeable change.

For more details, see https://github.com/elastic/apm-server/pull/9210[PR #9210].

[float]
==== `context.http.response.*_size` fields now enforce integer values
New field mappings enforce integer values for `context.http.response.*_size`.
The fields are mapped with `index: false` to minimize storage overhead.

For more details, see https://github.com/elastic/apm-server/pull/9429[PR #9429].

[float]
==== `observer.id` and `observer.ephemeral_id` removed

`observer.id` and `observer.ephemeral_id` are no longer added to APM documents.
The APM UI does not currently rely on these field, so there should be no noticeable change.

For more details, see https://github.com/elastic/apm-server/pull/9412[PR #9412].

[float]
==== `timeseries.instance` removed
`timeseries.instance` has been removed from transaction metrics docs.
The APM UI did not use this field, so there should be no noticeable change.

For more details, see https://github.com/elastic/apm-server/pull/9565[PR #9565].

// end::86-bc[]

[float]
[[breaking-changes-8.2]]
=== 8.2

// tag::82-bc[]
The following breaking changes are introduced in APM version 8.2.0:

[float]
==== APM Server now emits events with `event.duration`

APM Server no longer emits events with a `transaction.duration.us` or `span.duration.us`.
Instead, events are emitted with an `event.duration`.
An ingest pipeline sets the legacy `<event>.duration.us` field and removes the `event.duration`.

This change will impact users who are not using APM Server's {es} output or the packaged ingest pipeline.
For details, see https://github.com/elastic/apm-server/pull/7261[PR #7261].

[float]
==== Removed `observer.version_major`

The field `observer.version_major` is non-standard and existed only for the APM UI to filter out legacy docs (versions <7.0).
This check is no longer performed, so the field has been removed.

For details, see https://github.com/elastic/apm-server/pull/7399[PR #7399].

[float]
==== APM Server no longer ships with System V init scripts or the go-daemon wrapper

As of version 8.1.0, all Linux distributions supported by APM Server support systemd.
As a result, APM Server no longer ships with System V init scripts or the go-daemon wrapper; use systemd instead.

For details, see https://github.com/elastic/apm-server/pull/7576[PR #7576].

[float]
==== Deprecated 32-bit architectures

APM Server support for 32-bit architectures has been deprecated and will be removed in a future release.
// end::82-bc[]

[float]
[[breaking-changes-8.1]]
=== 8.1

// tag::81-bc[]
There are no breaking changes in APM.
// end::81-bc[]

[float]
[[breaking-changes-8.0]]
=== 8.0

// tag::80-bc[]
The following breaking changes are introduced in APM version 8.0.

[float]
==== Indices are now manged by {fleet}

All index management has been removed from APM Server;
{fleet} is now entirely responsible for setting up index templates, index lifecycle polices,
and index pipelines.

As a part of this change, the following settings have been removed:

* `apm-server.ilm.*`
* `apm-server.register.ingest.pipeline.*`
* `setup.*`

[float]
==== Data streams by default

APM Server now only writes to well-defined data streams;
writing to classic indices is no longer supported.

As a part of this change, the following settings have been removed:

* `apm-server.data_streams.enabled`
* `output.elasticsearch.index`
* `output.elasticsearch.indices`
* `output.elasticsearch.pipeline`
* `output.elasticsearch.pipelines`

[float]
==== New {es} output

APM Server has a new {es} output implementation; it is no longer necessary to manually
tune the output of APM Server.

As a part of this change, the following settings have been removed:

* `output.elasticsearch.bulk_max_size`
* `output.elasticsearch.worker`
* `queue.*`

[float]
==== New source map upload endpoint

The source map upload endpoint has been removed from APM Server.
Source maps should now be uploaded directly to {kib} instead.

[float]
==== Legacy Jaeger endpoints have been removed

The legacy Jaeger gRPC and HTTP endpoints have been removed from APM Server.

As a part of this change, the following settings have been removed:

* `apm-server.jaeger`

[float]
==== Homebrew no longer supported

APM Server no longer supports installation via Homebrew.

[float]
==== All removed and changed settings

Below is a list of all **removed settings** (in alphabetical order) for
users upgrading a standalone (legacy) APM Server to {stack} version 8.0.

[source,yml]
----
apm-server.data_streams.enabled
apm-server.ilm.*
apm-server.jaeger
apm-server.register.ingest.pipeline.*
apm-server.sampling.keep_unsampled
output.elasticsearch.bulk_max_size
output.elasticsearch.index
output.elasticsearch.indices
output.elasticsearch.pipeline
output.elasticsearch.pipelines
output.elasticsearch.worker
queue.*
setup.*
----

Below is a list of **renamed settings** (in alphabetical order) for
users upgrading a standalone (legacy) APM Server to {stack} version 8.0.

[source,yml]
----
previous setting                --> new setting

apm-server.api_key              --> apm-server.auth.api_key
apm-server.instrumentation      --> instrumentation
apm-server.rum.allowed_service  --> apm-server.auth.anonymous.allow_service
apm-server.rum.event_rate       --> apm-server.auth.anonymous.rate_limit
apm-server.secret_token         --> apm-server.auth.secret_token
----

[float]
==== Supported {ecloud} settings

Below is a list of all **supported settings** (in alphabetical order) for
users upgrading an {ecloud} standalone (legacy) cluster to {stack} version 8.0.
Any previously supported settings not listed below will be removed when upgrading.

[source,yml]
----
apm-server.agent.config.cache.expiration
apm-server.aggregation.transactions.*
apm-server.auth.anonymous.allow_agent
apm-server.auth.anonymous.allow_service
apm-server.auth.anonymous.rate_limit.event_limit
apm-server.auth.anonymous.rate_limit.ip_limit
apm-server.auth.api_key.enabled
apm-server.auth.api_key.limit
apm-server.capture_personal_data
apm-server.default_service_environment
apm-server.max_event_size
apm-server.rum.allow_headers
apm-server.rum.allow_origins
apm-server.rum.enabled
apm-server.rum.exclude_from_grouping
apm-server.rum.library_pattern
apm-server.rum.source_mapping.enabled
apm-server.rum.source_mapping.cache.expiration
logging.level
logging.selectors
logging.metrics.enabled
logging.metrics.period
max_procs
output.elasticsearch.flush_bytes
output.elasticsearch.flush_interval
----

// end::80-bc[]
