[[breaking-changes]]
=== Breaking Changes
APM Server is built on top of {beats-ref}/index.html[libbeat].
As such, any breaking change in libbeat is also considered to be a breaking change in APM Server.

[float]
==== HEAD

[float]
==== 7.0
* Removed deprecated Intake v1 API endpoints.
Upgrade agents to a version that supports APM Server >= 6.5.
{apm-overview-ref-v}/breaking-7.0.0.html#breaking-remove-v1[More information].
* Moved fields in Elasticsearch to be compliant with the Elastic Common Schema (ECS).
{apm-overview-ref-v}/breaking-7.0.0.html#breaking-ecs[More information and changed fields].
* {beats-ref}/breaking-changes-7.0.html[Breaking changes in libbeat]

[float]
==== 6.5
* There are no breaking changes in APM Server.
* Advanced users may find the <<upgrading-to-65,upgrading to 6.5 guide>> useful.

[float]
==== 6.4
* Indexing the `onboarding` document in it's own index by default.

[float]
==== 6.3
* Indexing events in separate indices by default.
* {beats-ref-63}/breaking-changes-6.3.html[Breaking changes in libbeat]

[float]
==== 6.2
* APM Server GA