[[configuration-rum]]
== Set up Real User Monitoring (RUM) support

The {apm-rum-ref}/index.html[JavaScript RUM Agent] offers <<rum, real user monitoring (RUM)>> support.

Example config with RUM enabled:

["source","yaml"]
----
apm-server.rum.enabled: true
apm-server.rum.rate_limit: 10
apm-server.rum.allow_origins: ['*']
apm-server.rum.library_pattern: "node_modules|bower_components|~"
apm-server.rum.exclude_from_grouping: "^/webpack"
apm-server.rum.source_mapping.cache.expiration: 5m
apm-server.rum.source_mapping.index_pattern: "apm-*-sourcemap*"
----

[float]
=== Configuration options

[[rum-enable]]
[float]
==== `enabled`
For enabling RUM support, set the `apm-server.rum.enabled` to `true`.
By default this is disabled.

[float]
==== `rate_limit`
Rate limit per second and IP address for requests sent to the RUM endpoint.
If the rate limit is hit, the APM Server will return an HTTP status code `429`.
The rate limit cannot be disabled. Ensure to have it set to a number suiting your requirements.
Default value is set to 10.

[float]
==== `allow_origins`
Comma separated list of permitted origins for RUM supprt.
User-agents send an Origin header that will be validated against this list.
This is done automatically by modern browsers as part of the https://www.w3.org/TR/cors/[CORS specification].
An origin is made of a protocol scheme, host and port, without the url path.
Default value is set to `['*']`, which allows everything.

[float]
==== `library_pattern`
Regexp to be matched against a stacktrace frame's `file_name` and `abs_path` attributes.
If the regexp matches, the stacktrace frame is considered to be a library frame.
When source mapping is applied the `error.culprit` is set to reflect the _function_ and the _filename_
of the first not library frame.
This aims to provide an entry point for identifying issues.
Default value is `"node_modules|bower_components|~"`.

[float]
==== `exclude_from_grouping`
Regexp to be matched against a stacktrace frame's `file_name`.
If the regexp matches, the stacktrace frame is excluded from being used for calculating error groups.
The default pattern excludes stacktrace frames that have a filename starting with `/webpack`.

[[rum-sourcemap-cache]]
[float]
==== `source_mapping.cache.expiration`
If a source map has been uploaded to the APM Server,
<<sourcemaps,source mapping>> is automatically applied to documents sent to the RUM endpoint.
Source maps are fetched from Elasticsearch and then kept in an in-memory cache for the configured time.
Values configured without a time unit are treated as seconds.
Default value is 5 minutes.

[[config-sourcemapping-elasticsearch]]
[float]
==== `source_mapping.elasticsearch`
Configure the Elasticsearch source map retrieval location, taking the same options as <<elasticsearch-output,output.elasticsearch>>.
This must be set when using an output other than Elasticsearch, and that output is writing to Elasticsearch.
Othewise leave this section empty.

[float]
==== `source_mapping.index_pattern`
Source maps are stored in a seperate index `apm-%{[beat.version]}-sourcemap` by default.
If changed, a matching index pattern needs to be specified here.

