[[sourcemap-output]]

[float]
=== Sourcemaps

Sourcemaps can be uploaded through all outputs but must eventually be stored in Elasticsearch.
When using outputs other than Elasticsearch, `source_mapping.elasticsearch` must be set for source maps to be applied.
Be sure to update `source_mapping.index_pattern` if sourcemaps are stored in the non-default location.
See <<config-sourcemapping-elasticsearch>> for more details.

[[libbeat-configuration-fields]]
[float]
=== `fields`

Fields are optional tags that can be added to all outputs.
Fields can be scalar values, arrays, dictionaries, or any nested combination of these.
By default, the fields that you specify here will be grouped under a `fields` sub-dictionary in the output document.

Example:

[source,yaml]
------------------------------------------------------------------------------
fields: {project: "myproject", instance-id: "574734885120952459"}
#-------------------------- Elasticsearch output --------------------------
output.elasticsearch:
  hosts: ["localhost:9200"]
------------------------------------------------------------------------------

To store the custom fields as top-level fields, set the `fields_under_root` option to true.
This is not recommended as when new fields are added to APM documents backward compatibility cannot be ensured.
