[[exploring-es-data]]
= Exploring data in Elasticsearch

[partintro]
--

By default, Elastic APM data is stored in separated indices in the following formats:
------------------------------------------------------------
apm-%{[version]}-transaction-%{+yyyy.MM.dd}
apm-%{[version]}-span-%{+yyyy.MM.dd}
apm-%{[version]}-error-%{+yyyy.MM.dd}
apm-%{[version]}-metric-%{+yyyy.MM.dd}
apm-%{[version]}-sourcemap
------------------------------------------------------------

If you're unfamiliar with the data types shown above, they are described in the {apm-overview-ref}/apm-data-model.html[APM data model].

TIP: If your APM data is being stored in a different format, you may be using an outdated `apm-server.yml` file. You must update your `apm-server.yml` file in order to take advantage of the new format of indices.

To get an overview of existing indices you can run:
["source","sh"]
------------------------------------------------------------
GET _cat/indices/apm*
------------------------------------------------------------
// CONSOLE

Default APM `template` and `indices`:

* <<transaction-indices>>
* <<span-indices>>
* <<error-indices>>
* <<metricset-indices>>
* <<sourcemap-indices>>


To query all documents collected with a specific APM Server version:
["source","sh",subs="attributes"]
------------------------------------------------------------
GET apm-{version}-*/_search
------------------------------------------------------------
// CONSOLE

To query a specific type, for example transactions:
["source","sh",subs="attributes"]
------------------------------------------------------------
GET apm-*transactions-*/_search
------------------------------------------------------------
// CONSOLE

If you are interested in the _settings_ and _mappings_ of the Elastic APM indices,
first, run a query to find template names:

["source","sh"]
------------------------------------------------------------
GET _cat/templates/apm*
------------------------------------------------------------
// CONSOLE

Then you can retrieve the specific template you are interested in:
["source","sh"]
------------------------------------------------------------
GET  /_template/your-template-name
------------------------------------------------------------
// CONSOLE

Read more about {ref}/indices-templates.html[Index Templates] and how they are used.

Alternatively, use the {kibana-ref}/managing-indices.html[Kibana Index Management UI].
When clicking on a specific index you can view the _settings_ and _mapping_ for it.

--


include::./transaction-indices.asciidoc[]
include::./span-indices.asciidoc[]
include::./error-indices.asciidoc[]
include::./metricset-indices.asciidoc[]
include::./sourcemap-indices.asciidoc[]
