
////
This file is generated! See _meta/fields.yml and scripts/generate_field_docs.py
////

[[exported-fields]]
= Exported fields

[partintro]

--
This document describes the fields that are exported by apm-server. They are
grouped in the following categories:

* <<exported-fields-apm>>
* <<exported-fields-apm-error>>
* <<exported-fields-apm-trace>>
* <<exported-fields-apm-transaction>>
* <<exported-fields-beat>>
* <<exported-fields-cloud>>
* <<exported-fields-docker-processor>>
* <<exported-fields-kubernetes-processor>>

--
[[exported-fields-apm]]
== General APM fields fields

None


[float]
=== `listening`

type: keyword

Address the server is listening on.


[float]
=== `processor.name`

type: keyword

Processor name.

[float]
=== `processor.event`

type: keyword

Processor event.

[float]
== context fields

General context fields.



[float]
=== `context.tags`

type: object

Flat mapping of user-defined tags.



[float]
=== `context.user.username`

type: keyword

The username of the user who experienced this event.


[float]
=== `context.user.id`

type: keyword

Identifier of the user who experienced this event.


[float]
=== `context.user.email`

type: keyword

Email of the user who experienced this event.



[float]
== url fields

The http URL of the request leading to this event.



[float]
=== `context.request.url.raw`

type: keyword

The raw, unparsed URL of the request, e.g https://example.com:443/search?q=elasticsearch#top.


[float]
=== `context.request.url.protocol`

type: keyword

The protocol of the request, e.g. "https:".


[float]
=== `context.request.url.hostname`

type: keyword

The hostname of the request, e.g. "example.com".


[float]
=== `context.request.url.port`

type: keyword

The port of the request, e.g. 443.


[float]
=== `context.request.url.pathname`

type: keyword

The path of the request, e.g. "/search".


[float]
=== `context.request.url.search`

type: keyword

The search describes the query string of the request, e.g. "q=elasticsearch".


[float]
=== `context.request.url.hash`

type: keyword

The hash of the request URL, e.g. "top".


[float]
=== `context.request.http_version`

type: keyword

The http version of the request leading to this event.


[float]
=== `context.request.method`

type: keyword

The http method of the request leading to this event.



[float]
=== `context.response.status_code`

type: long

Http response status code.


[float]
=== `context.response.finished`

type: boolean

[float]
== system fields

Optional system fields.



[float]
=== `context.system.hostname`

type: keyword

The host that records the event.


[float]
=== `context.system.architecture`

type: keyword

The architecture of the host that records the event.


[float]
=== `context.system.platform`

type: keyword

The platform of the host that records the event.


[float]
== app fields

App fields.



[float]
=== `context.app.name`

type: keyword

Unique App name.


[float]
=== `context.app.version`

type: keyword

App version.


[float]
=== `context.app.git_ref`

type: keyword

App git reference.


[float]
=== `context.app.pid`

type: long

Numeric process ID of the app process.


[float]
=== `context.app.process_title`

type: keyword

App process_title.



[float]
=== `context.app.language.name`

type: keyword

Language name.


[float]
=== `context.app.language.version`

type: keyword

Language version.



[float]
=== `context.app.runtime.name`

type: keyword

Runtime name.


[float]
=== `context.app.runtime.version`

type: keyword

Runtime version.



[float]
=== `context.app.framework.name`

type: keyword

Framework name.


[float]
=== `context.app.framework.version`

type: keyword

Framework version.



[float]
=== `context.app.agent.name`

type: keyword

Agent name.


[float]
=== `context.app.agent.version`

type: keyword

Agent version.


[float]
== db fields

An object containing contextual data for database traces



[float]
=== `context.db.instance`

type: text

Database instance name


[float]
=== `context.db.statement`

type: text

A database statement (e.g. query) for the given database type


[float]
=== `context.db.type`

type: text

Database type. For any SQL database, "sql". For others, the lower-case database category, e.g. "cassandra", "hbase", or "redis"


[float]
=== `context.db.user`

type: text

Username for accessing database


[[exported-fields-apm-error]]
== APM Error fields

Error-specific data for APM



[float]
=== `error.id`

type: keyword

A UUID4 error ID.


[float]
=== `error.culprit`

type: text

Function call which was the primary perpetrator of this event.

[float]
=== `error.grouping_key`

type: keyword

GroupingKey of the logged error for use in grouping.


[float]
== exception fields

Information about the originally thrown error.



[float]
=== `error.exception.code`

type: keyword

The error code set when the error happened, e.g. database error code.

[float]
=== `error.exception.message`

type: text

The original error message.

[float]
=== `error.exception.module`

type: keyword

The module namespace of the original error.

[float]
=== `error.exception.type`

type: keyword

[float]
=== `error.exception.uncaught`

type: boolean

Indicator whether the error was caught somewhere in the code or not.

[float]
== log fields

Additional information added by logging the error.



[float]
=== `error.log.level`

type: keyword

The severity of the record.

[float]
=== `error.log.logger_name`

type: keyword

The name of the used logger instance.

[float]
=== `error.log.message`

type: text

The additionally logged error message.

[float]
=== `error.log.param_message`

type: keyword

Equal to message, but with placeholders replaced.

[[exported-fields-apm-trace]]
== APM Trance fields

Trace-specific data for APM.



[float]
=== `trace.id`

type: long

A locally unique ID of the trace.


[float]
=== `trace.transaction_id`

type: keyword

Reference to the transaction this trace is part of.


[float]
=== `trace.name`

type: keyword

Generic name of the trace.


[float]
=== `trace.type`

type: keyword

Type of the trace. This should be a dotted format, e.g. db.postgresql.query, cache.redis, or ext.http.get.


[float]
== start fields

None


[float]
=== `trace.start.us`

type: long

Start time of the trace in microseconds, relative to the start time of the transaction.


[float]
== duration fields

None


[float]
=== `trace.duration.us`

type: long

Duration of the trace, in microseconds.


[float]
=== `trace.parent`

type: long

The parent trace id for recreating the full ancestor path.


[[exported-fields-apm-transaction]]
== APM Transaction fields

Transaction-specific data for APM



[float]
=== `transaction.id`

type: keyword

A UUID4 transaction ID.


[float]
=== `transaction.name`

type: text

Name of the transaction. This is usually a generic path to the controller/endpoint that handled the transaction.
TODO: investigate use of "path_hierarchy" tokenizer


[float]
=== `transaction.type`

type: keyword

The transaction type, e.g. "request", or "job".


[float]
== duration fields

None


[float]
=== `transaction.duration.us`

type: long

Total duration of this transaction, in microseconds.


[float]
=== `transaction.result`

type: keyword

The result of the transaction. HTTP status code for HTTP-related transactions.


[[exported-fields-beat]]
== Beat fields

Contains common beat fields available in all event types.



[float]
=== `beat.name`

The name of the Beat sending the log messages. If the Beat name is set in the configuration file, then that value is used. If it is not set, the hostname is used. To set the Beat name, use the `name` option in the configuration file.


[float]
=== `beat.hostname`

The hostname as returned by the operating system on which the Beat is running.


[float]
=== `beat.timezone`

The timezone as returned by the operating system on which the Beat is running.


[float]
=== `beat.version`

The version of the beat that generated this event.


[float]
=== `@timestamp`

type: date

example: August 26th 2016, 12:35:53.332

format: date

required: True

The timestamp when the event log record was generated.


[float]
=== `tags`

Arbitrary tags that can be set per Beat and per transaction type.


[float]
=== `fields`

type: object

Contains user configurable fields.


[float]
== error fields

Error fields containing additional info in case of errors.



[float]
=== `error.message`

type: text

Error message.


[float]
=== `error.code`

type: long

Error code.


[float]
=== `error.type`

type: keyword

Error type.


[[exported-fields-cloud]]
== Cloud provider metadata fields

Metadata from cloud providers added by the add_cloud_metadata processor.



[float]
=== `meta.cloud.provider`

example: ec2

Name of the cloud provider. Possible values are ec2, gce, or digitalocean.


[float]
=== `meta.cloud.instance_id`

Instance ID of the host machine.


[float]
=== `meta.cloud.instance_name`

Instance name of the host machine.


[float]
=== `meta.cloud.machine_type`

example: t2.medium

Machine type of the host machine.


[float]
=== `meta.cloud.availability_zone`

example: us-east-1c

Availability zone in which this host is running.


[float]
=== `meta.cloud.project_id`

example: project-x

Name of the project in Google Cloud.


[float]
=== `meta.cloud.region`

Region in which this host is running.


[[exported-fields-docker-processor]]
== Docker fields

beta[]
Docker stats collected from Docker.




[float]
=== `docker.container.id`

type: keyword

Unique container id.


[float]
=== `docker.container.image`

type: keyword

Name of the image the container was built on.


[float]
=== `docker.container.name`

type: keyword

Container name.


[float]
=== `docker.container.labels`

type: object

Image labels.


[[exported-fields-kubernetes-processor]]
== Kubernetes fields

beta[]
Kubernetes metadata added by the kubernetes processor




[float]
=== `kubernetes.pod.name`

type: keyword

Kubernetes pod name


[float]
=== `kubernetes.namespace`

type: keyword

Kubernetes namespace


[float]
=== `kubernetes.labels`

type: object

Kubernetes labels map


[float]
=== `kubernetes.annotations`

type: object

Kubernetes annotations map


[float]
=== `kubernetes.container.name`

type: keyword

Kubernetes container name


[float]
=== `kubernetes.container.image`

type: keyword

Kubernetes container image


