//////////////////////////////////////////////////////////////////////////
// This content is reused in the Legacy ingest pipeline
//////////////////////////////////////////////////////////////////////////

[[ingest-pipelines]]
=== Parse data using ingest pipelines

:append-legacy:
// tag::ingest-pipelines[]

Ingest pipelines preprocess and enrich APM documents before indexing them.
For example, a pipeline might define one processor that removes a field, and another that renames a field.
This can be useful for ensuring data security by removing or obfuscating sensitive information.
See <<apm-data-security,data security>> for more on this topic.

The default APM pipelines are defined in index templates that {fleet} loads into {es}.
{es} then uses the index pattern in these index templates to match pipelines to APM data streams.

[discrete]
[id="view-edit-default-pipelines{append-legacy}"]
=== View ingest pipelines

To view or edit a default pipelines in {kib},
select **Stack Management** > **Ingest Pipelines**.
Search for `apm`.

It is not currently possible to edit or add pipelines that persist through upgrades.

See {ref}/ingest.html[ingest node pipelines] for more information.

// end::ingest-pipelines[]