[[metadata-api]]
=== Metadata

Every new connection to the APM Server starts with a `metadata` stanza.
This provides general metadata concerning the other objects in the stream.

Rather than send this metadata information from the agent multiple times,
the APM Server hangs on to this information and applies it to other objects in the stream as necessary.

TIP: Metadata is stored under `context` when viewing documents in Elasticsearch.

* <<kubernetes-data>>
* <<metadata-schema>>
* <<metadata-service-schema>>
* <<metadata-process-schema>>
* <<metadata-system-schema>>
* <<metadata-user-schema>>

[[kubernetes-data]]
[float]
==== Kubernetes data

APM agents automatically read kubernetes data and send it to the APM Server.
In most instances, agents are able to read this data from inside the container.
If this is not the case, or if you wish to override this data, you can set environment variables for the agents to read.
These environment variable are set via the kubernetes https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#use-pod-fields-as-values-for-environment-variables[Downward API].
Here's how you would add the environment variables to your kubernetes pod spec:

[source,yaml]
----
         - name: KUBERNETES_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: KUBERNETES_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: KUBERNETES_POD_UID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid
----

The table below maps these environment variables to the APM metadata event field:

[options="header"]
|=====
|Environment variable |Metadata field name
|KUBERNETES_NODE_NAME |system.kubernetes.node.name
|KUBERNETES_POD_NAME |system.kubernetes.pod.name
|KUBERNETES_NAMESPACE |system.kubernetes.namespace
|KUBERNETES_POD_UID	|system.kubernetes.pod.uid
|=====

[[metadata-schema]]
[float]
==== Metadata Schema

APM Server uses JSON Schema to validate requests. The specification for metadata is defined on
{github_repo_link}/docs/spec/metadata.json[GitHub] and included below:

[source,json]
----
include::./spec/metadata.json[]
----

[[metadata-service-schema]]
[float]
===== Service Schema

[source,json]
----
include::./spec/service.json[]
----

[[metadata-process-schema]]
[float]
===== Process Schema

[source,json]
----
include::./spec/process.json[]
----

[[metadata-system-schema]]
[float]
===== System Schema

[source,json]
----
include::./spec/system.json[]
----

[[metadata-user-schema]]
[float]
===== User Schema

[source,json]
----
include::./spec/user.json[]
----