[[open-telemetry]]
== OpenTelemetry integration

:ot-what:       https://opentelemetry.io/docs/concepts/what-is-opentelemetry/
:ot-spec:       https://github.com/open-telemetry/opentelemetry-specification/blob/master/README.md
:ot-grpc:       https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#otlpgrpc
:ot-http:       https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#otlphttp
:ot-contrib:    https://github.com/open-telemetry/opentelemetry-collector-contrib
:ot-resource:   {ot-contrib}/tree/main/processor/resourceprocessor
:ot-attr:       {ot-contrib}/blob/main/processor/attributesprocessor
:ot-repo:       https://github.com/open-telemetry/opentelemetry-collector
:ot-pipelines:  https://opentelemetry.io/docs/collector/configuration/#service
:ot-extension:  {ot-repo}/blob/master/extension/README.md
:ot-scaling:    {ot-repo}/blob/master/docs/performance.md

:ot-collector:  https://opentelemetry.io/docs/collector/getting-started/
:ot-dockerhub:  https://hub.docker.com/r/otel/opentelemetry-collector-contrib

{ot-what}[OpenTelemetry] is a set of APIs, SDKs, tooling, and integrations that enable the capture and management of
telemetry data from your services and applications. For more information about the
OpenTelemetry project, see the {ot-spec}[spec].

[float]
== OpenTelemetry and the {stack}

[subs=attributes+]
include::./diagrams/apm-otel-architecture.asciidoc[Architecture of Elastic APM with OpenTelemetry]

Elastic integrates with OpenTelemetry, allowing you to reuse your existing instrumentation
to easily send observability data to the {stack}.
There are four ways to integrate OpenTelemetry with the {stack}:

**OpenTelemetry API/SDK with Elastic APM agents**

To unlock the full power of the {stack}, use the OpenTelemetry API/SDKs with Elastic APM agents,
currently supported by the Java, Python, .NET, and Node.js agents.
These Elastic APM agents translate OpenTelemetry API calls to Elastic APM API calls.
This allows you to reuse your existing instrumentation to create Elastic APM transactions and spans--
avoiding vendor lock-in and having to redo manual instrumentation.

<<open-telemetry-with-elastic,Get started>>.

**OpenTelemetry agent**

The {stack} natively supports the OpenTelemetry protocol (OTLP).
This means trace data and metrics collected from your applications and infrastructure by an
OpenTelemetry agent can be sent directly to the {stack}.

<<instrument-apps-otel,Get started>>.

**OpenTelemetry collector**

The {stack} natively supports the OpenTelemetry protocol (OTLP).
This means trace data and metrics collected from your applications and infrastructure by an
OpenTelemetry collector can be sent directly to the {stack}.

<<connect-open-telemetry-collector,Get started>>.

**Lambda collector exporter**

AWS Lambda functions can be instrumented with OpenTelemetry and monitored with Elastic {observability}.

<<open-telemetry-aws-lambda,Get started>>.

include::./otel-with-elastic.asciidoc[]

include::./otel-direct.asciidoc[]

include::./otel-other.asciidoc[]

include::./otel-metrics.asciidoc[]

include::./otel-limitations.asciidoc[]

include::./otel-attrs.asciidoc[]

// ****
// The text below is used in the Quick start guide
// tag::otel-get-started[]
Elastic integrates with OpenTelemetry, allowing you to reuse your existing instrumentation
to easily send observability data to the {stack}.

For more information on how to combine Elastic and OpenTelemetry,
see {apm-guide-ref}/open-telemetry.html[OpenTelemetry integration].
// end::otel-get-started[]
// ****