[[open-telemetry-collect-metrics]]
=== Collect metrics

IMPORTANT: When collecting metrics, please note that the https://www.javadoc.io/doc/io.opentelemetry/opentelemetry-api/latest/io/opentelemetry/api/metrics/DoubleValueRecorder.html[`DoubleValueRecorder`]
and https://www.javadoc.io/doc/io.opentelemetry/opentelemetry-api/latest/io/opentelemetry/api/metrics/LongValueObserver.html[`LongValueRecorder`] metrics are not yet supported.

Here's an example of how to capture business metrics from a Java application.

[source,java]
----
// initialize metric
Meter meter = GlobalMetricsProvider.getMeter("my-frontend");
DoubleCounter orderValueCounter = meter.doubleCounterBuilder("order_value").build();

public void createOrder(HttpServletRequest request) {

   // create order in the database
   ...
   // increment business metrics for monitoring
   orderValueCounter.add(orderPrice);
}
----

See the https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md[Open Telemetry Metrics API]
for more information.

[float]
[[open-telemetry-verify-metrics]]
==== Verify OpenTelemetry metrics data

Use *Discover* to validate that metrics are successfully reported to {kib}.

. Launch {kib}:
+
--
include::{tab-widget-dir}/open-kibana-widget.asciidoc[]
--

. Open the main menu, then click *Discover*.
. Select `apm-*` as your index pattern.
<<<<<<< HEAD
. Filter the data to only show documents with metrics: `processor.name :"metric"`
=======
. Filter the data to only show documents with metrics: `[data_stream][type]: "metrics"`
>>>>>>> 6174ffdf6 (docs: Remove references to `processor.event` (#12013))
. Narrow your search with a known OpenTelemetry field. For example, if you have an `order_value` field, add `order_value: *` to your search to return
only OpenTelemetry metrics documents.

[float]
[[open-telemetry-visualize]]
==== Visualize in {kib}

Use *Lens* to create visualizations for OpenTelemetry metrics. Lens enables you to build visualizations by dragging and dropping data fields. It makes smart visualization suggestions for your data, allowing you to switch between visualization types.

For more information on using Lens, refer to the {kibana-ref}/lens.html[Lens documentation].
