[[open-telemetry-known-limitations]]
=== Limitations

[float]
[[open-telemetry-traces-limitations]]
==== OpenTelemetry traces

* Traces of applications using `messaging` semantics might be wrongly displayed as `transactions` in the APM UI, while they should be considered `spans` (see issue https://github.com/elastic/apm-server/issues/7001[#7001]).
* Inability to see Stack traces in spans.
* Inability in APM views to view the "Time Spent by Span Type"  (see issue https://github.com/elastic/apm-server/issues/5747[#5747]).

[float]
[[open-telemetry-metrics-limitations]]
==== OpenTelemetry metrics

* Inability to see host metrics in Elastic Metrics Infrastructure view when using the OpenTelemetry Collector host metrics receiver (see issue https://github.com/elastic/apm-server/issues/5310[#5310]).

[float]
[[open-telemetry-logs-intake]]
==== OpenTelemetry logs

* preview:[] The OpenTelemetry logs intake via APM Server is in technical preview.
* The application logs data stream (`app_logs`) has dynamic mapping disabled. This means the automatic detection and mapping of new fields is disabled (see issue https://github.com/elastic/apm-server/issues/9093[#9093]).

[float]
[[open-telemetry-otlp-limitations]]
==== OpenTelemetry Line Protocol (OTLP)

APM Server supports both the {ot-grpc}[(OTLP/gRPC)] and {ot-http}[(OTLP/HTTP)] protocol with ProtoBuf payload.
APM Server does not yet support JSON Encoding for OTLP/HTTP.

[float]
[[open-telemetry-collector-exporter]]
==== OpenTelemetry Collector exporter for Elastic

The https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/elasticexporter#legacy-opentelemetry-collector-exporter-for-elastic[OpenTelemetry Collector exporter for Elastic]
was deprecated in 7.13 and replaced by the native support of the OpenTelemetry Line Protocol in
Elastic {observability} (OTLP). To learn more, see
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/elasticexporter#migration[migration].

[float]
[[open-telemetry-tbs]]
==== OpenTelemetry's tail-based sampling

Tail-based sampling allows to make sampling decisions after all spans of a trace have been completed.
This allows for more powerful and informed sampling rules.

When using OpenTelemetry with Elastic APM, there are two different implementations available for tail-based sampling:

* Tail-based sampling using the https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor[tailsamplingprocessor] in the OpenTelemetry Collector
* Native <<tail-based-sampling,tail-based sampling in the Elastic APM backend>>

Using the https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor[tailsamplingprocessor] in the OpenTelemetry Collector comes with an important limitation. Elastic's APM backend calculates span and transaction metrics based on the incoming span events.
These metrics are accurate for 100% sampling scenarios. In scenarios with probabilistic sampling, Elastic's APM backend is being informed about the sampling rate of spans and can extrapolate throughput metrics based on the incoming, partial data. However, with tail-based sampling there's no clear probability for sampling decisions as the rules can be more complex. Therefore, there's no way for the Elastic APM to properly extrapolate throughput and count metrics that are derived from tail-based-sampled span events. In these scenarios, derived throughput and count metrics are likely to be inaccurate.

Therefore, we recommend using Elastic's native tail-based smapling when integrating with OpenTelemetry. 
