[[overview]]
== Overview

The APM Server receives data from APM agents and transforms them into Elasticsearch documents.

It works by exposing an HTTP server to which agents post the APM data they collect.

APM Server is built with the Beats framework,
and as such it leverages its functionality.

To get an overview of the whole Elastic APM system,
 also have a look at:

* {apm-node-ref}/index.html[APM Node.js Agent]
* {apm-py-ref}/index.html[APM Python Agent]
* {apm-ruby-ref}/index.html[APM Ruby Agent]
* {apm-rum-ref}/index.html[APM RUM JavaScript Agent]
* {ref}/index.html[Elasticsearch]


[[why-separate-component]]
=== Why is APM Server a separate component?

The APM Server is a separate component for the following reasons:

* It helps to keep the agents as light as possible and since the APM Server is a stateless separate component,
it can be scaled independently.
* For Real User monitoring data is collected in browsers.
  APM Server prevents browsers from interacting directly with Elasticsearch (which poses a security risk),
  and controls the amount of data flowing into Elasticsearch.
* In cases where Elasticsearch becomes unresponsive,
APM Server can buffer data temporarily without adding overhead to the agents.
* Acts as a middleware for source mapping for javascript in the browser.
* Provides a JSON API for agents to use thereby improving compatibility across different versions of agents and the Elastic Stack.
