[[secret-token]]
=== Secret token

IMPORTANT: Secret tokens are sent as plain-text,
so they only provide security when used in combination with <<agent-tls,TLS>>.

When defined, secret tokens are used to authorize requests to the APM Server.
Both the {apm-agent} and APM Server must be configured with the same secret token for the request to be accepted.

To secure the communication between APM agents and the APM Server with a secret token:

. Make sure <<agent-tls,TLS>> is enabled
. <<create-secret-token,Create a secret token>>
. <<configure-secret-token,Configure the secret token in your APM agents>>

NOTE: Secret tokens are not applicable for the RUM Agent,
as there is no way to prevent them from being publicly exposed.

[float]
[[create-secret-token]]
=== Create a secret token

// lint ignore fleet
NOTE: {ess} and {ece} deployments provision a secret token when the deployment is created.
The secret token can be found and reset in the {ecloud} console under **Deployments** -- **APM & Fleet**.

include::{tab-widget-dir}/secret-token-widget.asciidoc[]

[[configure-secret-token]]
[float]
=== Configure the secret token in your APM agents

Each Elastic {apm-agent} has a configuration option to set the value of the secret token:

* *Go agent*: {apm-go-ref}/configuration.html#config-secret-token[`ELASTIC_APM_SECRET_TOKEN`]
* *iOS agent*: {apm-ios-ref-v}/configuration.html#secretToken[`secretToken`]
* *Java agent*: {apm-java-ref}/config-reporter.html#config-secret-token[`secret_token`]
* *.NET agent*: {apm-dotnet-ref}/config-reporter.html#config-secret-token[`ELASTIC_APM_SECRET_TOKEN`]
* *Node.js agent*: {apm-node-ref}/configuration.html#secret-token[`Secret Token`]
* *PHP agent*: {apm-php-ref-v}/configuration-reference.html#config-secret-token[`secret_token`]
* *Python agent*: {apm-py-ref}/configuration.html#config-secret-token[`secret_token`]
* *Ruby agent*: {apm-ruby-ref}/configuration.html#config-secret-token[`secret_token`]

In addition to setting the secret token, ensure the configured server URL uses `HTTPS` instead of `HTTP`:

* *Go agent*: {apm-go-ref}/configuration.html#config-server-url[`ELASTIC_APM_SERVER_URL`]
* *Java agent*: {apm-java-ref}/config-reporter.html#config-server-urls[`server_urls`]
* *.NET agent*: {apm-dotnet-ref}/config-reporter.html#config-server-url[`ServerUrl`]
* *Node.js agent*: {apm-node-ref}/configuration.html#server-url[`serverUrl`]
* *PHP agent*: {apm-php-ref-v}/configuration-reference.html#config-server-url[`server_url`]
* *Python agent*: {apm-py-ref}/[`server_url`]
* *Ruby agent*: {apm-ruby-ref}/configuration.html#config-server-url[`server_url`]