
[[setting-up-and-running]]
== Setting up and running APM Server

In a production environment,
you would put APM Server on its own machines,
similar to how you run Elasticsearch.
You _can_ run it on the same machines as Elasticsearch,
but this is not recommended,
as the processes will be competing for resources.
To start APM Server, run:

[source,bash]
----------------------------------
./apm-server -e
----------------------------------

You should see APM Server start up.
It will try to connect to Elasticsearch on localhost port 9200 and expose an API to agents on port 8200.
You can change the defaults by supplying a different address on the command line:

[source,bash]
----------------------------------
./apm-server -e -E output.elasticsearch.hosts=ElasticsearchAddress:9200 -E apm-server.host=localhost:8200
----------------------------------

[[apm-server-configuration]]
=== Configuration file
To configure APM Server, you can also update the `apm-server.yml` configuration file.

For rpm and deb,
you’ll find the configuration file at +/etc/{beatname_lc}/{beatname_lc}.yml+.
There's also a full example configuration file at
+/etc/{beatname_lc}/{beatname_lc}.reference.yml+ that shows all non-deprecated
options. For mac and win, look in the archive that you extracted.

See {libbeat}/config-file-format.html[Config File Format] in _Beats Platform Reference_ for more about the structure of the config file.

[source,yaml]
----------------------------------
apm-server:
  host: localhost:8200

output:
  elasticsearch:
    hosts: ElasticsearchAddress:9200
----------------------------------


NOTE: If you are using an X-Pack secured version of Elastic Stack,
you need to specify credentials in the config file before you run the commands that set up and start APM Server.
For example:

[source,yaml]
----
output.elasticsearch:
  hosts: ["ElasticsearchAddress:9200"]
  username: "elastic"
  password: "elastic"
----

If you plan to use the sample Kibana dashboards provided with {beatname_uc},
configure the Kibana endpoint:

[source,yaml]
----------------------------------------------------------------------
setup.kibana:
  host: "localhost:5601"
----------------------------------------------------------------------

--
Where `host` is the hostname and port of the machine where Kibana is running,
for example, `localhost:5601`.

NOTE: If you specify a path after the port number, you need to include
the scheme and port: `http://localhost:5601/path`.

--

See <<configuring-howto-apm-server>> for more configuration options.


include::./high-availability.asciidoc[]

include::./security.asciidoc[]

include::./dashboards.asciidoc[]

include::./copied-from-beats/keystore.asciidoc[]

include::./copied-from-beats/command-reference.asciidoc[]

include::./copied-from-beats/shared-directory-layout.asciidoc[]

include::./copied-from-beats/shared-docker.asciidoc[]
