[[sourcemap-api]]
== Sourcemap Upload API

The APM Server exposes an API endpoint to upload source maps for <<rum, real user monitoring (RUM)>>.

[[sourcemap-endpoint]]
[float]
=== Upload endpoint
Send a `HTTP POST` request with the `Content-Type` header set to `multipart/form-data` to the source map endpoint:

[source,bash]
------------------------------------------------------------
http(s)://{hostname}:{port}/assets/v1/sourcemaps
------------------------------------------------------------

NOTE: The URL for uploading sourcemaps was previously `/v1/sourcemaps`. It still works, but is being deprecated in favor of `/assets/v1/sourcemaps`.

[[sourcemap-request-fields]]
[float]
==== Request Fields
The request must include some fields needed to identify `source map` correctly later on:

* `service_name`
* `service_version`
* `bundle_filepath`: needs to be the absolute path of the final bundle as it is used in the web application

The source map must follow the
https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k[Source map revision 3 proposal] spec and be attached as a `file upload`.

You can configure a <<secret-token, secret token>> to upload sourcemaps.

[[sourcemap-api-examples]]
[float]
==== Example

Example source map request including an optional <<secret-token, secret token>> "mysecret":

["source","sh",subs="attributes"]
---------------------------------------------------------------------------
curl -X POST http://127.0.0.1:8200/assets/v1/sourcemaps \
  -H "Authorization: Bearer mysecret" \
  -F service_name="test-service" \
  -F service_version="1.0" \
  -F bundle_filepath="http://localhost/static/js/bundle.js" \
  -F sourcemap=@bundle.js.map
---------------------------------------------------------------------------

