[[spans]]
=== Spans

A span contains information about a specific code path, 
executed as part of a <<transactions,transaction>>. 
Every span is identified by an ID unique per transaction.

Elastic APM agents automatically instrument a variety of libraries, 
but also support custom instrumentation for code paths.

Every code path that is captured by an agent creates a span.
Spans at least collect information about when the code path execution started, 
the duration, and the type of the code path execution.

This means, if for example a database query happens within a recorded transaction,
a span representing this database query will be created.
In such a case the name of the span will contain information about the query itself,
and the type will hold information about the database type. 

Some of the key attributes of a span are described in more detail:

[[span-context]]
[float]
==== Context
In case a database query was captured, the span's context contains information about this database access.
The context also contains information about the service the agent is monitoring.

[[span-span]]
[float]
==== Span
The information available within the span group includes the duration of the recorded span, 
an id unique within a transaction and an automatically retrieved name.
Additionally a span can contain `stack trace` information.

[[span-example]]
[float]
==== Example document

[source,json]
----
include::./data/elasticsearch/span.json[]
----

