[[agent-tls]]
=== {apm-agent} TLS communication

TLS is disabled by default.
When TLS is enabled for APM Server inbound communication, agents will verify the identity
of the APM Server by authenticating its certificate.

When TLS is enabled, a certificate and corresponding private key are required.
The certificate and private key can either be issued by a trusted certificate authority (CA)
or be <<agent-self-sign,self-signed>>.

[float]
[[agent-self-sign]]
=== Use a self-signed certificate

[float]
[[agent-self-sign-1]]
==== Step 1: Create a self-signed certificate

The {es} distribution offers the `certutil` tool for the creation of self-signed certificates:

1. Create a CA: `./bin/elasticsearch-certutil ca --pem`. You'll be prompted to enter the desired
location of the output zip archive containing the certificate and the private key.
2. Extract the contents of the CA archive.
3. Create the self-signed certificate: `./bin/elasticsearch-certutil cert --ca-cert
<path-to-ca-crt>/ca.crt --ca-key <path-to-ca-key>/ca.key --pem --name localhost`
4. Extract the certificate and key from the resulted zip archive.

[float]
[[agent-self-sign-2]]
==== Step 2: Configure the APM Server

Enable TLS and configure the APM Server to point to the extracted certificate and key:

include::{tab-widget-dir}/tls-widget.asciidoc[]

[float]
[[agent-self-sign-3]]
==== Step 3: Configure APM agents

When the APM server uses a certificate that is not chained to a publicly-trusted certificate
(e.g. self-signed), additional configuration is required in the {apm-agent}:

* *Go agent*: certificate pinning through {apm-go-ref}/configuration.html#config-server-cert[`ELASTIC_APM_SERVER_CERT`]
* *Python agent*: certificate pinning through {apm-py-ref}/configuration.html#config-server-cert[`server_cert`]
* *Ruby agent*: certificate pinning through {apm-ruby-ref}/configuration.html#config-ssl-ca-cert[`server_ca_cert`]
* *.NET agent*: {apm-dotnet-ref}/config-reporter.html#config-server-cert[`ServerCert`]
* *Node.js agent*: custom CA setting through {apm-node-ref}/configuration.html#server-ca-cert-file[`serverCaCertFile`]
* *Java agent*: adding the certificate to the JVM `trustStore`.
See {apm-java-ref}/ssl-configuration.html#ssl-server-authentication[APM Server authentication] for more details.

We do not recommend disabling {apm-agent} verification of the server's certificate, but it is possible:

* *Go agent*: {apm-go-ref}/configuration.html#config-verify-server-cert[`ELASTIC_APM_VERIFY_SERVER_CERT`]
* *.NET agent*: {apm-dotnet-ref}/config-reporter.html#config-verify-server-cert[`VerifyServerCert`]
* *Java agent*: {apm-java-ref}/config-reporter.html#config-verify-server-cert[`verify_server_cert`]
* *PHP agent*: {apm-php-ref-v}/configuration-reference.html#config-verify-server-cert[`verify_server_cert`]
* *Python agent*: {apm-py-ref}/configuration.html#config-verify-server-cert[`verify_server_cert`]
* *Ruby agent*: {apm-ruby-ref}/configuration.html#config-verify-server-cert[`verify_server_cert`]
* *Node.js agent*: {apm-node-ref}/configuration.html#validate-server-cert[`verifyServerCert`]

[float]
[[agent-client-cert]]
=== Client certificate authentication

APM Server does not require agents to provide a certificate for authentication,
and there is no dedicated support for SSL/TLS client certificate authentication in Elastic’s backend agents.