[x-pack]
[[transaction-metrics]]
== Configure transaction metrics

++++
<titleabbrev>Transaction metrics</titleabbrev>
++++

When enabled, {beatname_uc} produces transaction histogram metrics that are used to power the APM app.
Shifting this responsibility from APM app to APM Server removes the need to store unsampled transactions, reducing storage costs.

Example config file:

["source","yaml"]
----
apm-server:
  aggregation:
    transactions:
      enabled: true
      interval: 1m
  sampling:
    keep_unsampled: false
----

[float]
[[configuration-aggregation]]
=== Configuration options: `apm-server.aggregation.transactions.*`

[[transactions-enabled]]
[float]
==== `enabled`

Enables the collection and publishing of transaction metrics.
Enabling this setting removes the need to store unsampled transactions, reducing storage costs.
Storing unsampled transactions is controlled independently with <<sampling-keep_unsampled>>.

Default: `true`.

IMPORTANT: To prevent inaccuracies in the APM app, transaction metrics must also be enabled in
Kibana with `xpack.apm.searchAggregatedTransactions`.
See {kibana-ref}/apm-settings-in-kibana.html[APM app settings] for more information.

[[transactions-interval]]
[float]
==== `interval`

Controls the frequency of metrics publication.

Default: `1m`.

[[transactions-max_groups]]
[float]
==== `max_groups`

Maximum number of transaction groups to keep track of.
Once exceeded, APM Server devolves into recording a metrics document for each transaction that is not in one
of the transaction groups being tracked.

Default: `10000`.

[[transactions-hdrhistogram_significant_figures]]
[float]
==== `hdrhistogram_significant_figures`

The fixed, worst-case percentage error (specified as a number of significant digits)
to maintain for recorded metrics.
Supported values are `1` through `5`.
See {ref}/search-aggregations-metrics-percentile-aggregation.html#_hdr_histogram_2[HDR histogram] for more information.

Default: `2`.

[float]
[[configuration-sampling]]
=== Configuration options: `apm-server.sampling.*`

[[sampling-keep_unsampled]]
[float]
==== `keep_unsampled`

Deprecated: `keep_unsampled` will default to `false` in 8.0, and later be removed.

Controls the recording of unsampled transaction documents.
Dropping unsampled documents (`keep_unsampled: false`) reduces APM's storage consumption.

Default: `true`.

IMPORTANT: Unsampled transactions should only be dropped when `apm-server.aggregation.transactions.enabled` is `true`,
otherwise, the APM app will report inaccurate metrics.
