[[transaction-indices]]
== Transaction Indices

Transactions are by default stored to indices of the format `apm-[version]-transaction-[date]`.
Read more about the general purpose of a <<transactions, transaction>>.

A transaction is identified by a unique ID and holds some meta information about the event.
It at least holds information about when the event started and the duration until it completed,
as well as information about the event type.

Some of the key attributes of a transaction are described in more detail:

[[transactions-context]]
include::./context.asciidoc[]

[[transaction-transaction]]
[float]

=== Transaction
The information available within the transaction group includes the duration of the transaction, 
a unique id, the type and an automatically retrieved name,
as well as an indication whether or not the transaction was handled successfully. 
The transaction can also contain:

* sampled: if a transaction was sampled, the spans of the transaction were captured and are available as seperate documents
* span_count.dropped: how many spans have not been captured, according to configuration on the agent side
* marks: captures the timing in milliseconds of a significant event during the lifetime of a transaction, set by the user or the agent

[[transaction-example]]
[float]
=== Example Document
See an example document of an indexed transaction:
[source,json]
----
include::./data/elasticsearch/transaction.json[]
----

