[[upgrading]]
= Upgrade APM Server

++++
<titleabbrev>Upgrade</titleabbrev>
++++

We do our best to keep APM Server backward compatible between minor releases.
Any exceptions will be explained in <<breaking-changes,breaking changes>>.

[discrete]
[[before-upgrading]]
=== Before upgrading

* Review the APM Server <<release-notes,release notes>> and <<breaking-changes,breaking changes>>
for changes between your current APM Server version and the one you are upgrading to.
* Review the APM stack {apm-overview-ref-v}/apm-breaking-changes.html[breaking changes] and Observability
{observability-guide}/whats-new.html[What's new in {minor-version}] for important changes to other APM components.

[discrete]
[[upgrade-order]]
=== Upgrade process

. The Elastic Stack (Elasticsearch and Kibana) must be upgraded before APM Server.
See the {stack-ref}/upgrading-elastic-stack.html[Elastic Stack Installation and Upgrade Guide] for guidance.

. If applicable, read and understand the relevant APM Server upgrading guide.
Guides exist for upgrades to versions
<<upgrading-to-77,`7.7`>>, <<upgrading-to-70,`7.0`>>, and <<upgrading-to-65,`6.5`>>.

. Install the new APM Server release.

. Review the `apm-server.yml` configuration file.
There may be newly added configuration options, and you'll want to be aware of their default settings.
See <<configuring-howto-apm-server,configuring>> for more information on available options.

. If you set up index patterns and dashboards manually by running `./apm-server setup`,
rerun the command to update the index pattern and the dashboards.

. Start the APM server.
+
When you start the APM server after upgrading, it creates new indices that use the current version,
and applies the correct template automatically.

include::./breaking-changes.asciidoc[]

// Adding a new upgrading guide?
// Be sure to also add it to the jump list above (step 2).
include::./upgrading-to-77.asciidoc[]

include::./upgrading-to-70.asciidoc[]

include::./upgrading-to-65.asciidoc[]
