[[upgrading-to-8.0]]
=== Upgrade to version 8.0

Version 8.0 of Elastic APM offers a number of benefits over previous versions:

* Reduced number of fields per index, better space efficiency, and faster queries
* More granular data control
* Errors and metrics data streams are shared with other data sources -- which means better long-term integration with the logs and metrics apps
* Removes template inheritance for index lifecycle policies and makes use of new {es} index and component templates

[float]
=== Notable changes

* APM setup has moved from APM Server to {fleet}.
* APM Server no longer writes to classic indices, and instead writes to data streams.

See the APM <<release-notes,release notes>>, <<apm-breaking,breaking changes>>,
and Observability {observability-guide}/whats-new.html[What's new] for full details.

[float]
=== Upgrade path

Starting in version 7.14, there are two methods of running Elastic APM.
Determine which method you're running, then use the links below to find the correct upgrading guide.

* Standalone (legacy): This mode has been deprecated and will be removed in a future release.
Users on standalone mode run the APM Server binary to collect, parse, and send data to the {stack}.
* {fleet} + APM integration: Users in this mode run {fleet} and the APM integration.

**Self-installation (non-{ecloud} users)**

* <<upgrade-8.0-self-standalone>>
* <<upgrade-8.0-self-integration>>

**{ecloud} users**

* <<upgrade-8.0-cloud-standalone>>
* <<upgrade-8.0-cloud-integration>>

// ********************************************************

[[upgrade-8.0-self-standalone]]
==== Upgrade self-installation standalone (legacy) to 8.0

. Upgrade to 7.17
+
Before upgrading to version 8.0, {es}, {kib},
and APM Server must be upgraded to version 7.17.
+
To upgrade {es} and {kib},
see the https://www.elastic.co/guide/en/elastic-stack/7.17/upgrading-elastic-stack.html[{stack} Installation and Upgrade Guide]
+
To upgrade APM Server to version 7.17, see
{apm-guide-7x}/upgrading-to-717.html[upgrade to version 7.17].

. Upgrade the {stack} to 8.0
+
The {stack} ({es} and {kib}) must be upgraded before APM.
See the {stack-ref}/upgrading-elastic-stack.html[{stack} Installation and Upgrade Guide] for guidance.

. Review the APM <<release-notes,release notes>>, <<apm-breaking,breaking changes>>,
and Observability {observability-guide}/whats-new.html[What's new] content.

. Install the APM integration via the {fleet} UI.
+
If you've previously installed the APM integration,
use the {fleet} UI to upgrade the APM integration to version {version}.

. Upgrade APM Server
+
<<installing,Install the new APM Server release>>.

. Review the `apm-server.yml` configuration file.
Some settings have been removed or changed.

. <<apm-server-starting,Start the APM Server>>

You should see your data flowing into the APM app again.


IMPORTANT: If you upgrade APM Server to version 8.0 BEFORE installing the APM integration, you will see logs similar to the following about the APM integration not being installed:

[source,json]
----
...
{"log.level":"error","@timestamp":"2022-01-19T10:45:34.923+0800","log.logger":"beater","log.origin":{"file.name":"beater/waitready.go","file.line":62},"message":"precondition 'apm integration installed' failed: error querying Elasticsearch for integration index templates: unexpected HTTP status: 404 Not Found ({\"error\":{\"root_cause\":[{\"type\":\"resource_not_found_exception\",\"reason\":\"index template matching [traces-apm.sampled] not found\"}],\"type\":\"resource_not_found_exception\",\"reason\":\"index template matching [traces-apm.sampled] not found\"},\"status\":404}): to remediate, please install the apm integration: https://ela.st/apm-integration-quickstart","service.name":"apm-server","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-01-19T10:45:37.461+0800","log.logger":"beater","log.origin":{"file.name":"beater/waitready.go","file.line":62},"message":"precondition 'apm integration installed' failed: error querying Elasticsearch for integration index templates: unexpected HTTP status: 404 Not Found ({\"error\":{\"root_cause\":[{\"type\":\"resource_not_found_exception\",\"reason\":\"index template matching [logs-apm.error] not found\"}],\"type\":\"resource_not_found_exception\",\"reason\":\"index template matching [logs-apm.error] not found\"},\"status\":404}): to remediate, please install the apm integration: https://ela.st/apm-integration-quickstart","service.name":"apm-server","ecs.version":"1.6.0"}
...
----

OPTIONAL: UPGRADE TO THE APM INTEGRATION

// ********************************************************

[[upgrade-8.0-self-integration]]
==== Upgrade self-installation APM integration to 8.0

. Upgrade to 7.17
+
Before upgrading to version 8.0, {es} and {kib},
must be upgraded to version 7.17.
+
To upgrade {es} and {kib},
see the https://www.elastic.co/guide/en/elastic-stack/7.17/upgrading-elastic-stack.html[{stack} Installation and Upgrade Guide]

. Upgrade the {stack} to 8.0
+
The {stack} ({es} and {kib}) must be upgraded before {agent}.
See the {stack-ref}/upgrading-elastic-stack.html[{stack} Installation and Upgrade Guide] for guidance.

. Review the APM <<release-notes,release notes>>, <<apm-breaking,breaking changes>>,
and Observability {observability-guide}/whats-new.html[What's new] content.

. Upgrade the APM integration to version 8.0.
// happens automatically

. Upgrade {agent} to 8.0
+
To upgrade {agent}, see {fleet-guide}/upgrade-elastic-agent.html[Upgrade {agent}]

You should see your data flowing into the APM app again.

// ********************************************************

[[upgrade-8.0-cloud-standalone]]
==== Upgrade {ecloud} standalone (legacy) to 8.0

Review the APM <<release-notes,release notes>>, <<apm-breaking,breaking changes>>,
and Observability {observability-guide}/whats-new.html[What's new] content.

To upgrade your {ecloud} standalone instance to 8.0,
see https://www.elastic.co/guide/en/cloud/current/ec-upgrade-deployment.html[Upgrade versions].

Some settings have been changed or removed in version 8.0.
See https://www.elastic.co/guide/en/cloud/current/ec-manage-apm-settings.html
for details on which settings are available.

OPTIONAL: UPGRADE TO THE APM INTEGRATION

// ********************************************************

[[upgrade-8.0-cloud-integration]]
==== Upgrade {ecloud} APM integration to 8.0

Review the APM <<release-notes,release notes>>, <<apm-breaking,breaking changes>>,
and Observability {observability-guide}/whats-new.html[What's new] content.

To upgrade your {ecloud} {fleet} + APM integration instance to 8.0,
see https://www.elastic.co/guide/en/cloud/current/ec-upgrade-deployment.html[Upgrade versions].
