[[upgrading]]
== Upgrade APM Server

++++
<titleabbrev>Upgrade</titleabbrev>
++++

We do our best to keep APM Server backward compatible between minor releases.
However, check out the <<breaking-changes, breaking changes>> section for exceptions.

Before upgrading:

* Review the APM Server <<release-notes,release notes>> and <<breaking-changes, breaking changes>>
for changes between your current APM Server version and the one you are upgrading to.
* Visit the general APM {apm-overview-ref-v}/apm-release-notes.html[release highlights] and {apm-overview-ref-v}/apm-breaking-changes.html[breaking changes] for highlights and important changes.
* Check the {stack-ref}/index.html[Elastic Stack Installation and Upgrade Guide] for guidance on how to upgrade your Elastic Stack.

When you're ready to upgrade your APM Server between minor versions,
simply install the new release.

You'll want to take a look at the `apm-server.yml` configuration file after installing a new release.
There may be newly added configuration options, and you'll want to be aware of their default settings.
See <<configuring-howto-apm-server,Configuring APM Server>> for more information on available configuration options.

If you set up index patterns and dashboards manually by running `./apm-server setup`,
rerun the command to update the index pattern and the dashboards.

When everything is properly configured and updated, start the APM server.

When you start the APM server after upgrading, it creates new indices that use the current version,
and applies the correct template automatically.

include::./breaking-changes.asciidoc[]

include::./upgrading-to-65.asciidoc[]

include::./upgrading-to-70.asciidoc[]

include::./upgrading-to-77.asciidoc[]
