[[upgrading-to-8.x]]
=== Upgrade to version {version}

Version 8.0 of Elastic APM offers a number of benefits over previous versions:

* Reduced number of fields per index, better space efficiency, and faster queries
* More granular data control
* Errors and metrics data streams are shared with other data sources -- which means better long-term integration with the logs and metrics apps
* Removes template inheritance for index lifecycle policies and makes use of new {es} index and component templates

[float]
=== Notable changes

* All index management has been removed from APM Server;
{fleet} is now entirely responsible for setting up index templates, index lifecycle polices,
and index pipelines.
* APM Server now only writes to well-defined data streams;
writing to classic indices is no longer supported.
* APM Server has a new {es} output implementation with defaults that should be sufficient for
most use cases.

As a result of the above changes,
a number of index management and index tuning configuration variables have been removed.
See the APM <<release-notes,release notes>>, <<apm-breaking,breaking changes>>,
and Observability {observability-guide}/whats-new.html[What's new] for full details.

[float]
=== Upgrade path

Starting in version 7.14, there are two ways to run Elastic APM.
Determine which method you're using, then use the links below to find the correct upgrading guide.

* **Standalone (legacy)**: Users in this mode run and configure the APM Server binary.
This mode has been deprecated and will be removed in a future release.
* **{fleet} and the APM integration**: Users in this mode run and configure {fleet} and the Elastic APM integration.

**Self-installation (non-{ecloud} users) upgrade guides**

* <<upgrade-8.0-self-standalone>>
* <<upgrade-8.0-self-integration>>

**{ecloud} upgrade guides**

* <<upgrade-8.0-cloud-standalone>>
* <<upgrade-8.0-cloud-integration>>

// ********************************************************

[[upgrade-8.0-self-standalone]]
==== Upgrade a self-installation of APM Server standalone to {version}

++++
<titleabbrev>Self-installation standalone (legacy)</titleabbrev>
++++

This upgrade guide is for the standalone (legacy) method of running APM Server.
Only use this guide if both of the following are true:

* You have a self-installation of the {stack}, i.e. you're not using {ecloud}.
* You're running the APM Server binary, i.e. you haven't upgraded to the Elastic APM integration.

[float]
==== Prerequisites

* Prior to upgrading to version {version}, {es}, {kib},
and APM Server must be upgraded to version 7.17.
** To upgrade {es} and {kib},
see the https://www.elastic.co/guide/en/elastic-stack/7.17/upgrading-elastic-stack.html[{stack} Installation and Upgrade Guide]
** To upgrade APM Server to version 7.17, see
{apm-guide-7x}/upgrading-to-717.html[upgrade to version 7.17].

* Review the APM <<release-notes,release notes>>, <<apm-breaking,breaking changes>>,
and Observability {observability-guide}/whats-new.html[What's new] content.

[float]
==== Upgrade steps

. **Upgrade the {stack} to version 8.0**
+
The {stack} ({es} and {kib}) must be upgraded before APM.
See the {stack-ref}/upgrading-elastic-stack.html[{stack} Installation and Upgrade Guide] for guidance.

. **Install the APM integration via the {fleet} UI**
+
If you've previously installed the APM integration,
use the {fleet} UI to upgrade the APM integration to version {version}.

. **Upgrade APM Server**
+
See <<installing,install the new APM Server release>> for instructions.
+
[WARNING]
====
If you upgrade APM Server to version 8.0.0 before installing the APM integration, you will see error logs similar to the following. You must go back and install the APM integration before data can be ingested in {es}.
+
[source,json]
----
...
{"log.level":"error","@timestamp":"2022-01-19T10:45:34.923+0800","log.logger":"beater","log.origin":{"file.name":"beater/waitready.go","file.line":62},"message":"precondition 'apm integration installed' failed: error querying Elasticsearch for integration index templates: unexpected HTTP status: 404 Not Found ({\"error\":{\"root_cause\":[{\"type\":\"resource_not_found_exception\",\"reason\":\"index template matching [traces-apm.sampled] not found\"}],\"type\":\"resource_not_found_exception\",\"reason\":\"index template matching [traces-apm.sampled] not found\"},\"status\":404}): to remediate, please install the apm integration: https://ela.st/apm-integration-quickstart","service.name":"apm-server","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-01-19T10:45:37.461+0800","log.logger":"beater","log.origin":{"file.name":"beater/waitready.go","file.line":62},"message":"precondition 'apm integration installed' failed: error querying Elasticsearch for integration index templates: unexpected HTTP status: 404 Not Found ({\"error\":{\"root_cause\":[{\"type\":\"resource_not_found_exception\",\"reason\":\"index template matching [logs-apm.error] not found\"}],\"type\":\"resource_not_found_exception\",\"reason\":\"index template matching [logs-apm.error] not found\"},\"status\":404}): to remediate, please install the apm integration: https://ela.st/apm-integration-quickstart","service.name":"apm-server","ecs.version":"1.6.0"}
...
----
====

. **Review your configuration file**
+
Some settings have been removed or changed. You may need to update your `apm-server.yml` configuration
file prior to starting the APM Server.
See <<directory-layout>> for help in locating this file,
and <<configuring-howto-apm-server>> for a list of all available configuration options.

. **Start the APM Server**
+
See <<apm-server-starting,start the APM Server>>.
You should see your data flowing into the APM app again.

. **(Optional) Upgrade to the APM integration**
+
Got time for one more upgrade?
See <<upgrade-to-apm-integration>>.

// ********************************************************

[[upgrade-8.0-self-integration]]
==== Upgrade a self-installation of the APM integration to {version}

++++
<titleabbrev>Self-installation APM integration</titleabbrev>
++++

This upgrade guide is for the Elastic APM integration.
Only use this guide if both of the following are true:

* You have a self-installation of the {stack}, i.e. you're not using {ecloud}.
* You have already upgraded to and are running {fleet} and the Elastic APM integration.

[float]
==== Prerequisites

* Prior to upgrading to version {version}, {es}, and {kib}
must be upgraded to version 7.17. To upgrade {es} and {kib},
see the https://www.elastic.co/guide/en/elastic-stack/7.17/upgrading-elastic-stack.html[{stack} Installation and Upgrade Guide]

* Review the APM <<release-notes,release notes>>, <<apm-breaking,breaking changes>>,
and Observability {observability-guide}/whats-new.html[What's new] content.

[float]
==== Upgrade steps

. Upgrade the {stack} to 8.0
+
The {stack} ({es} and {kib}) must be upgraded before {agent}.
See the {stack-ref}/upgrading-elastic-stack.html[{stack} Installation and Upgrade Guide] for guidance.

. Upgrade the APM integration to version 8.0.
// happens automatically

. Upgrade {agent} to 8.0
+
To upgrade {agent}, see {fleet-guide}/upgrade-elastic-agent.html[Upgrade {agent}]

You should see your data flowing into the APM app again.

// ********************************************************

[[upgrade-8.0-cloud-standalone]]
==== Upgrade {ecloud} APM Server standalone to {version}

++++
<titleabbrev>{ecloud} standalone (legacy)</titleabbrev>
++++

. Review the APM <<release-notes,release notes>>, <<apm-breaking,breaking changes>>,
and Observability {observability-guide}/whats-new.html[What's new] content.

. Upgrade {ecloud} to {version},
See https://www.elastic.co/guide/en/cloud/current/ec-upgrade-deployment.html[Upgrade versions] for instructions.

. (Optional) Upgrade to the APM integration
+
Got time for one more upgrade?
See <<upgrade-to-apm-integration>>.

// ********************************************************

[[upgrade-8.0-cloud-integration]]
==== Upgrade {ecloud} with the APM integration to 8.0

++++
<titleabbrev>{ecloud} APM integration</titleabbrev>
++++

. Review the APM <<release-notes,release notes>>, <<apm-breaking,breaking changes>>,
and Observability {observability-guide}/whats-new.html[What's new] content.

. Upgrade your {ecloud} instance to {version}.
The APM integration will automatically be upgraded to version {version} as a part of this process.
See https://www.elastic.co/guide/en/cloud/current/ec-upgrade-deployment.html[Upgrade versions] for instructions.

NOTE: {ece} users require additional TLS setup.
See {ece-ref}/ece-manage-apm-settings.html[Add APM user settings] for more information.
