---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apm-server-config
  labels:
    k8s-app: apm-server
data:
  apm-server.yml: |-
    apm-server:
      host: "0.0.0.0:8200"
      instrumentation:
        enabled: true
      register.ingest.pipeline:
        enabled: true

    cloud.id: ${ELASTIC_CLOUD_ID}
    cloud.auth: ${ELASTIC_CLOUD_AUTH}

    output.elasticsearch:
      hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apm-server-env
  labels:
    k8s-app: apm-server
data:
  # CLOUD_ID:
  ELASTICSEARCH_HOST: elasticsearch
  ELASTICSEARCH_PORT: "9200"
---
apiVersion: v1
kind: Secret
metadata:
  name: apm-server-secret
type: Opaque
data:
  cloud_auth: ""
  elasticsearch_password: Y2hhbmdlbWUK
  elasticsearch_username: YXBtLXNlcnZlci11c2VyCg==
