---
description: Pipeline for ingesting APM trace events.
processors:
  - set:
      field: event.ingested
      value: "{{_ingest.timestamp}}"
  - user_agent:
      field: user_agent.original
      target_field: user_agent
      ignore_missing: true
      ignore_failure: true
  - geoip:
      database_file: GeoLite2-City.mmdb
      field: client.ip
      target_field: client.geo
      ignore_missing: true
      on_failure:
        - remove:
            field: client.ip
            ignore_missing: true
            ignore_failure: true
  - remove:
      # Remove some metadata from spans that is available in the parent transaction, to cut down on storage costs.
      if: ctx.processor?.event == 'span'
      field:
        - host
        - process
        - user
        - user_agent
        - container
        - kubernetes
        - service.node
        - service.version
        - service.language
        - service.runtime
        - service.framework
      ignore_missing: true
      ignore_failure: true

