name: benchmarks-matrix

on:
  workflow_dispatch:
    inputs:
      profileJSON:
        description: 'JSON list of system profile for benchmark, e.g. ["system-profiles/8GBx1zone.tfvars"]'
        required: true
        type: string
      runStandalone:
        description: 'Benchmark against standalone APM Server with Moxy'
        required: false
        type: boolean
        default: false
      enableTailSampling:
        description: 'Enable tail-based sampling on APM server'
        required: false
        type: boolean
        default: false
      tailSamplingStorageLimit:
        description: 'Storage size limit of tail-based sampling on APM server'
        required: false
        type: string
        default: "10GB"
        # defaults set below (TFVARS_SOURCE)
      runOnStable:
        description: 'Benchmark on latest stable version'
        required: false
        type: boolean
        default: false
      benchmarkAgents:
        description: 'Number of benchmark agents sending data to APM Server'
        required: false
        type: string
        # defaults set in Makefile
      benchmarkRun:
        description: 'Benchmark scenarios that only match regex, e.g. BenchmarkAgentAll'
        required: false
        type: string
        # defaults set in Makefile
      warmupTime:
        description: 'Benchmark warmup time for APM Server e.g. 3s, 5m, 2h'
        required: false
        type: string
        # defaults set below (Set up env)

permissions:
  contents: read

jobs:
  bench-matrix:
    strategy:
      matrix:
        profile: ${{ fromJSON(inputs.profileJSON)}}
    uses: ./.github/workflows/benchmarks.yml
    with:
      profile: ${{ matrix.profile }}
      benchmarkAgents: ${{ inputs.benchmarkAgents }}
      runStandalone: ${{ inputs.runStandalone }}
      enableTailSampling: ${{ inputs.enableTailSampling }}
      tailSamplingStorageLimit: ${{ inputs.tailSamplingStorageLimit }}
      runOnStable: ${{ inputs.runOnStable }}
      benchmarkRun: ${{ inputs.benchmarkRun }}
      warmupTime: ${{ inputs.warmupTime }}
