name: benchmarks-matrix

on:
  workflow_dispatch:
    inputs:
      profilesJSON:
        description: 'JSON list of system profiles for benchmark, e.g. ["system-profiles/8GBx1zone.tfvars"]'
        required: true
        type: string
      essRegionsJSON:
        description: 'JSON list of ESS regions, e.g. ["gcp-us-west2", "azure-westus2", "us-west-2"]'
        required: true
        type: string
      runStandalone:
        description: 'Benchmark against standalone APM Server with Moxy'
        required: false
        type: boolean
        default: false
      enableTailSampling:
        description: 'Enable tail-based sampling on APM server'
        required: false
        type: boolean
        default: false
      tailSamplingStorageLimit:
        description: 'Storage size limit of tail-based sampling on APM server'
        required: false
        type: string
      runOnStable:
        description: 'Benchmark on latest stable version'
        required: false
        type: boolean
        default: false
      benchmarkAgents:
        description: 'Number of benchmark agents sending data to APM Server'
        required: false
        type: string
      benchmarkRun:
        description: 'Benchmark scenarios that only match regex, e.g. BenchmarkAgentAll'
        required: false
        type: string
      warmupTime:
        description: 'Benchmark warmup time for APM Server e.g. 3s, 5m, 2h'
        required: false
        type: string

permissions:
  contents: read

jobs:
  bench-matrix:
    permissions:
      contents: write
      id-token: write
    strategy:
      matrix:
        profile: ${{ fromJSON(inputs.profilesJSON)}}
        essRegion: ${{ fromJSON(inputs.essRegionsJSON)}}
    uses: ./.github/workflows/benchmarks.yml
    with:
      profile: ${{ matrix.profile }}
      essRegion: ${{ matrix.essRegion }}
      benchmarkAgents: ${{ inputs.benchmarkAgents }}
      runStandalone: ${{ inputs.runStandalone }}
      enableTailSampling: ${{ inputs.enableTailSampling }}
      tailSamplingStorageLimit: ${{ inputs.tailSamplingStorageLimit }}
      runOnStable: ${{ inputs.runOnStable }}
      benchmarkRun: ${{ inputs.benchmarkRun }}
      warmupTime: ${{ inputs.warmupTime }}
