name: check-full

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * 5'

# limit the access of the generated GITHUB_TOKEN
permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: |
            go.sum
            tools/go.sum
      - run: make check-full
      - name: Ensure .go-version is up to date
        run: make update-go-version
