---
name: Comment on PR for .asciidoc changes

on:
  # We need to use pull_request_target to be able to comment on PRs from forks
  pull_request_target:
    types:
      - synchronize
      - opened
      - reopened
    branches:
      - main

jobs:
  comment-on-asciidoc-change:
    permissions:
      contents: read
      pull-requests: write
    uses: elastic/docs-builder/.github/workflows/comment-on-asciidoc-changes.yml@d20bc8650b8ea27a58ee6d17ed963659e878f993 # main
