name: docs-cleanup

on:
  pull_request_target:
    types:
      - closed

jobs:
  docs-preview:
    uses: elastic/docs-builder/.github/workflows/preview-cleanup.yml@6e63c07b451fbd28bbd3e777a31fedf756a09b7c # main
    permissions:
      contents: none
      id-token: write
      deployments: write
