---
name: functional-tests

on:
  workflow_dispatch: ~
  schedule:
    - cron: '0 3 * * 1-5'

permissions:
  contents: read
  id-token: write

env:
  TF_VAR_BRANCH: ${{ github.ref_name }}
  TF_VAR_BUILD_ID: ${{ github.run_id }}
  TF_VAR_ENVIRONMENT: 'ci'
  TF_VAR_REPO: ${{ github.repository }}
  TERRAFORM_VERSION: 1.10.2

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment:
          - 'qa'
          - 'pro'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4

      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: "${{ env.TERRAFORM_VERSION }}"

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v5
        with:
          go-version-file: 'functionaltests/go.mod'
          cache: false

      - uses: elastic/oblt-actions/google/auth@e1273cafad946cd6255c5c3ade06cce92ea77e33 # v1

      - uses: google-github-actions/get-secretmanager-secrets@bc9c54b29fdffb8a47776820a7d26e77b379d262 # v3.0.0
        with:
          export_to_environment: true
          secrets: |-
            EC_API_KEY:elastic-observability/elastic-cloud-observability-team-${{ matrix.environment }}-api-key

      - run: |
          export TF_VAR_CREATED_DATE=$(date +%s)
          cd functionaltests && go test -v -timeout=30m -target "${{ matrix.environment }}" ./

  notify:
    if: always()
    runs-on: ubuntu-latest
    needs:
      - run
    steps:
      - id: check
        uses: elastic/oblt-actions/check-dependent-jobs@v1
        with:
          jobs: ${{ toJSON(needs) }}
      - uses: elastic/oblt-actions/slack/notify-result@v1
        with:
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: "#apm-server"
          status: ${{ steps.check.outputs.status }}
