name: macos

on:
  pull_request:
  push:
    branches:
      - main
      - 7.1*
      - 8.*

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Fetch Go version from .go-version
      run: echo "GO_VERSION=$(cat .go-version)" >> $GITHUB_ENV
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Install dependencies
      run:  go get -u github.com/magefile/mage
    - name: Run build
      run: .ci/scripts/build.sh
    - name: Run test
      run: .ci/scripts/unit-test.sh
