name: macos

on:
  pull_request:
  push:
    branches:
      - main
      - 7.1*
      - 8.*


jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Fetch Go version from .go-version
      run: echo "GO_VERSION=$(cat .go-version)" >> $GITHUB_ENV
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true
    - name: Run tests
      run: |-
        go test -v ./...
