name: macos

on:
  pull_request:
  push:
    branches:
      - main
      - 7.1*
      - 8.*


jobs:
  macos:
    runs-on: macos-latest
    env:
      BASE_DIR: src/github.com/elastic/apm-server
    steps:
    - uses: actions/checkout@v3
      with:
        path: ${{ env.BASE_DIR }}
    - name: Fetch Go version from .go-version
      run: echo "GO_VERSION=$(cat .go-version)" >> $GITHUB_ENV
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Install dependencies
      run:  go get -u github.com/magefile/mage
    - name: Run build
      run: |-
        cd $BASE_DIR
        WORKSPACE=$GITHUB_WORKSPACE .ci/scripts/build.sh
    - name: Run test
      run: |-
        cd $BASE_DIR
        go get -u github.com/magefile/mage
        WORKSPACE=$GITHUB_WORKSPACE .ci/scripts/unit-test.sh
