name: package

on:
  workflow_call: ~
  push:
    branches:
      - main
      - 7.1*
      - 8.*
    paths-ignore: # When updating the list of expressions also update ci-docs.yml
      - '**.md'
      - '**.asciidoc'
      - '**.png'
      - '**.svg'
  pull_request:
    paths-ignore: # When updating the list of expressions also update ci-docs.yml
      - '**.md'
      - '**.asciidoc'
      - '**.png'
      - '**.svg'

# limit the access of the generated GITHUB_TOKEN
permissions:
  contents: read

jobs:
  buildkite:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dra-workflow: ["snapshot", "staging"]
    steps:
      # exclude if main and staging
      # exclude if branch is not supported anymore isBranchUnifiedReleaseAvailable()
      - uses: actions/checkout@v3

      - id: buildkite
        name: Run buildkite pipeline
        uses: elastic/apm-pipeline-library/.github/actions/buildkite@current
        with:
          vaultUrl: ${{ secrets.VAULT_ADDR }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
          #pipeline: apm-server-package
          pipeline: apm-server
          triggerMessage: "${{ matrix.dra-workflow }} - ${{ github.repository }}@${{ github.ref_name }}"
          waitFor: true
          printBuildLogs: true
          buildEnvVars: |
            GITHUB_SHA=${{ github.sha }}
            BRANCH_NAME=${{ github.ref_name }}
            DRA_WORKFLOW=${{ matrix.dra-workflow }}

      - if: failure()
        uses: elastic/apm-pipeline-library/.github/actions/notify-build-status@current
        with:
          vaultUrl: ${{ secrets.VAULT_ADDR }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
          #slackChannel: "#apm-server"
          slackChannel: "#observablt-bots"
