name: pre-commit

on:
  pull_request:
  push:
    branches:
      - main
      - 7.*
      - 8.*
      - 9.*

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: elastic/oblt-actions/pre-commit@31e93d1dfb82adc106fc7820f505db1afefe43b1 # v1
