name: smoke-tests-ess
run-name: Smoke Tests ESS

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string


# limit the access of the generated GITHUB_TOKEN
permissions:
  contents: read

jobs:
  prepare:
    name: Generate smoke tests list
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.generate.outputs.tests }}
      date: ${{ steps.generate.outputs.date }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - id: generate
        name: Generate matrix and date
        uses: ./.github/workflows/generate-smoke-tests-list

  smoke-tests-ess:
    name: Run smoke tests ${{ matrix.test }} for ${{ matrix.version }}
    runs-on: ubuntu-latest
    needs: prepare
    permissions:
      contents: read
      id-token: write
    env:
      TF_VAR_BUILD_ID: ${{ github.run_id }}
      TF_VAR_ENVIRONMENT: 'ci'
      TF_VAR_BRANCH: ${{ github.ref_name }}
      TF_VAR_REPO: ${{ github.repository }}
      TF_VAR_CREATED_DATE: ${{ needs.prepare.outputs.date }}
    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJSON(needs.prepare.outputs.tests) }}
        version:
          - '7.17'
          - 'latest'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - name: Setup cluster env
        uses: ./.github/workflows/setup-cluster-env

      - uses: elastic/oblt-actions/aws/auth@v1

      - uses: elastic/oblt-actions/google/auth@v1

      - uses: google-github-actions/get-secretmanager-secrets@95a0b09b8348ef3d02c68c6ba5662a037e78d713 # v2.1.4
        with:
          export_to_environment: true
          secrets: |-
            EC_API_KEY:elastic-observability/elastic-cloud-observability-team-pro-api-key

      - name: Run smoke tests ${{ matrix.test }} for ${{ matrix.version }}
        run: make smoketest/run-version TEST_DIR=${{ matrix.test }} SMOKETEST_VERSION=${{ matrix.version }}
      - if: always()
        name: Teardown smoke test infra
        run: make smoketest/cleanup TEST_DIR=${{ matrix.test }}
