name: smoke-tests-ess
run-name: Smoke Tests ESS

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string


# limit the access of the generated GITHUB_TOKEN
permissions:
  contents: read

jobs:
  prepare:
    name: Generate smoke tests list
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.generate.outputs.tests }}
      date: ${{ steps.generate.outputs.date }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - id: generate
        name: Generate matrix and date
        uses: ./.github/workflows/generate-smoke-tests-list
        with:
          vault-url: ${{ secrets.VAULT_ADDR }}
          vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
          vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}

  smoke-tests-ess:
    name: Run smoke tests ${{ matrix.test }} for ${{ matrix.version }}
    runs-on: ubuntu-latest
    needs: prepare
    env:
      TF_VAR_BUILD_ID: ${{ github.run_id }}
      TF_VAR_ENVIRONMENT: 'ci'
      TF_VAR_BRANCH: ${{ github.ref_name }}
      TF_VAR_REPO: ${{ github.repository }}
      TF_VAR_CREATED_DATE: ${{ needs.prepare.outputs.date }}
    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJSON(needs.prepare.outputs.tests) }}
        version:
          - '7.17'
          - 'latest'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - name: Setup cluster env
        uses: ./.github/workflows/setup-cluster-env
        with:
          vault-url: ${{ secrets.VAULT_ADDR }}
          vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
          vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}
          ec-key-secret: 'secret/observability-team/ci/elastic-cloud/observability-team-pro'
          aws-account-secret: 'secret/observability-team/ci/elastic-observability-aws-account-auth'
      - name: Run smoke tests ${{ matrix.test }} for ${{ matrix.version }}
        run: make smoketest/run-version TEST_DIR=${{ matrix.test }} SMOKETEST_VERSION=${{ matrix.version }}
      - if: always()
        name: Teardown smoke test infra
        run: make smoketest/cleanup TEST_DIR=${{ matrix.test }}
