name: smoke-tests-ess
run-name: Smoke Tests ESS

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
  workflow_dispatch: ~

# limit the access of the generated GITHUB_TOKEN
permissions:
  contents: read

jobs:
  prepare:
    name: Generate smoke tests list
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.generate.outputs.tests }}
      tests_legacy: ${{ steps.generate.outputs.tests_legacy }}
      date: ${{ steps.generate.outputs.date }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ inputs.branch }}
      - id: generate
        name: Generate matrix and date
        uses: ./.github/workflows/generate-smoke-tests-list

  smoke-tests-ess-legacy:
    name: Run smoke tests ${{ matrix.test }} for ${{ matrix.version }}
    runs-on: ubuntu-latest
    needs: prepare
    permissions:
      contents: read
      id-token: write
    env:
      TF_VAR_BUILD_ID: ${{ github.run_id }}
      TF_VAR_ENVIRONMENT: 'ci'
      TF_VAR_BRANCH: ${{ github.ref_name }}
      TF_VAR_REPO: ${{ github.repository }}
      TF_VAR_CREATED_DATE: ${{ needs.prepare.outputs.date }}
    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJSON(needs.prepare.outputs.tests_legacy) }}
        version:
          - '7.17'
          - 'latest'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - id: smoke_test
        name: Run smoke test action
        uses: ./.github/workflows/smoke-test-ess-action
        with:
          test: ${{ matrix.test }}
          version: ${{ matrix.version }}

  smoke-tests-ess:
    name: Run smoke tests ${{ matrix.test }} for ${{ matrix.version }}
    runs-on: ubuntu-latest
    needs: prepare
    permissions:
      contents: read
      id-token: write
    env:
      TF_VAR_BUILD_ID: ${{ github.run_id }}
      TF_VAR_ENVIRONMENT: 'ci'
      TF_VAR_BRANCH: ${{ github.ref_name }}
      TF_VAR_REPO: ${{ github.repository }}
      TF_VAR_CREATED_DATE: ${{ needs.prepare.outputs.date }}
    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJSON(needs.prepare.outputs.tests) }}
        version:
          - '7.17'
          - '8.16'
          - '8.17'
          - '8.18'
          - 'latest'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ inputs.branch }}
      - id: smoke_test
        name: Run smoke test action
        uses: ./.github/workflows/smoke-test-ess-action
        with:
          test: ${{ matrix.test }}
          version: ${{ matrix.version }}
