name: Terraform Format

on:
  push:
    paths:
      - '**.tf'
  pull_request:
    paths:
      - '**.tf'
  merge_group:

permissions:
  contents: read

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
      - run: terraform fmt -recursive -check -diff
