name: Terraform Format

on:
  push:
    paths:
      - '**.tf'
  pull_request:
    paths:
      - '**.tf'
  merge_group:

permissions:
  contents: read

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform fmt -recursive -check -diff
