name: Terraform Format

on:
  push:
    paths:
      - '**.tf'
  pull_request:
    paths:
      - '**.tf'
  merge_group:

permissions:
  contents: read

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
      - run: terraform fmt -recursive -check -diff
