name: Terraform Format

on:
  push:
    paths:
      - '**.tf'
  pull_request:
    paths:
      - '**.tf'
  merge_group:

permissions:
  contents: read

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
      - run: terraform fmt -recursive -check -diff
