## Workflow to process the JUnit test results and add a report to the checks.
name: system-test-reporter
on:
  workflow_run:
    workflows:
      - ci
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  system-test-results:
    runs-on: ubuntu-latest
    steps:
      - uses: elastic/oblt-actions/test-report@645d97cb15a7742c25352c2bd4d1e2ea0590c746 # v1
        with:
          artifact: /test-results-(.*)/     # artifact name pattern
          name: 'Test Results $1'        # Name of the check run which will be created
          path: "*.xml"                     # Path to test results (inside artifact .zip)
          reporter: java-junit              # Format of test results
